@startuml

    class DefaultVariableManager [[DefaultVariableManager.html]] {
        +DefaultVariableManager(Properties)
        +parseAndGetValue(Context, String): String
        +expandVariables(Context, String): String
        +getValue(Context, String, String): String
        +getVariable(Context, String): String
        +getValue(Context, String): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
