@startuml

    namespace org.apache.wiki.variables {

        interface VariableManager [[VariableManager.html]] {
            {static} +VAR_ERROR: String
            {static} +VAR_MSG: String
            {static} +VAR_RUNFILTERS: String
            {abstract} +parseAndGetValue(Context, String): String
            {abstract} +expandVariables(Context, String): String
            {abstract} +getValue(Context, String, String): String
            {abstract} +getVariable(Context, String): String
            {abstract} +getValue(Context, String): String
        }

        class DefaultVariableManager [[DefaultVariableManager.html]] {
            +DefaultVariableManager(Properties)
            +parseAndGetValue(Context, String): String
            +expandVariables(Context, String): String
            +getValue(Context, String, String): String
            +getVariable(Context, String): String
            +getValue(Context, String): String
        }

        VariableManager <|.. DefaultVariableManager

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
