@startuml

    class AllPermission [[AllPermission.html]] {
        #AllPermission()
        +AllPermission(String)
        +getActions(): String
        +getWiki(): String
        +implies(Permission): boolean
        +newPermissionCollection(): PermissionCollection
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
