@startuml

    namespace org.apache.wiki.auth.permissions {

        class PermissionFactory [[PermissionFactory.html]] {
            {static} +getPagePermission(WikiPage, String): PagePermission
            {static} +getPagePermission(String, String): PagePermission
        }

        class WikiPermission [[WikiPermission.html]] {
            {static} +CREATE_GROUPS_ACTION: String
            {static} +CREATE_PAGES_ACTION: String
            {static} +LOGIN_ACTION: String
            {static} +EDIT_PREFERENCES_ACTION: String
            {static} +EDIT_PROFILE_ACTION: String
            {static} +WILDCARD: String
            {static} #CREATE_GROUPS_MASK: int
            {static} #CREATE_PAGES_MASK: int
            {static} #EDIT_PREFERENCES_MASK: int
            {static} #EDIT_PROFILE_MASK: int
            {static} #LOGIN_MASK: int
            {static} +CREATE_GROUPS: WikiPermission
            {static} +CREATE_PAGES: WikiPermission
            {static} +LOGIN: WikiPermission
            {static} +EDIT_PREFERENCES: WikiPermission
            {static} +EDIT_PROFILE: WikiPermission
            +WikiPermission(String, String)
            +getActions(): String
            +getWiki(): String
            +implies(Permission): boolean
            +newPermissionCollection(): PermissionCollection
            {static} #impliedMask(int): int
            {static} #createMask(String): int
        }

        class PagePermission [[PagePermission.html]] {
            {static} +COMMENT_ACTION: String
            {static} +DELETE_ACTION: String
            {static} +EDIT_ACTION: String
            {static} +MODIFY_ACTION: String
            {static} +RENAME_ACTION: String
            {static} +UPLOAD_ACTION: String
            {static} +VIEW_ACTION: String
            {static} #COMMENT_MASK: int
            {static} #DELETE_MASK: int
            {static} #EDIT_MASK: int
            {static} #MODIFY_MASK: int
            {static} #RENAME_MASK: int
            {static} #UPLOAD_MASK: int
            {static} #VIEW_MASK: int
            {static} +COMMENT: PagePermission
            {static} +DELETE: PagePermission
            {static} +EDIT: PagePermission
            {static} +RENAME: PagePermission
            {static} +MODIFY: PagePermission
            {static} +UPLOAD: PagePermission
            {static} +VIEW: PagePermission
            #PagePermission()
            +PagePermission(String, String)
            +PagePermission(WikiPage, String)
            +getActions(): String
            +getPage(): String
            +getWiki(): String
            +implies(Permission): boolean
            +newPermissionCollection(): PermissionCollection
            {static} #impliedMask(int): int
            {static} #isSubset(String, String): boolean
            {static} #createMask(String): int
        }

        class AllPermissionCollection [[AllPermissionCollection.html]] {
            #m_permissions: Hashtable<Permission, Permission>
            +add(Permission): void
            +elements(): Enumeration<Permission>
            +implies(Permission): boolean
            +isReadOnly(): boolean
            +setReadOnly(): void
        }

        class GroupPermission [[GroupPermission.html]] {
            {static} +MEMBER_TOKEN: String
            {static} +DELETE_ACTION: String
            {static} +EDIT_ACTION: String
            {static} +VIEW_ACTION: String
            {static} #DELETE_MASK: int
            {static} #EDIT_MASK: int
            {static} #VIEW_MASK: int
            {static} +DELETE: GroupPermission
            {static} +EDIT: GroupPermission
            {static} +VIEW: GroupPermission
            #GroupPermission()
            +GroupPermission(String, String)
            +getActions(): String
            +getGroup(): String
            +getWiki(): String
            +implies(Permission): boolean
            {static} #impliedMask(int): int
            {static} #createMask(String): int
            #impliesMember(Permission): boolean
        }

        class AllPermission [[AllPermission.html]] {
            #AllPermission()
            +AllPermission(String)
            +getActions(): String
            +getWiki(): String
            +implies(Permission): boolean
            +newPermissionCollection(): PermissionCollection
            {static} #isJSPWikiPermission(Permission): boolean
        }

        abstract class java.security.Permission {
            {abstract} +implies(Permission): boolean
            {abstract} +getActions(): String
        }
        java.security.Permission <|-- WikiPermission

        interface java.io.Serializable
        java.io.Serializable <|.. WikiPermission

        java.security.Permission <|-- PagePermission

        java.io.Serializable <|.. PagePermission

        abstract class java.security.PermissionCollection {
            {abstract} +add(Permission): void
            {abstract} +implies(Permission): boolean
            {abstract} +elements(): Enumeration<Permission>
        }
        java.security.PermissionCollection <|-- AllPermissionCollection

        java.security.Permission <|-- GroupPermission

        java.io.Serializable <|.. GroupPermission

        java.security.Permission <|-- AllPermission

        java.io.Serializable <|.. AllPermission

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
