@startuml

    namespace org.apache.wiki.markdown.renderer {

        class JSPWikiLinkRenderer [[JSPWikiLinkRenderer.html]] {
            +getNodeRenderingHandlers(): Set<NodeRenderingHandler<?>>
        }

        class JSPWikiNodeRendererFactory [[JSPWikiNodeRendererFactory.html]] {
            +JSPWikiNodeRendererFactory(WikiContext)
            +apply(DataHolder): NodeRenderer
            +getDelegates(): Set<Class<?>>
        }

        interface com.vladsch.flexmark.html.renderer.NodeRenderer {
            {abstract} +getNodeRenderingHandlers(): Set<NodeRenderingHandler<?>>
        }
        com.vladsch.flexmark.html.renderer.NodeRenderer <|.. JSPWikiLinkRenderer

        interface com.vladsch.flexmark.html.renderer.DelegatingNodeRendererFactory {
            {abstract} +getDelegates(): Set<Class<?>>
        }
        com.vladsch.flexmark.html.renderer.DelegatingNodeRendererFactory <|.. JSPWikiNodeRendererFactory

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
