@startuml

    class AnonymousLoginModule [[AnonymousLoginModule.html]] {
        {static} +PROMPT: String
        {static} #log: Logger
        +login(): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
