@startuml

    class CookieAuthenticationLoginModule [[CookieAuthenticationLoginModule.html]] {
        {static} #COOKIE_DIR: String
        {static} +PROP_LOGIN_EXPIRY_DAYS: String
        +login(): boolean
        {static} +setLoginCookie(Engine, HttpServletResponse, String): void
        {static} +clearLoginCookie(Engine, HttpServletRequest, HttpServletResponse): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
