@startuml

    class WebContainerCallbackHandler [[WebContainerCallbackHandler.html]] {
        +WebContainerCallbackHandler(Engine, HttpServletRequest)
        +handle(Callback[]): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
