@startuml

    class WikiEngineCallback [[WikiEngineCallback.html]] {
        +setEngine(Engine): void
        +getEngine(): Engine
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
