@startuml

    class MarkdownForJSPWikiExtension [[MarkdownForJSPWikiExtension.html]] {
        +MarkdownForJSPWikiExtension(WikiContext)
        +rendererOptions(MutableDataHolder): void
        +parserOptions(MutableDataHolder): void
        +extend(HtmlRenderer.Builder, String): void
        +extend(Parser.Builder): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
