@startuml

    namespace org.apache.wiki.markdown {

        class MarkdownForJSPWikiExtension [[MarkdownForJSPWikiExtension.html]] {
            +MarkdownForJSPWikiExtension(WikiContext)
            +rendererOptions(MutableDataHolder): void
            +parserOptions(MutableDataHolder): void
            +extend(HtmlRenderer.Builder, String): void
            +extend(Parser.Builder): void
        }

        interface com.vladsch.flexmark.parser.Parser.ParserExtension {
            {abstract} +parserOptions(MutableDataHolder): void
            {abstract} +extend(Parser.Builder): void
        }
        com.vladsch.flexmark.parser.Parser.ParserExtension <|.. MarkdownForJSPWikiExtension

        interface com.vladsch.flexmark.html.HtmlRenderer.HtmlRendererExtension {
            {abstract} +rendererOptions(MutableDataHolder): void
            {abstract} +extend(HtmlRenderer.Builder, String): void
        }
        com.vladsch.flexmark.html.HtmlRenderer.HtmlRendererExtension <|.. MarkdownForJSPWikiExtension

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
