@startuml

    class FormOpen [[FormOpen.html]] {
        {static} +PARAM_METHOD: String
        +execute(Context, Map<String, String>): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
