@startuml

    namespace org.apache.wiki.spi {

        class EngineSPIDefaultImpl [[EngineSPIDefaultImpl.html]] {
            +find(ServletContext, Properties): Engine
        }

        class SessionSPIDefaultImpl [[SessionSPIDefaultImpl.html]] {
            +remove(Engine, HttpServletRequest): void
            +find(Engine, HttpServletRequest): Session
            +guest(Engine): Session
        }

        class ContextSPIDefaultImpl [[ContextSPIDefaultImpl.html]] {
            +create(Engine, Page): Context
            +create(Engine, HttpServletRequest, Command): Context
            +create(Engine, HttpServletRequest, Page): Context
            +create(Engine, HttpServletRequest, String): Context
        }

        class AclsSPIDefaultImpl [[AclsSPIDefaultImpl.html]] {
            +acl(): Acl
            +entry(): AclEntry
        }

        class ContentsSPIDefaultImpl [[ContentsSPIDefaultImpl.html]] {
            +attachment(Engine, String, String): Attachment
            +page(Engine, String): Page
        }

        interface org.apache.wiki.api.spi.EngineSPI {
            {abstract} +find(ServletContext, Properties): Engine
        }
        org.apache.wiki.api.spi.EngineSPI <|.. EngineSPIDefaultImpl

        interface org.apache.wiki.api.spi.SessionSPI {
            {abstract} +remove(Engine, HttpServletRequest): void
            {abstract} +find(Engine, HttpServletRequest): Session
            {abstract} +guest(Engine): Session
        }
        org.apache.wiki.api.spi.SessionSPI <|.. SessionSPIDefaultImpl

        interface org.apache.wiki.api.spi.ContextSPI {
            {abstract} +create(Engine, Page): Context
            {abstract} +create(Engine, HttpServletRequest, Command): Context
            {abstract} +create(Engine, HttpServletRequest, Page): Context
            {abstract} +create(Engine, HttpServletRequest, String): Context
        }
        org.apache.wiki.api.spi.ContextSPI <|.. ContextSPIDefaultImpl

        interface org.apache.wiki.api.spi.AclsSPI {
            {abstract} +acl(): Acl
            {abstract} +entry(): AclEntry
        }
        org.apache.wiki.api.spi.AclsSPI <|.. AclsSPIDefaultImpl

        interface org.apache.wiki.api.spi.ContentsSPI {
            {abstract} +attachment(Engine, String, String): Attachment
            {abstract} +page(Engine, String): Page
        }
        org.apache.wiki.api.spi.ContentsSPI <|.. ContentsSPIDefaultImpl

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
