@startuml

    namespace org.apache.wiki.render.markdown {

        class MarkdownRenderer [[MarkdownRenderer.html]] {
            +MarkdownRenderer(WikiContext, WikiDocument)
            +getString(): String
        }

        abstract class org.apache.wiki.render.WikiRenderer {
            {abstract} +getString(): String
        }
        org.apache.wiki.render.WikiRenderer <|-- MarkdownRenderer

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
