@startuml

    class Release [[Release.html]] {
        {static} +APPNAME: String
        {static} +VERSION: int
        {static} +REVISION: int
        {static} +MINORREVISION: int
        {static} +BUILD: String
        {static} +VERSTR: String
        {static} +getVersionString(): String
        {static} +isNewerOrEqual(String): boolean
        {static} +isOlderOrEqual(String): boolean
        {static} +main(String[]): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
