@startuml

    interface Watchable [[Watchable.html]] {
        {abstract} +timeoutExceeded(String): void
        {abstract} +getName(): String
        {abstract} +isAlive(): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
