@startuml

    class WikiPage [[WikiPage.html]] {
        {static} +DESCRIPTION: String
        {static} +ALIAS: String
        {static} +REDIRECT: String
        {static} +AUTHOR: String
        {static} +CHANGENOTE: String
        {static} +VIEWCOUNT: String
        +WikiPage(WikiEngine, String)
        +getName(): String
        +getAttribute(String): Object
        +setAttribute(String, Object): void
        +getAttributes(): Map<String, Object>
        +removeAttribute(String): Object
        +getLastModified(): Date
        +setLastModified(Date): void
        +setVersion(int): void
        +getVersion(): int
        +getSize(): long
        +setSize(long): void
        +getAcl(): Acl
        +setAcl(Acl): void
        +setAuthor(String): void
        +getAuthor(): String
        +getWiki(): String
        +invalidateMetadata(): void
        +hasMetadata(): boolean
        +setHasMetadata(): void
        +compareTo(WikiPage): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
