@startuml

    abstract class ProgressItem [[ProgressItem.html]] {
        {static} +CREATED: int
        {static} +STARTED: int
        {static} +STOPPED: int
        {static} +FINISHED: int
        #m_state: int
        +getState(): int
        +setState(int): void
        {abstract} +getProgress(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
