@startuml

    class ProgressManager [[ProgressManager.html]] {
        {static} +JSON_PROGRESSTRACKER: String
        +getNewProgressIdentifier(): String
        +startProgress(ProgressItem, String): void
        +stopProgress(String): void
        +getProgress(String): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
