@startuml

    class PagePermission [[PagePermission.html]] {
        {static} +COMMENT_ACTION: String
        {static} +DELETE_ACTION: String
        {static} +EDIT_ACTION: String
        {static} +MODIFY_ACTION: String
        {static} +RENAME_ACTION: String
        {static} +UPLOAD_ACTION: String
        {static} +VIEW_ACTION: String
        {static} #COMMENT_MASK: int
        {static} #DELETE_MASK: int
        {static} #EDIT_MASK: int
        {static} #MODIFY_MASK: int
        {static} #RENAME_MASK: int
        {static} #UPLOAD_MASK: int
        {static} #VIEW_MASK: int
        {static} +COMMENT: PagePermission
        {static} +DELETE: PagePermission
        {static} +EDIT: PagePermission
        {static} +RENAME: PagePermission
        {static} +MODIFY: PagePermission
        {static} +UPLOAD: PagePermission
        {static} +VIEW: PagePermission
        #PagePermission()
        +PagePermission(String, String)
        +PagePermission(Page, String)
        +getActions(): String
        +getPage(): String
        +getWiki(): String
        +implies(Permission): boolean
        +newPermissionCollection(): PermissionCollection
        {static} #impliedMask(int): int
        {static} #isSubset(String, String): boolean
        {static} #createMask(String): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
