@startuml

    class PermissionFactory [[PermissionFactory.html]] {
        {static} +getPagePermission(Page, String): PagePermission
        {static} +getPagePermission(String, String): PagePermission
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
