@startuml

    abstract class AbstractStep [[AbstractStep.html]] {
        #AbstractStep(String)
        +AbstractStep(Workflow, String)
        +addSuccessor(Outcome, Step): void
        +getAvailableOutcomes(): Collection<Outcome>
        +getErrors(): List<String>
        +getEndTime(): Date
        +getMessageArguments(): Serializable[]
        +getMessageKey(): String
        +getOutcome(): Outcome
        +getOwner(): Principal
        +getStartTime(): Date
        +getWorkflow(): Workflow
        +isCompleted(): boolean
        +isStarted(): boolean
        +setOutcome(Outcome): void
        +start(): void
        +getSuccessor(Outcome): Step
        +setWorkflow(Workflow): void
        #addError(String): void
        {abstract} +execute(): Outcome
        {abstract} +getActor(): Principal
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
