@startuml

    namespace org.apache.wiki.i18n {

        interface InternationalizationManager [[InternationalizationManager.html]] {
            {static} +CORE_BUNDLE: String
            {static} +DEF_TEMPLATE: String
            +get(String): String
            +getBundle(String, Locale): ResourceBundle
            +get(String, Locale, String): String
            +get(String, Locale, String, Object[]): String
        }

        class DefaultInternationalizationManager [[DefaultInternationalizationManager.html]] {
            +DefaultInternationalizationManager(Engine)
        }

        InternationalizationManager <|.. DefaultInternationalizationManager

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
