@startuml

    class BasicPageFilter <<deprecated>> [[BasicPageFilter.html]] {
        + --initialize-- (WikiEngine, Properties): void
        + --preTranslate-- (WikiContext, String): String
        + --preTranslate-- (Context, String): String
        + --postTranslate-- (WikiContext, String): String
        + --postTranslate-- (Context, String): String
        + --preSave-- (WikiContext, String): String
        + --preSave-- (Context, String): String
        + --postSave-- (WikiContext, String): void
        + --postSave-- (Context, String): void
        + --destroy-- (WikiEngine): void
        + --destroy-- (Engine): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
