@startuml

    namespace org.apache.wiki.api.filters {

        class BasicPageFilter [[BasicPageFilter.html]] {
            #m_engine: Engine
            +initialize(Engine, Properties): void
        }

        interface PageFilter [[PageFilter.html]] {
            +preTranslate(WikiContext, String): String
            +postTranslate(WikiContext, String): String
            +preSave(WikiContext, String): String
            +postSave(WikiContext, String): void
            +destroy(Engine): void
            {abstract} +initialize(Engine, Properties): void
        }

        PageFilter <|.. BasicPageFilter

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
