@startuml

    namespace org.apache.wiki.api.filters {

        class BasicPageFilter [[BasicPageFilter.html]] {
            #m_engine: WikiEngine
            +initialize(WikiEngine, Properties): void
            +preTranslate(WikiContext, String): String
            +postTranslate(WikiContext, String): String
            +preSave(WikiContext, String): String
            +postSave(WikiContext, String): void
            +destroy(WikiEngine): void
        }

        interface PageFilter [[PageFilter.html]] {
            {abstract} +initialize(WikiEngine, Properties): void
            {abstract} +preTranslate(WikiContext, String): String
            {abstract} +postTranslate(WikiContext, String): String
            {abstract} +preSave(WikiContext, String): String
            {abstract} +postSave(WikiContext, String): void
            {abstract} +destroy(WikiEngine): void
        }

        PageFilter <|.. BasicPageFilter

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
