@startuml

    class DefaultPageManager [[DefaultPageManager.html]] {
        #m_pageLocks: ConcurrentHashMap<String, PageLock>
        +DefaultPageManager(Engine, Properties)
        +getProvider(): WikiPageProvider
        +getAllPages(): Collection<WikiPage>
        +getPageText(String, int): String
        +getPureText(String, int): String
        +getText(String, int): String
        +saveText(WikiContext, String): void
        #getEngine(): Engine
        +putPageText(WikiPage, String): void
        +lockPage(WikiPage, String): PageLock
        +unlockPage(PageLock): void
        +getCurrentLock(WikiPage): PageLock
        +getActiveLocks(): List<PageLock>
        +getPage(String): WikiPage
        +getPage(String, int): WikiPage
        +getPageInfo(String, int): WikiPage
        +getVersionHistory(String): List<T>
        +getCurrentProvider(): String
        +getProviderDescription(): String
        +getTotalPageCount(): int
        +getRecentChanges(): Set<WikiPage>
        +pageExists(String): boolean
        +pageExists(String, int): boolean
        +wikiPageExists(String): boolean
        +wikiPageExists(String, int): boolean
        +deleteVersion(WikiPage): void
        +deletePage(String): void
        +deletePage(WikiPage): void
        #fireEvent(int, String): void
        +actionPerformed(WikiEvent): void
        #changeAcl(WikiPage, Principal[], Principal): boolean
        +getPageSorter(): PageSorter
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
