@startuml

    class DefaultPageManager [[DefaultPageManager.html]] {
        #m_pageLocks: ConcurrentHashMap<String, PageLock>
        +DefaultPageManager(Engine, Properties)
        +getProvider(): PageProvider
        +getAllPages(): Collection<Page>
        +getPageText(String, int): String
        +getPureText(String, int): String
        +getText(String, int): String
        +saveText(Context, String): void
        #getEngine(): Engine
        +putPageText(Page, String): void
        +lockPage(Page, String): PageLock
        +unlockPage(PageLock): void
        +getCurrentLock(Page): PageLock
        +getActiveLocks(): List<PageLock>
        +getPage(String): Page
        +getPage(String, int): Page
        +getPageInfo(String, int): Page
        +getVersionHistory(String): List<T>
        +getCurrentProvider(): String
        +getProviderDescription(): String
        +getTotalPageCount(): int
        +getRecentChanges(): Set<Page>
        +pageExists(String): boolean
        +pageExists(String, int): boolean
        +wikiPageExists(String): boolean
        +wikiPageExists(String, int): boolean
        +deleteVersion(Page): void
        +deletePage(String): void
        +deletePage(Page): void
        #fireEvent(int, String): void
        +actionPerformed(WikiEvent): void
        #changeAcl(WikiPage, Principal[], Principal): boolean
        +getPageSorter(): PageSorter
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
