@startuml

    interface Page [[Page.html]] {
        {static} +withUrl(String): PageBuilder
        {static} +baseUrl(): String
        {static} +download(String): File
        +title(): String
        +url(): String
        {abstract} +wikiTitle(): String
        {abstract} +wikiPageContent(): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
