@startuml

    class PageLock [[PageLock.html]] {
        +PageLock(Page, String, Date, Date)
        +getPage(): String
        +getLocker(): String
        +getAcquisitionTime(): Date
        +getExpiryTime(): Date
        +getTimeLeft(): long
        +isExpired(): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
