@startuml

    class DecisionQueue [[DecisionQueue.html]] {
        #add(Decision): void
        #decisions(): Decision[]
        #remove(Decision): void
        +getActorDecisions(Session): Collection<Decision>
        +decide(Decision, Outcome): void
        +reassign(Decision, Principal): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
