@startuml

    namespace org.apache.wiki.workflow {

        class WorkflowBuilder [[WorkflowBuilder.html]] {
            {static} +getBuilder(WikiEngine): WorkflowBuilder
            +buildApprovalWorkflow(Principal, String, Step, String, Fact[], Step, String): Workflow
        }

        abstract class Decision [[Decision.html]] {
            +Decision(Workflow, String, Principal, Outcome)
            +addFact(Fact): void
            +decide(Outcome): void
            +execute(): Outcome
            +getId(): int
            +isReassignable(): boolean
            +reassign(Principal): void
            +setId(int): void
        }

        class Fact [[Fact.html]] {
            +Fact(String, Serializable)
            +getMessageKey(): String
        }

        class SystemPrincipal [[SystemPrincipal.html]] {
            {static} +SYSTEM_USER: Principal
            +getName(): String
        }

        class SimpleNotification [[SimpleNotification.html]] {
            +SimpleNotification(Workflow, String, Principal)
            +acknowledge(): void
            +isReassignable(): boolean
        }

        class WorkflowManager [[WorkflowManager.html]] {
            {static} +WF_WP_SAVE_ATTR_PRESAVE_WIKI_CONTEXT: String
            {static} +WF_WP_SAVE_APPROVER: String
            {static} +WF_WP_SAVE_DECISION_MESSAGE_KEY: String
            {static} +WF_WP_SAVE_REJECT_MESSAGE_KEY: String
            {static} +WF_WP_SAVE_FACT_PAGE_NAME: String
            {static} +WF_WP_SAVE_FACT_DIFF_TEXT: String
            {static} +WF_WP_SAVE_FACT_CURRENT_TEXT: String
            {static} +WF_WP_SAVE_FACT_PROPOSED_TEXT: String
            {static} +WF_WP_SAVE_FACT_IS_AUTHENTICATED: String
            {static} +WF_UP_CREATE_SAVE_ATTR_SAVED_PROFILE: String
            {static} +WF_UP_CREATE_SAVE_APPROVER: String
            {static} +WF_UP_CREATE_SAVE_DECISION_MESSAGE_KEY: String
            {static} +WF_UP_CREATE_SAVE_FACT_SUBMITTER: String
            {static} +WF_UP_CREATE_SAVE_FACT_PREFS_LOGIN_NAME: String
            {static} +WF_UP_CREATE_SAVE_FACT_PREFS_FULL_NAME: String
            {static} +WF_UP_CREATE_SAVE_FACT_PREFS_EMAIL: String
            {static} #PROPERTY_APPROVER_PREFIX: String
            +start(Workflow): void
            +initialize(WikiEngine, Properties): void
            +requiresApproval(String): boolean
            +getApprover(String): Principal
            #getEngine(): WikiEngine
            +getOwnerWorkflows(WikiSession): Collection<Workflow>
            +actionPerformed(WikiEvent): void
            #add(Workflow): void
            #remove(Workflow): void
        }

        interface Step [[Step.html]] {
            {abstract} +addSuccessor(Outcome, Step): void
            {abstract} +getErrors(): List<String>
            {abstract} +execute(): Outcome
            {abstract} +getEndTime(): Date
            {abstract} +getMessageKey(): String
            {abstract} +getStartTime(): Date
            {abstract} +isCompleted(): boolean
            {abstract} +isStarted(): boolean
            {abstract} +start(): void
            {abstract} +getSuccessor(Outcome): Step
        }

        class Outcome [[Outcome.html]] {
            {static} +STEP_COMPLETE: Outcome
            {static} +STEP_ABORT: Outcome
            {static} +STEP_CONTINUE: Outcome
            {static} +DECISION_ACKNOWLEDGE: Outcome
            {static} +DECISION_APPROVE: Outcome
            {static} +DECISION_DENY: Outcome
            {static} +DECISION_HOLD: Outcome
            {static} +DECISION_REASSIGN: Outcome
            +isCompletion(): boolean
            +getMessageKey(): String
            {static} +forName(String): Outcome
        }

        class Workflow [[Workflow.html]] {
            {static} +TIME_NOT_SET: Date
            {static} +ID_NOT_SET: int
            {static} +COMPLETED: int
            {static} +ABORTED: int
            {static} +WAITING: int
            {static} +RUNNING: int
            {static} +CREATED: int
            +Workflow(String, Principal)
            +abort(): void
            +addMessageArgument(Serializable): void
            +getCurrentState(): int
            +getAttribute(String): Object
            +getEndTime(): Date
            +getId(): int
            +getMessageKey(): String
            +getStartTime(): Date
            +isAborted(): boolean
            +isCompleted(): boolean
            +isStarted(): boolean
            +restart(): void
            +setAttribute(String, Object): void
            +setId(int): void
            +start(): void
            +waitstate(): void
            #cleanup(): void
            #complete(): void
            #previousStep(Step): Step
            #processCurrentStep(): void
            +addWikiEventListener(WikiEventListener): void
            +removeWikiEventListener(WikiEventListener): void
            #fireEvent(int): void
        }

        class DecisionRequiredException [[DecisionRequiredException.html]] {
            +DecisionRequiredException(String)
        }

        class DecisionQueue [[DecisionQueue.html]] {
            #add(Decision): void
            #decisions(): Decision[]
            #remove(Decision): void
            +getActorDecisions(WikiSession): Collection<Decision>
            +decide(Decision, Outcome): void
            +reassign(Decision, Principal): void
        }

        abstract class AbstractStep [[AbstractStep.html]] {
            #AbstractStep(String)
            +AbstractStep(Workflow, String)
            +addSuccessor(Outcome, Step): void
            +getErrors(): List<String>
            +getEndTime(): Date
            +getMessageKey(): String
            +getStartTime(): Date
            +isCompleted(): boolean
            +isStarted(): boolean
            +start(): void
            +getSuccessor(Outcome): Step
            #addError(String): void
            {abstract} +execute(): Outcome
        }

        abstract class Task [[Task.html]] {
            +Task(String)
            +Task(Workflow, String)
        }

        class NoSuchOutcomeException [[NoSuchOutcomeException.html]] {
            +NoSuchOutcomeException(String)
        }

        class SimpleDecision [[SimpleDecision.html]] {
            +SimpleDecision(Workflow, String, Principal)
        }

        AbstractStep <|-- Decision

        interface java.io.Serializable
        java.io.Serializable <|.. Fact

        interface java.security.Principal {
            {abstract} +getName(): String
        }
        java.security.Principal <|.. SystemPrincipal

        Decision <|-- SimpleNotification

        interface org.apache.wiki.event.WikiEventListener {
            {abstract} +actionPerformed(WikiEvent): void
        }
        org.apache.wiki.event.WikiEventListener <|.. WorkflowManager

        java.io.Serializable <|.. Step

        java.io.Serializable <|.. Outcome

        java.io.Serializable <|.. Workflow

        class org.apache.wiki.api.exceptions.WikiException
        org.apache.wiki.api.exceptions.WikiException <|-- DecisionRequiredException

        java.io.Serializable <|.. DecisionQueue

        Step <|.. AbstractStep

        AbstractStep <|-- Task

        org.apache.wiki.api.exceptions.WikiException <|-- NoSuchOutcomeException

        Decision <|-- SimpleDecision

        Decision --> java.security.Principal: actor

        Decision --> Outcome: defaultOutcome

        Decision --> "*" Fact: facts

        Fact --> java.io.Serializable: value

        WorkflowManager --> "*" Workflow: workflows\ncompletedWorkflows

        WorkflowManager --> DecisionQueue: decisionQueue

        Step --> "*" Outcome: availableOutcomes

        Step --> java.security.Principal: actor\nowner

        Step --> "*" java.io.Serializable: messageArguments

        Step --> Outcome: outcome

        Step --> Workflow: workflow

        Workflow --> java.security.Principal: currentActor\nowner

        Workflow --> Step: currentStep\npreviousStep\nfirstStep

        Workflow --> "*" java.io.Serializable: messageArguments

        Workflow --> WorkflowManager: workflowManager

        Workflow --> "*" Step: history

        AbstractStep --> "*" Outcome: availableOutcomes

        AbstractStep --> "*" java.io.Serializable: messageArguments

        AbstractStep --> Outcome: outcome

        AbstractStep --> java.security.Principal: owner\nactor

        AbstractStep --> Workflow: workflow

        Task --> java.security.Principal: actor

        Task --> Step: successor

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
