@startuml

    interface Step [[Step.html]] {
        {abstract} +addSuccessor(Outcome, Step): void
        {abstract} +getAvailableOutcomes(): Collection<Outcome>
        {abstract} +getErrors(): List<String>
        {abstract} +execute(): Outcome
        {abstract} +getActor(): Principal
        {abstract} +getEndTime(): Date
        {abstract} +getMessageKey(): String
        {abstract} +getMessageArguments(): Serializable[]
        {abstract} +getOutcome(): Outcome
        {abstract} +getStartTime(): Date
        {abstract} +getWorkflow(): Workflow
        {abstract} +isCompleted(): boolean
        {abstract} +isStarted(): boolean
        {abstract} +start(): void
        {abstract} +setOutcome(Outcome): void
        {abstract} +getOwner(): Principal
        {abstract} +getSuccessor(Outcome): Step
        {abstract} +setWorkflow(Workflow): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
