@startuml

    namespace org.apache.wiki.auth.authorize {

        class Group [[Group.html]] {
            #Group(String, String)
            +add(Principal): boolean
            +clear(): void
            +getCreated(): Date
            +getCreator(): String
            +getLastModified(): Date
            +getModifier(): String
            +getName(): String
            +getWiki(): String
            +isMember(Principal): boolean
            +members(): Principal[]
            +remove(Principal): boolean
            +setCreated(Date): void
            +setCreator(String): void
            +setLastModified(Date): void
            +setModifier(String): void
        }

        interface WebAuthorizer [[WebAuthorizer.html]] {
            {abstract} +isUserInRole(HttpServletRequest, Principal): boolean
        }

        class JDBCGroupDatabase [[JDBCGroupDatabase.html]] {
            {static} +DEFAULT_GROUPDB_DATASOURCE: String
            {static} +DEFAULT_GROUPDB_TABLE: String
            {static} +DEFAULT_GROUPDB_MEMBER_TABLE: String
            {static} +DEFAULT_GROUPDB_CREATED: String
            {static} +DEFAULT_GROUPDB_CREATOR: String
            {static} +DEFAULT_GROUPDB_NAME: String
            {static} +DEFAULT_GROUPDB_MEMBER: String
            {static} +DEFAULT_GROUPDB_MODIFIED: String
            {static} +DEFAULT_GROUPDB_MODIFIER: String
            {static} +PROP_GROUPDB_DATASOURCE: String
            {static} +PROP_GROUPDB_TABLE: String
            {static} +PROP_GROUPDB_MEMBER_TABLE: String
            {static} +PROP_GROUPDB_CREATED: String
            {static} +PROP_GROUPDB_CREATOR: String
            {static} +PROP_GROUPDB_NAME: String
            {static} +PROP_GROUPDB_MEMBER: String
            {static} +PROP_GROUPDB_MODIFIED: String
            {static} +PROP_GROUPDB_MODIFIER: String
            {static} #log: Logger
            +delete(Group): void
            +groups(): Group[]
            +save(Group, Principal): void
            +initialize(WikiEngine, Properties): void
        }

        class GroupManager [[GroupManager.html]] {
            {static} +MESSAGES_KEY: String
            #m_engine: WikiEngine
            +findRole(String): Principal
            +getGroup(String): Group
            +initialize(WikiEngine, Properties): void
            +isUserInRole(WikiSession, Principal): boolean
            +parseGroup(String, String, boolean): Group
            +parseGroup(WikiContext, boolean): Group
            +removeGroup(String): void
            +setGroup(WikiSession, Group): void
            +validateGroup(WikiContext, Group): void
            #extractMembers(String): String[]
            #checkGroupName(WikiContext, String): void
            +addWikiEventListener(WikiEventListener): void
            +removeWikiEventListener(WikiEventListener): void
            #fireEvent(int, Object): void
            +actionPerformed(WikiEvent): void
        }

        class WebContainerAuthorizer [[WebContainerAuthorizer.html]] {
            {static} #log: Logger
            #m_engine: WikiEngine
            #m_containerAuthorized: boolean
            +initialize(WikiEngine, Properties): void
            +isUserInRole(HttpServletRequest, Principal): boolean
            +isUserInRole(WikiSession, Principal): boolean
            +findRole(String): Principal
            +isConstrained(String, Role): boolean
            +isContainerAuthorized(): boolean
            #getRoles(Document): Role[]
            #getWebXml(): Document
        }

        class org.apache.wiki.auth.authorize.WebContainerAuthorizer.LocalEntityResolver [[WebContainerAuthorizer.LocalEntityResolver.html]] {
            +resolveEntity(String, String): InputSource
        }

        interface GroupDatabase [[GroupDatabase.html]] {
            {abstract} +delete(Group): void
            {abstract} +initialize(WikiEngine, Properties): void
            {abstract} +save(Group, Principal): void
            {abstract} +groups(): Group[]
        }

        class XMLGroupDatabase [[XMLGroupDatabase.html]] {
            {static} #log: Logger
            {static} +PROP_DATABASE: String
            +delete(Group): void
            +groups(): Group[]
            +initialize(WikiEngine, Properties): void
            +save(Group, Principal): void
        }

        class Role [[Role.html]] {
            {static} +ALL: Role
            {static} +ANONYMOUS: Role
            {static} +ASSERTED: Role
            {static} +AUTHENTICATED: Role
            #Role()
            +Role(String)
            {static} +isBuiltInRole(Role): boolean
            {static} +isReservedName(String): boolean
            +getName(): String
        }

        interface org.apache.wiki.auth.Authorizer {
            {abstract} +getRoles(): Principal[]
            {abstract} +findRole(String): Principal
            {abstract} +initialize(WikiEngine, Properties): void
            {abstract} +isUserInRole(WikiSession, Principal): boolean
        }
        org.apache.wiki.auth.Authorizer <|.. WebAuthorizer

        GroupDatabase <|.. JDBCGroupDatabase

        org.apache.wiki.auth.Authorizer <|.. GroupManager

        interface org.apache.wiki.event.WikiEventListener {
            {abstract} +actionPerformed(WikiEvent): void
        }
        org.apache.wiki.event.WikiEventListener <|.. GroupManager

        WebAuthorizer <|.. WebContainerAuthorizer

        interface org.xml.sax.EntityResolver {
            {abstract} +resolveEntity(String, String): InputSource
        }
        org.xml.sax.EntityResolver <|.. org.apache.wiki.auth.authorize.WebContainerAuthorizer.LocalEntityResolver

        WebContainerAuthorizer +-- org.apache.wiki.auth.authorize.WebContainerAuthorizer.LocalEntityResolver

        GroupDatabase <|.. XMLGroupDatabase

        interface java.security.Principal {
            {abstract} +getName(): String
        }
        java.security.Principal <|.. Role

        interface java.io.Serializable
        java.io.Serializable <|.. Role

        Group --> java.security.Principal: principal

        GroupManager --> org.apache.wiki.event.WikiEventListener: m_groupListener

        GroupManager --> GroupDatabase: groupDatabase

        GroupManager --> "*" java.security.Principal: roles

        WebContainerAuthorizer --> "*" Role: m_containerRoles

        WebContainerAuthorizer --> "*" java.security.Principal: roles

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
