@startuml

    class FormInput [[FormInput.html]] {
        {static} +PARAM_TYPE: String
        {static} +PARAM_SIZE: String
        {static} +PARAM_CHECKED: String
        +execute(WikiContext, Map<String, String>): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
