@startuml

    namespace org.apache.wiki.forms {

        abstract class FormElement [[FormElement.html]] {
            {static} +HANDLERPARAM_PREFIX: String
            {static} +FORM_VALUES_CARRIER: String
            {static} +HIDE_SUCCESS: String
            {static} +PARAM_SUBMITHANDLER: String
            {static} +PARAM_ELEMENT: String
            {static} +PARAM_HANDLER: String
            {static} +PARAM_FORM: String
            {static} +PARAM_INPUTNAME: String
            {static} +PARAM_VALUE: String
            {static} +PARAM_HIDEFORM: String
            {static} +PARAM_POPULATE: String
            {static} +PARAM_FORMNAMEHIDDEN: String
            #storeFormInfo(Context, FormInfo): void
            #getFormInfo(Context): FormInfo
        }

        class FormInfo [[FormInfo.html]] {
            {static} +EXECUTED: int
            {static} +OK: int
            {static} +ERROR: int
            +setStatus(int): void
            +getStatus(): int
            +setHide(boolean): void
            +hide(): boolean
            +setAction(String): void
            +getAction(): String
            +setName(String): void
            +getName(): String
            +setHandler(String): void
            +getHandler(): String
            +setResult(String): void
            +getResult(): String
            +setError(String): void
            +getError(): String
            +setSubmission(Map<String, String>): void
            +addSubmission(Map<String, String>): void
            +getSubmission(): Map<String, String>
        }

        class FormOpen [[FormOpen.html]] {
            {static} +PARAM_METHOD: String
            +execute(Context, Map<String, String>): String
        }

        interface FormHandler [[FormHandler.html]] {
        }

        class FormClose [[FormClose.html]] {
            +execute(Context, Map<String, String>): String
        }

        class FormTextarea [[FormTextarea.html]] {
            {static} +PARAM_ROWS: String
            {static} +PARAM_COLS: String
            +execute(Context, Map<String, String>): String
        }

        class FormSelect [[FormSelect.html]] {
            +execute(Context, Map<String, String>): String
        }

        class FormInput [[FormInput.html]] {
            {static} +PARAM_TYPE: String
            {static} +PARAM_SIZE: String
            {static} +PARAM_CHECKED: String
            +execute(Context, Map<String, String>): String
        }

        class FormOutput [[FormOutput.html]] {
            +execute(Context, Map<String, String>): String
        }

        class FormSet [[FormSet.html]] {
            +execute(Context, Map<String, String>): String
        }

        interface org.apache.wiki.api.plugin.Plugin {
            {abstract} +execute(Context, Map<String, String>): String
        }
        org.apache.wiki.api.plugin.Plugin <|.. FormElement

        interface java.io.Serializable
        java.io.Serializable <|.. FormInfo

        FormElement <|-- FormOpen

        FormElement <|-- FormClose

        FormElement <|-- FormTextarea

        FormElement <|-- FormSelect

        FormElement <|-- FormInput

        FormElement <|-- FormOutput

        org.apache.wiki.api.plugin.Plugin <|.. FormSet

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
