@startuml

    namespace org.apache.wiki.ajax {

        class WikiAjaxDispatcherServlet [[WikiAjaxDispatcherServlet.html]] {
            +init(ServletConfig): void
            {static} +registerServlet(WikiAjaxServlet): void
            {static} +registerServlet(String, WikiAjaxServlet): void
            {static} +registerServlet(String, WikiAjaxServlet, Permission): void
            +doPost(HttpServletRequest, HttpServletResponse): void
            +doGet(HttpServletRequest, HttpServletResponse): void
            +getServletName(String): String
            +findServletByName(String): WikiAjaxServlet
        }

        class AjaxUtil [[AjaxUtil.html]] {
            {static} +toJson(Object): String
            {static} +getNextPathPart(String, String): String
        }

        interface WikiAjaxServlet [[WikiAjaxServlet.html]] {
            {abstract} +getServletMapping(): String
            {abstract} +service(HttpServletRequest, HttpServletResponse, String, List<String>): void
        }

        abstract class javax.servlet.http.HttpServlet
        javax.servlet.http.HttpServlet <|-- WikiAjaxDispatcherServlet

        javax.servlet.http.HttpServlet <|-- AjaxUtil

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
