@startuml

    class FormInfo [[FormInfo.html]] {
        {static} +EXECUTED: int
        {static} +OK: int
        {static} +ERROR: int
        +setStatus(int): void
        +getStatus(): int
        +setHide(boolean): void
        +hide(): boolean
        +setAction(String): void
        +getAction(): String
        +setName(String): void
        +getName(): String
        +setHandler(String): void
        +getHandler(): String
        +setResult(String): void
        +getResult(): String
        +setError(String): void
        +getError(): String
        +setSubmission(Map<String, String>): void
        +addSubmission(Map<String, String>): void
        +getSubmission(): Map<String, String>
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
