@startuml

    abstract class ModuleManager [[ModuleManager.html]] {
        {static} +PLUGIN_RESOURCE_LOCATION: String
        #m_engine: WikiEngine
        +ModuleManager(WikiEngine)
        +checkCompatibility(WikiModuleInfo): boolean
        #modules(Iterator<T>): Collection<WikiModuleInfo>
        {abstract} +modules(): Collection<WikiModuleInfo>
        {abstract} +getModuleInfo(String): WikiModuleInfo
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
