@startuml

    class CreoleToJSPWikiTranslator [[CreoleToJSPWikiTranslator.html]] {
        {static} +VAR_VERSION: String
        {static} +VAR_CREOLE_VERSION: String
        {static} +VAR_LINEBREAK_BLOGLIKE: String
        {static} +VAR_LINEBREAK_C2LIKE: String
        +translateSignature(Properties, String, String): String
        +translate(Properties, String): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
