@startuml

    class LinkParsingOperations [[LinkParsingOperations.html]] {
        +LinkParsingOperations(WikiContext)
        +isAccessRule(String): boolean
        +isPluginLink(String): boolean
        +isMetadata(String): boolean
        +isVariableLink(String): boolean
        +isInterWikiLink(String): boolean
        +interWikiLinkAt(String): int
        +isExternalLink(String): boolean
        +isImageLink(String): boolean
        +linkExists(String): boolean
        +linkIfExists(String): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
