@startuml

    class ContentTag [[ContentTag.html]] {
        +setView(String): void
        +setDiff(String): void
        +setInfo(String): void
        +setPreview(String): void
        +setConflict(String): void
        +setFind(String): void
        +setPrefs(String): void
        +setError(String): void
        +setEdit(String): void
        +setComment(String): void
        +doWikiStartTag(): int
        +doEndTag(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
