@startuml

    class EditLinkTag [[EditLinkTag.html]] {
        +m_version: String
        +m_title: String
        +m_accesskey: String
        +initTag(): void
        +setVersion(String): void
        +setTitle(String): void
        +setAccesskey(String): void
        +doWikiStartTag(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
