@startuml

    class IncludeTag [[IncludeTag.html]] {
        #m_page: String
        +initTag(): void
        +setPage(String): void
        +getPage(): String
        +doWikiStartTag(): int
        +doEndTag(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
