@startuml

    class InsertPageTag [[InsertPageTag.html]] {
        {static} +HTML: int
        {static} +PLAIN: int
        #m_pageName: String
        +initTag(): void
        +setPage(String): void
        +getPage(): String
        +setMode(String): void
        +doWikiStartTag(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
