@startuml

    abstract class IteratorTag [[IteratorTag.html]] {
        #m_pageName: String
        #m_iterator: Iterator<?>
        #m_wikiContext: Context
        +setList(Collection<?>): void
        +setList(Object[]): void
        +clearList(): void
        +resetIterator(): void
        +doStartTag(): int
        +doEndTag(): int
        +doAfterBody(): int
        +doCatch(Throwable): void
        +doFinally(): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
