@startuml

    class LinkTag [[LinkTag.html]] {
        +initTag(): void
        +setTemplatefile(String): void
        +setAccessKey(String): void
        +setAbsolute(String): void
        +getVersion(): String
        +setVersion(String): void
        +setCssClass(String): void
        +setStyle(String): void
        +setTitle(String): void
        +setTarget(String): void
        +setTabindex(String): void
        +setCompareToVersion(String): void
        +setRel(String): void
        +setRef(String): void
        +setJsp(String): void
        +setContext(String): void
        +setContainedParameter(String, String): void
        +doWikiStartTag(): int
        +doEndTag(): int
        +setBodyContent(BodyContent): void
        +doInitBody(): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
