@startuml

    namespace org.apache.wiki.tags {

        class IncludeResourcesTag [[IncludeResourcesTag.html]] {
            +initTag(): void
            +setType(String): void
            +doWikiStartTag(): int
        }

        class LinkTag [[LinkTag.html]] {
            +initTag(): void
            +setTemplatefile(String): void
            +setAccessKey(String): void
            +setAbsolute(String): void
            +getVersion(): String
            +setVersion(String): void
            +setCssClass(String): void
            +setStyle(String): void
            +setTitle(String): void
            +setTarget(String): void
            +setTabindex(String): void
            +setCompareToVersion(String): void
            +setRel(String): void
            +setRef(String): void
            +setJsp(String): void
            +setContext(String): void
            +setContainedParameter(String, String): void
            +doWikiStartTag(): int
            +doEndTag(): int
            +setBodyContent(BodyContent): void
            +doInitBody(): void
        }

        class CommentLinkTag [[CommentLinkTag.html]] {
            +doWikiStartTag(): int
        }

        class HistoryIteratorInfo [[HistoryIteratorInfo.html]] {
            +getVariableInfo(TagData): VariableInfo[]
        }

        class ParentPageNameTag [[ParentPageNameTag.html]] {
            +doWikiStartTag(): int
        }

        abstract class WikiLinkTag [[WikiLinkTag.html]] {
            {static} +ANCHOR: int
            {static} +URL: int
            #m_pageName: String
            #m_format: int
            #m_template: String
            +initTag(): void
            +setPage(String): void
            +getPage(): String
            +getTemplate(): String
            +setTemplate(String): void
            +setFormat(String): void
            +doEndTag(): int
        }

        class ContentTag [[ContentTag.html]] {
            +setView(String): void
            +setDiff(String): void
            +setInfo(String): void
            +setPreview(String): void
            +setConflict(String): void
            +setFind(String): void
            +setPrefs(String): void
            +setError(String): void
            +setEdit(String): void
            +setComment(String): void
            +doWikiStartTag(): int
            +doEndTag(): int
        }

        class NoSuchPageTag [[NoSuchPageTag.html]] {
            +initTag(): void
            +setPage(String): void
            +getPage(): String
            +doWikiStartTag(): int
        }

        class AuthorTag [[AuthorTag.html]] {
            +m_format: String
            +setFormat(String): void
            +doWikiStartTag(): int
        }

        class CheckVersionTag [[CheckVersionTag.html]] {
            +initTag(): void
            +setMode(String): void
            +doWikiStartTag(): int
        }

        class SearchResultIteratorInfo [[SearchResultIteratorInfo.html]] {
            +getVariableInfo(TagData): VariableInfo[]
        }

        class SearchResultIteratorTag [[SearchResultIteratorTag.html]] {
            +release(): void
            +setMaxItems(int): void
            +setStart(int): void
            +doStartTag(): int
            +doAfterBody(): int
            +doEndTag(): int
        }

        class FeedDiscoveryTag [[FeedDiscoveryTag.html]] {
            +doWikiStartTag(): int
        }

        class CalendarTag [[CalendarTag.html]] {
            +initTag(): void
            +setPageformat(String): void
            +setUrlformat(String): void
            +setMonthurlformat(String): void
            +doWikiStartTag(): int
        }

        class PageInfoLinkTag [[PageInfoLinkTag.html]] {
            +m_title: String
            +m_accesskey: String
            +setTitle(String): void
            +setAccesskey(String): void
            +doWikiStartTag(): int
        }

        class TemplateDirTag [[TemplateDirTag.html]] {
            +doWikiStartTag(): int
        }

        class UserProfileTag [[UserProfileTag.html]] {
            {static} +BLANK: String
            +initTag(): void
            +doWikiStartTag(): int
            +setProperty(String): void
            {static} +printGroups(WikiContext): String
            {static} +printRoles(WikiContext): String
        }

        class AdminBeanIteratorTag [[AdminBeanIteratorTag.html]] {
            +setType(String): void
            +resetIterator(): void
        }

        class SetPaginationTag [[SetPaginationTag.html]] {
            +initTag(): void
            +setStart(int): void
            +setTotal(int): void
            +setPagesize(int): void
            +setMaxlinks(int): void
            +setFmtkey(String): void
            +setHref(String): void
            +setOnclick(String): void
            +doWikiStartTag(): int
        }

        class ContentEncodingTag [[ContentEncodingTag.html]] {
            +doWikiStartTag(): int
        }

        class TabTag [[TabTag.html]] {
            +doFinally(): void
            +setTitle(String): void
            +setAccesskey(String): void
            +setUrl(String): void
            +doWikiStartTag(): int
            +doEndTag(): int
        }

        class AttachmentsIteratorInfo [[AttachmentsIteratorInfo.html]] {
            +getVariableInfo(TagData): VariableInfo[]
        }

        class IncludeTag [[IncludeTag.html]] {
            #m_page: String
            +initTag(): void
            +setPage(String): void
            +getPage(): String
            +doWikiStartTag(): int
            +doEndTag(): int
        }

        class PermissionTag [[PermissionTag.html]] {
            +initTag(): void
            +setPermission(String): void
            +doWikiStartTag(): int
        }

        class EditorIteratorInfo [[EditorIteratorInfo.html]] {
            +getVariableInfo(TagData): VariableInfo[]
        }

        class SearchResultsTag [[SearchResultsTag.html]] {
            +doWikiStartTag(): int
        }

        class RSSImageLinkTag [[RSSImageLinkTag.html]] {
            #m_title: String
            +initTag(): void
            +setTitle(String): void
            +setMode(String): void
            +getTitle(): String
            +doWikiStartTag(): int
        }

        abstract class WikiBodyTag [[WikiBodyTag.html]] {
            #m_wikiContext: WikiContext
            +doStartTag(): int
            +doCatch(Throwable): void
            +doFinally(): void
            {abstract} +doWikiStartTag(): int
        }

        abstract class IteratorTag [[IteratorTag.html]] {
            #m_pageName: String
            #m_iterator: Iterator<?>
            #m_wikiContext: WikiContext
            +setList(Collection<?>): void
            +setList(Object[]): void
            +clearList(): void
            +resetIterator(): void
            +doStartTag(): int
            +doEndTag(): int
            +doAfterBody(): int
            +doCatch(Throwable): void
            +doFinally(): void
        }

        class UserNameTag [[UserNameTag.html]] {
            +doWikiStartTag(): int
        }

        class EditorTag [[EditorTag.html]] {
            +doWikiStartTag(): int
            +doEndTag(): int
        }

        abstract class WikiTagBase [[WikiTagBase.html]] {
            {static} +ATTR_CONTEXT: String
            #m_wikiContext: WikiContext
            +setPageContext(PageContext): void
            +initTag(): void
            +doStartTag(): int
            +doEndTag(): int
            +doCatch(Throwable): void
            +doFinally(): void
            +setId(String): void
            {abstract} +doWikiStartTag(): int
        }

        class SearchResultsSizeTag [[SearchResultsSizeTag.html]] {
            +doWikiStartTag(): int
        }

        class HasAttachmentsTag [[HasAttachmentsTag.html]] {
            +doWikiStartTag(): int
        }

        class CookieTag [[CookieTag.html]] {
            +setName(String): void
            +setItem(String): void
            +setValue(String): void
            +setVar(String): void
            +setClear(String): void
            +setScope(String): void
            +release(): void
            +doEndTag(): int
        }

        class IfNoSearchResultsTag [[IfNoSearchResultsTag.html]] {
            +doWikiStartTag(): int
        }

        class BaseURLTag [[BaseURLTag.html]] {
            +doWikiStartTag(): int
        }

        class PageNameTag [[PageNameTag.html]] {
            +doWikiStartTag(): int
        }

        class AdminBeanIteratorInfo [[AdminBeanIteratorInfo.html]] {
            +getVariableInfo(TagData): VariableInfo[]
        }

        class InsertDiffTag [[InsertDiffTag.html]] {
            {static} +ATTR_OLDVERSION: String
            {static} +ATTR_NEWVERSION: String
            #m_pageName: String
            +initTag(): void
            +setPage(String): void
            +getPage(): String
            +doWikiStartTag(): int
        }

        class VariableTag [[VariableTag.html]] {
            +initTag(): void
            +getVar(): String
            +setVar(String): void
            +setDefault(String): void
            +doWikiStartTag(): int
        }

        class TabbedSectionTag [[TabbedSectionTag.html]] {
            +release(): void
            +setDefaultTab(String): void
            +validateDefaultTab(String): boolean
            +doStartTag(): int
            +isStateFindDefaultTab(): boolean
            +isStateGenerateTabMenu(): boolean
            +isStateGenerateTabBody(): boolean
            +doAfterBody(): int
            +doEndTag(): int
        }

        class TranslateTag [[TranslateTag.html]] {
            +doAfterBody(): int
        }

        class NextVersionTag [[NextVersionTag.html]] {
            +doWikiStartTag(): int
        }

        class InsertPageTag [[InsertPageTag.html]] {
            {static} +HTML: int
            {static} +PLAIN: int
            #m_pageName: String
            +initTag(): void
            +setPage(String): void
            +getPage(): String
            +setMode(String): void
            +doWikiStartTag(): int
        }

        class MessagesTag [[MessagesTag.html]] {
            +initTag(): void
            +setTopic(String): void
            +setPrefix(String): void
            +setDiv(String): void
            +setAction(String): void
            +doWikiStartTag(): int
        }

        class DiffLinkTag [[DiffLinkTag.html]] {
            {static} +VER_LATEST: String
            {static} +VER_PREVIOUS: String
            {static} +VER_CURRENT: String
            +initTag(): void
            +getVersion(): String
            +setVersion(String): void
            +getNewVersion(): String
            +setNewVersion(String): void
            +doWikiStartTag(): int
        }

        interface ParamHandler [[ParamHandler.html]] {
            {abstract} +setContainedParameter(String, String): void
        }

        class ParamTag [[ParamTag.html]] {
            +release(): void
            +setName(String): void
            +setValue(String): void
            +doEndTag(): int
        }

        class BreadcrumbsTag [[BreadcrumbsTag.html]] {
            {static} +BREADCRUMBTRAIL_KEY: String
            +initTag(): void
            +getMaxpages(): int
            +setMaxpages(int): void
            +getSeparator(): String
            +setSeparator(String): void
            +doWikiStartTag(): int
        }

        class org.apache.wiki.tags.BreadcrumbsTag.FixedQueue [[BreadcrumbsTag.FixedQueue.html]] {
            +removeItem(String): void
        }

        class UserCheckTag [[UserCheckTag.html]] {
            +initTag(): void
            +getStatus(): String
            +setStatus(String): void
            +doWikiStartTag(): int
        }

        class EditLinkTag [[EditLinkTag.html]] {
            +m_version: String
            +m_title: String
            +m_accesskey: String
            +initTag(): void
            +setVersion(String): void
            +setTitle(String): void
            +setAccesskey(String): void
            +doWikiStartTag(): int
        }

        class CheckLockInfo [[CheckLockInfo.html]] {
            +getVariableInfo(TagData): VariableInfo[]
        }

        class PageDateTag [[PageDateTag.html]] {
            {static} +DEFAULT_FORMAT: String
            +initTag(): void
            +getFormat(): String
            +setFormat(String): void
            +doWikiStartTag(): int
        }

        class PageVersionTag [[PageVersionTag.html]] {
            +doWikiStartTag(): int
        }

        class AttachmentsIteratorTag [[AttachmentsIteratorTag.html]] {
            +doStartTag(): int
            +doAfterBody(): int
        }

        class PluginTag [[PluginTag.html]] {
            +release(): void
            +setPlugin(String): void
            +setArgs(String): void
            +doWikiStartTag(): int
            +doEndTag(): int
            +doAfterBody(): int
        }

        class UploadLinkTag [[UploadLinkTag.html]] {
            +doWikiStartTag(): int
        }

        class PageSizeTag [[PageSizeTag.html]] {
            +doWikiStartTag(): int
        }

        class CheckRequestContextTag [[CheckRequestContextTag.html]] {
            +initTag(): void
            +getContext(): String
            +setContext(String): void
            +doWikiStartTag(): int
        }

        class PageExistsTag [[PageExistsTag.html]] {
            +doWikiStartTag(): int
        }

        class CheckLockTag [[CheckLockTag.html]] {
            +initTag(): void
            +setMode(String): void
            +doWikiStartTag(): int
        }

        class PreviousVersionTag [[PreviousVersionTag.html]] {
            +doWikiStartTag(): int
        }

        class HistoryIteratorTag [[HistoryIteratorTag.html]] {
            +doStartTag(): int
            +doAfterBody(): int
        }

        class PageTypeTag [[PageTypeTag.html]] {
            +initTag(): void
            +setType(String): void
            +doWikiStartTag(): int
        }

        class LinkToParentTag [[LinkToParentTag.html]] {
            +doWikiStartTag(): int
        }

        class RequestResourceTag [[RequestResourceTag.html]] {
            +initTag(): void
            +doWikiStartTag(): int
            +getResource(): String
            +setResource(String): void
            +getType(): String
            +setType(String): void
        }

        class EditorIteratorTag [[EditorIteratorTag.html]] {
            +doStartTag(): int
        }

        class LinkToTag [[LinkToTag.html]] {
            +m_title: String
            +m_accesskey: String
            +initTag(): void
            +getVersion(): String
            +setVersion(String): void
            +setTitle(String): void
            +setAccesskey(String): void
            +doWikiStartTag(): int
        }

        WikiTagBase <|-- IncludeResourcesTag

        WikiLinkTag <|-- LinkTag

        ParamHandler <|.. LinkTag

        interface javax.servlet.jsp.tagext.BodyTag {
            {abstract} +setBodyContent(BodyContent): void
            {abstract} +doInitBody(): void
        }
        javax.servlet.jsp.tagext.BodyTag <|.. LinkTag

        WikiLinkTag <|-- CommentLinkTag

        abstract class javax.servlet.jsp.tagext.TagExtraInfo
        javax.servlet.jsp.tagext.TagExtraInfo <|-- HistoryIteratorInfo

        WikiTagBase <|-- ParentPageNameTag

        WikiTagBase <|-- WikiLinkTag

        WikiTagBase <|-- ContentTag

        WikiTagBase <|-- NoSuchPageTag

        WikiTagBase <|-- AuthorTag

        WikiTagBase <|-- CheckVersionTag

        javax.servlet.jsp.tagext.TagExtraInfo <|-- SearchResultIteratorInfo

        IteratorTag <|-- SearchResultIteratorTag

        WikiTagBase <|-- FeedDiscoveryTag

        WikiTagBase <|-- CalendarTag

        WikiLinkTag <|-- PageInfoLinkTag

        WikiTagBase <|-- TemplateDirTag

        WikiTagBase <|-- UserProfileTag

        IteratorTag <|-- AdminBeanIteratorTag

        WikiTagBase <|-- SetPaginationTag

        WikiTagBase <|-- ContentEncodingTag

        WikiTagBase <|-- TabTag

        javax.servlet.jsp.tagext.TagExtraInfo <|-- AttachmentsIteratorInfo

        WikiTagBase <|-- IncludeTag

        WikiTagBase <|-- PermissionTag

        javax.servlet.jsp.tagext.TagExtraInfo <|-- EditorIteratorInfo

        WikiTagBase <|-- SearchResultsTag

        WikiTagBase <|-- RSSImageLinkTag

        class javax.servlet.jsp.tagext.BodyTagSupport
        javax.servlet.jsp.tagext.BodyTagSupport <|-- WikiBodyTag

        interface javax.servlet.jsp.tagext.TryCatchFinally {
            {abstract} +doCatch(Throwable): void
            {abstract} +doFinally(): void
        }
        javax.servlet.jsp.tagext.TryCatchFinally <|.. WikiBodyTag

        javax.servlet.jsp.tagext.BodyTagSupport <|-- IteratorTag

        javax.servlet.jsp.tagext.TryCatchFinally <|.. IteratorTag

        WikiTagBase <|-- UserNameTag

        WikiBodyTag <|-- EditorTag

        class javax.servlet.jsp.tagext.TagSupport
        javax.servlet.jsp.tagext.TagSupport <|-- WikiTagBase

        javax.servlet.jsp.tagext.TryCatchFinally <|.. WikiTagBase

        WikiTagBase <|-- SearchResultsSizeTag

        WikiTagBase <|-- HasAttachmentsTag

        javax.servlet.jsp.tagext.TagSupport <|-- CookieTag

        WikiTagBase <|-- IfNoSearchResultsTag

        WikiTagBase <|-- BaseURLTag

        WikiTagBase <|-- PageNameTag

        javax.servlet.jsp.tagext.TagExtraInfo <|-- AdminBeanIteratorInfo

        WikiTagBase <|-- InsertDiffTag

        WikiTagBase <|-- VariableTag

        javax.servlet.jsp.tagext.BodyTagSupport <|-- TabbedSectionTag

        javax.servlet.jsp.tagext.BodyTagSupport <|-- TranslateTag

        WikiTagBase <|-- NextVersionTag

        WikiTagBase <|-- InsertPageTag

        WikiTagBase <|-- MessagesTag

        WikiLinkTag <|-- DiffLinkTag

        javax.servlet.jsp.tagext.BodyTagSupport <|-- ParamTag

        WikiTagBase <|-- BreadcrumbsTag

        class java.util.LinkedList<E>
        java.util.LinkedList <|-- org.apache.wiki.tags.BreadcrumbsTag.FixedQueue

        interface java.io.Serializable
        java.io.Serializable <|.. org.apache.wiki.tags.BreadcrumbsTag.FixedQueue

        BreadcrumbsTag +-- org.apache.wiki.tags.BreadcrumbsTag.FixedQueue

        WikiTagBase <|-- UserCheckTag

        WikiLinkTag <|-- EditLinkTag

        javax.servlet.jsp.tagext.TagExtraInfo <|-- CheckLockInfo

        WikiTagBase <|-- PageDateTag

        WikiTagBase <|-- PageVersionTag

        IteratorTag <|-- AttachmentsIteratorTag

        WikiBodyTag <|-- PluginTag

        WikiLinkTag <|-- UploadLinkTag

        WikiTagBase <|-- PageSizeTag

        WikiTagBase <|-- CheckRequestContextTag

        NoSuchPageTag <|-- PageExistsTag

        WikiTagBase <|-- CheckLockTag

        WikiTagBase <|-- PreviousVersionTag

        IteratorTag <|-- HistoryIteratorTag

        WikiTagBase <|-- PageTypeTag

        LinkToTag <|-- LinkToParentTag

        WikiTagBase <|-- RequestResourceTag

        IteratorTag <|-- EditorIteratorTag

        WikiLinkTag <|-- LinkToTag

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
