@startuml

    class SetPaginationTag [[SetPaginationTag.html]] {
        +initTag(): void
        +setStart(int): void
        +setTotal(int): void
        +setPagesize(int): void
        +setMaxlinks(int): void
        +setFmtkey(String): void
        +setHref(String): void
        +setOnclick(String): void
        +doWikiStartTag(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
