@startuml

    abstract class WikiTagBase [[WikiTagBase.html]] {
        #m_wikiContext: Context
        +setPageContext(PageContext): void
        +initTag(): void
        +doStartTag(): int
        +doEndTag(): int
        +doCatch(Throwable): void
        +doFinally(): void
        +setId(String): void
        {abstract} +doWikiStartTag(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
