@startuml

    class DefaultUserProfile [[DefaultUserProfile.html]] {
        +getCreated(): Date
        +getEmail(): String
        +getFullname(): String
        +getLastModified(): Date
        +getLoginName(): String
        +getPassword(): String
        +getWikiName(): String
        +isNew(): boolean
        +setCreated(Date): void
        +setEmail(String): void
        +setFullname(String): void
        +setLastModified(Date): void
        +setLoginName(String): void
        +setPassword(String): void
        +getAttributes(): Map<String, Serializable>
        +getLockExpiry(): Date
        +getUid(): String
        +isLocked(): boolean
        +setLockExpiry(Date): void
        +setUid(String): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
