@startuml

    interface UserDatabase [[UserDatabase.html]] {
        {abstract} +deleteByLoginName(String): void
        {abstract} +getPrincipals(String): Principal[]
        {abstract} +getWikiNames(): Principal[]
        {abstract} +find(String): UserProfile
        {abstract} +findByEmail(String): UserProfile
        {abstract} +findByLoginName(String): UserProfile
        {abstract} +findByUid(String): UserProfile
        {abstract} +findByWikiName(String): UserProfile
        {abstract} +findByFullName(String): UserProfile
        {abstract} +initialize(Engine, Properties): void
        {abstract} +newProfile(): UserProfile
        {abstract} +rename(String, String): void
        {abstract} +save(UserProfile): void
        {abstract} +validatePassword(String, String): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
