@startuml

    class SystemPrincipal [[SystemPrincipal.html]] {
        {static} +SYSTEM_USER: Principal
        +getName(): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
