@startuml

    abstract class Task [[Task.html]] {
        +Task(String)
        +Task(Workflow, String)
        +getActor(): Principal
        +setSuccessor(Step): void
        +getSuccessor(): Step
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
