@startuml

    namespace org.apache.wiki.markdown.nodes {

        class JSPWikiLink [[JSPWikiLink.html]] {
            +JSPWikiLink(Link)
            +toStringAttributes(): String
            +getWikiLink(): String
            +hasRef(): boolean
        }

        class com.vladsch.flexmark.ast.Link
        com.vladsch.flexmark.ast.Link <|-- JSPWikiLink

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
