@startuml

    namespace org.apache.wiki.api.search {

        interface SearchResult [[SearchResult.html]] {
            {abstract} +getPage(): Page
            {abstract} +getScore(): int
            {abstract} +getContexts(): String[]
        }

        class QueryItem [[QueryItem.html]] {
            {static} +REQUIRED: int
            {static} +FORBIDDEN: int
            {static} +REQUESTED: int
            +word: String
            +type: int
        }

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
