@startuml

    class CryptoUtil [[CryptoUtil.html]] {
        {static} +main(String[]): void
        {static} +getSaltedPassword(byte[]): String
        {static} #getSaltedPassword(byte[], byte[]): String
        {static} +verifySaltedPassword(byte[], String): boolean
        {static} #extractPasswordHash(byte[]): byte[]
        {static} #extractSalt(byte[]): byte[]
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
