@startuml

    class PropertyReader [[PropertyReader.html]] {
        {static} +DEFAULT_JSPWIKI_CONFIG: String
        {static} +PARAM_CUSTOMCONFIG: String
        {static} +PARAM_CUSTOMCONFIG_CASCADEPREFIX: String
        {static} +CUSTOM_JSPWIKI_CONFIG: String
        {static} +loadWebAppProps(ServletContext): Properties
        {static} +getDefaultProperties(): Properties
        {static} +getCombinedProperties(String): Properties
        {static} +expandVars(Properties): void
        {static} +locateClassPathResource(ServletContext, String): InputStream
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
