@startuml

    namespace org.apache.wiki.bootstrap {

        class WikiBootstrapServletContextListener [[WikiBootstrapServletContextListener.html]] {
            +contextInitialized(ServletContextEvent): void
            +contextDestroyed(ServletContextEvent): void
        }

        interface javax.servlet.ServletContextListener {
            {abstract} +contextInitialized(ServletContextEvent): void
            {abstract} +contextDestroyed(ServletContextEvent): void
        }
        javax.servlet.ServletContextListener <|.. WikiBootstrapServletContextListener

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
