@startuml

    namespace org.apache.wiki.util.comparators {

        class JavaNaturalComparator [[JavaNaturalComparator.html]] {
            {static} +DEFAULT_JAVA_COMPARATOR: Comparator<String>
            +compare(String, String): int
        }

        class HumanComparator [[HumanComparator.html]] {
            {static} +DEFAULT_HUMAN_COMPARATOR: Comparator<String>
            +HumanComparator()
            +HumanComparator(HumanComparator.CharType[])
            {static} +getInstance(): Comparator<String>
            +compare(String, String): int
        }

        enum org.apache.wiki.util.comparators.HumanComparator.CharType [[HumanComparator.CharType.html]] {
            {static} +TYPE_OTHER
            {static} +TYPE_DIGIT
            {static} +TYPE_LETTER
        }

        class PrincipalComparator [[PrincipalComparator.html]] {
            +compare(Principal, Principal): int
        }

        class LocaleComparator [[LocaleComparator.html]] {
            +LocaleComparator()
            +LocaleComparator(Locale)
            +setLocale(Locale): void
        }

        class CollatorComparator [[CollatorComparator.html]] {
            {static} +DEFAULT_LOCALE_COMPARATOR: Comparator<String>
            #m_collator: Collator
            +CollatorComparator()
            +CollatorComparator(Collator)
            +compare(String, String): int
            +setCollator(Collator): void
        }

        interface java.util.Comparator<T> {
            {abstract} +compare(T, T): int
        }
        java.util.Comparator <|.. JavaNaturalComparator

        java.util.Comparator <|.. HumanComparator

        HumanComparator +-- org.apache.wiki.util.comparators.HumanComparator.CharType

        java.util.Comparator <|.. PrincipalComparator

        interface java.io.Serializable
        java.io.Serializable <|.. PrincipalComparator

        CollatorComparator <|-- LocaleComparator

        java.util.Comparator <|.. CollatorComparator

        HumanComparator --> "*" org.apache.wiki.util.comparators.HumanComparator.CharType: sortOrder

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
