@startuml

    class Group [[Group.html]] {
        #Group(String, String)
        +add(Principal): boolean
        +clear(): void
        +getCreated(): Date
        +getCreator(): String
        +getLastModified(): Date
        +getModifier(): String
        +getName(): String
        +getPrincipal(): Principal
        +getWiki(): String
        +isMember(Principal): boolean
        +members(): Principal[]
        +remove(Principal): boolean
        +setCreated(Date): void
        +setCreator(String): void
        +setLastModified(Date): void
        +setModifier(String): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
