@startuml

    class GroupManager [[GroupManager.html]] {
        {static} +MESSAGES_KEY: String
        #m_engine: WikiEngine
        #m_groupListener: WikiEventListener
        +findRole(String): Principal
        +getGroup(String): Group
        +getGroupDatabase(): GroupDatabase
        +getRoles(): Principal[]
        +initialize(WikiEngine, Properties): void
        +isUserInRole(WikiSession, Principal): boolean
        +parseGroup(String, String, boolean): Group
        +parseGroup(WikiContext, boolean): Group
        +removeGroup(String): void
        +setGroup(WikiSession, Group): void
        +validateGroup(WikiContext, Group): void
        #extractMembers(String): String[]
        #checkGroupName(WikiContext, String): void
        +addWikiEventListener(WikiEventListener): void
        +removeWikiEventListener(WikiEventListener): void
        #fireEvent(int, Object): void
        +actionPerformed(WikiEvent): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
