@startuml

    interface GroupManager [[GroupManager.html]] {
        {static} +MESSAGES_KEY: String
        {static} +PROP_GROUPDATABASE: String
        +parseGroup(WikiContext, boolean): Group
        +validateGroup(WikiContext, Group): void
        +checkGroupName(WikiContext, String): void
        +fireEvent(int, Object): void
        {abstract} +getGroup(String): Group
        {abstract} +getGroupDatabase(): GroupDatabase
        {abstract} +parseGroup(String, String, boolean): Group
        {abstract} +removeGroup(String): void
        {abstract} +setGroup(Session, Group): void
        {abstract} +addWikiEventListener(WikiEventListener): void
        {abstract} +removeWikiEventListener(WikiEventListener): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
