@startuml

    class XMLGroupDatabase [[XMLGroupDatabase.html]] {
        {static} #log: Logger
        {static} +PROP_DATABASE: String
        +delete(Group): void
        +groups(): Group[]
        +initialize(WikiEngine, Properties): void
        +save(Group, Principal): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
