@startuml

    class HtmlStringToWikiTranslator [[HtmlStringToWikiTranslator.html]] {
        +translate(String): String
        +translate(String, Context): String
        +translate(String, XHtmlToWikiConfig): String
        {static} +element2String(Element): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
