@startuml

    namespace org.apache.wiki.htmltowiki {

        class WhitespaceTrimWriter [[WhitespaceTrimWriter.html]] {
            +flush(): void
            +isWhitespaceTrimMode(): boolean
            +setWhitespaceTrimMode(boolean): void
            +write(char[], int, int): void
            +close(): void
            +isCurrentlyOnLineBegin(): boolean
        }

        class XHtmlElementToWikiTranslator [[XHtmlElementToWikiTranslator.html]] {
            +XHtmlElementToWikiTranslator(Element)
            +XHtmlElementToWikiTranslator(Element, XHtmlToWikiConfig)
            +getWikiString(): String
        }

        class HtmlStringToWikiTranslator [[HtmlStringToWikiTranslator.html]] {
            +translate(String): String
            +translate(String, WikiContext): String
            +translate(String, XHtmlToWikiConfig): String
            {static} +element2String(Element): String
        }

        class XHtmlToWikiConfig [[XHtmlToWikiConfig.html]] {
            +XHtmlToWikiConfig()
            +XHtmlToWikiConfig(WikiContext)
            +getAttachPage(): String
            +setAttachPage(String): void
            +getOutlink(): String
            +setOutlink(String): void
            +getPageInfoJsp(): String
            +setPageInfoJsp(String): void
            +getPageName(): String
            +setPageName(String): void
            +getWikiJspPage(): String
            +setWikiJspPage(String): void
            +getEditJspPage(): String
            +setEditJspPage(String): void
        }

        class PersistentMapDecorator [[PersistentMapDecorator.html]] {
            +PersistentMapDecorator(Map<Object, Object>)
            +clear(): void
            +containsKey(Object): boolean
            +containsValue(Object): boolean
            +entrySet(): Set<Map.Entry<Object, Object>>
            +equals(Object): boolean
            +get(Object): Object
            +hashCode(): int
            +isEmpty(): boolean
            +keySet(): Set<Object>
            +put(Object, Object): Object
            +putAll(Map<?, ?>): void
            +remove(Object): Object
            +size(): int
            +toString(): String
            +values(): Collection<Object>
        }

        class ForgetNullValuesLinkedHashMap<K, V> [[ForgetNullValuesLinkedHashMap.html]] {
            +put(K, V): V
        }

        abstract class java.io.Writer {
            {abstract} +write(char[], int, int): void
            {abstract} +flush(): void
            {abstract} +close(): void
        }
        java.io.Writer <|-- WhitespaceTrimWriter

        class java.util.Properties
        java.util.Properties <|-- PersistentMapDecorator

        class java.util.LinkedHashMap<K, V>
        java.util.LinkedHashMap <|-- ForgetNullValuesLinkedHashMap

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
