@startuml

    class ClassUtil [[ClassUtil.html]] {
        {static} +MAPPINGS: String
        {static} +MAPPINGS_EXTRA: String
        {static} +findClass(List<String>, List<String>, String): Class<?>
        {static} +findClass(String, String): Class<?>
        {static} +classpathEntriesUnder(String): List<String>
        {static} +getMappedObject(String): T
        {static} +getMappedObject(String, Object[]): T
        {static} +getMappedClass(String): Class<?>
        {static} +assignable(String, String): boolean
        {static} +getExtraClassMappings(): Map<String, String>
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
