@startuml

    class TextUtil [[TextUtil.html]] {
        {static} +PASSWORD_LENGTH: int
        {static} +LEGACY_CHARS_ALLOWED: String
        {static} +PUNCTUATION_CHARS_ALLOWED: String
        {static} #urlEncode(byte[]): String
        {static} #urlDecode(byte[], String): String
        {static} +urlEncodeUTF8(String): String
        {static} +urlDecodeUTF8(String): String
        {static} +urlEncode(String, String): String
        {static} +urlDecode(String, String): String
        {static} +replaceEntities(String): String
        {static} +replaceString(String, String, String): String
        {static} +replaceString(String, int, int, String): String
        {static} +replaceStringCaseUnsensitive(String, String, String): String
        {static} +parseIntParameter(String, int): int
        {static} +getIntegerProperty(Properties, String, int): int
        {static} +getBooleanProperty(Properties, String, boolean): boolean
        {static} +getStringProperty(Properties, String, String): String
        {static} +getRequiredProperty(Properties, String): String
        {static} +getCanonicalFilePathProperty(Properties, String, String): String
        {static} +isPositive(String): boolean
        {static} +normalizePostData(String): String
        {static} +beautifyString(String): String
        {static} +beautifyString(String, String): String
        {static} +cleanString(String, String): String
        {static} +createProperties(String[]): Properties
        {static} +countSections(String): int
        {static} +getSection(String, int): String
        {static} +repeatString(String, int): String
        {static} +native2Ascii(String): String
        {static} +toHexString(byte[]): String
        {static} +isNumber(String): boolean
        {static} +generateRandomPassword(): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
