@startuml

    class XhtmlUtil [[XhtmlUtil.html]] {
        {static} +EXPAND_EMPTY_NODES: Format
        {static} +serialize(Element): String
        {static} +serialize(Element, boolean): String
        {static} +serialize(Element, Format): String
        {static} +element(XHTML): Element
        {static} +element(XHTML, String): Element
        {static} +link(String, String): Element
        {static} +target(String, String): Element
        {static} +img(String, String): Element
        {static} +input(String, String, String): Element
        {static} +setClass(Element, String): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
