@startuml

    enum XHTML [[XHTML.html]] {
        {static} +a
        {static} +abbr
        {static} +acronym
        {static} +address
        {static} +applet
        {static} +area
        {static} +b
        {static} +base
        {static} +basefont
        {static} +bdo
        {static} +big
        {static} +blockquote
        {static} +body
        {static} +br
        {static} +button
        {static} +caption
        {static} +center
        {static} +cite
        {static} +code
        {static} +col
        {static} +colgroup
        {static} +dd
        {static} +del
        {static} +dfn
        {static} +dir
        {static} +div
        {static} +dl
        {static} +dt
        {static} +em
        {static} +fieldset
        {static} +font
        {static} +form
        {static} +frame
        {static} +frameset
        {static} +h1
        {static} +h2
        {static} +h3
        {static} +h4
        {static} +h5
        {static} +h6
        {static} +head
        {static} +hr
        {static} +html
        {static} +i
        {static} +iframe
        {static} +img
        {static} +input
        {static} +ins
        {static} +isindex
        {static} +kbd
        {static} +label
        {static} +legend
        {static} +li
        {static} +link
        {static} +map
        {static} +menu
        {static} +meta
        {static} +noframes
        {static} +noscript
        {static} +object
        {static} +ol
        {static} +optgroup
        {static} +option
        {static} +p
        {static} +param
        {static} +pre
        {static} +q
        {static} +s
        {static} +samp
        {static} +script
        {static} +select
        {static} +small
        {static} +span
        {static} +strike
        {static} +strong
        {static} +style
        {static} +sub
        {static} +sup
        {static} +table
        {static} +tbody
        {static} +td
        {static} +textarea
        {static} +tfoot
        {static} +th
        {static} +thead
        {static} +title
        {static} +tr
        {static} +tt
        {static} +u
        {static} +ul
        {static} +var
        {static} +XMLNS_xhtml: String
        {static} +STRICT_DTD_PubId: String
        {static} +STRICT_DTD_SysId: String
        {static} +TRANSITIONAL_DTD_PubId: String
        {static} +TRANSITIONAL_DTD_SysId: String
        {static} +FRAMESET_DTD_PubId: String
        {static} +FRAMESET_DTD_SysId: String
        {static} +CSS_style: String
        {static} +ATTR_id: String
        {static} +ATTR_class: String
        {static} +ATTR_name: String
        {static} +ATTR_type: String
        {static} +ATTR_value: String
        {static} +ATTR_href: String
        {static} +ATTR_title: String
        {static} +ATTR_width: String
        {static} +ATTR_height: String
        {static} +ATTR_border: String
        {static} +ATTR_colspan: String
        {static} +ATTR_src: String
        {static} +ATTR_alt: String
        {static} +ATTR_bgcolor: String
        {static} +ATTR_checked: String
        {static} +ATTR_cols: String
        {static} +ATTR_content: String
        {static} +ATTR_httpEquiv: String
        {static} +ATTR_scheme: String
        {static} +ATTR_rel: String
        {static} +ATTR_rows: String
        {static} +ATTR_selected: String
        {static} +ATTR_size: String
        {static} +ATTR_style: String
        {static} +ATTR_align: String
        {static} +ATTR_cellpadding: String
        {static} +ATTR_cellspacing: String
        +getName(): String
        {static} +getNamedCharacterEntity(int): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
