@startuml

    class RPCHandlerUTF8 [[RPCHandlerUTF8.html]] {
        +getApplicationName(): String
        +getAllPages(): Vector
        #encodeWikiPage(WikiPage): Hashtable<String, Object>
        +getRecentChanges(Date): Vector
        +getPageInfo(String): Hashtable
        +getPageInfoVersion(String, int): Hashtable
        +getPage(String): String
        +getPageVersion(String, int): String
        +getPageHTML(String): String
        +getPageHTMLVersion(String, int): String
        +listLinks(String): Vector
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
