@startuml

    abstract class AbstractFileProvider [[AbstractFileProvider.html]] {
        {static} +PROP_CUSTOMPROP_MAXLIMIT: String
        {static} +PROP_CUSTOMPROP_MAXKEYLENGTH: String
        {static} +PROP_CUSTOMPROP_MAXVALUELENGTH: String
        {static} +DEFAULT_MAX_PROPLIMIT: int
        {static} +DEFAULT_MAX_PROPKEYLENGTH: int
        {static} +DEFAULT_MAX_PROPVALUELENGTH: int
        {static} +MAX_PROPLIMIT: int
        {static} +MAX_PROPKEYLENGTH: int
        {static} +MAX_PROPVALUELENGTH: int
        {static} +PROP_PAGEDIR: String
        {static} +FILE_EXT: String
        {static} +DEFAULT_ENCODING: String
        #m_encoding: String
        #m_engine: WikiEngine
        +initialize(WikiEngine, Properties): void
        #mangleName(String): String
        #unmangleName(String): String
        #findPage(String): File
        +pageExists(String): boolean
        +pageExists(String, int): boolean
        +getPageText(String, int): String
        +putPageText(WikiPage, String): void
        +getAllPages(): Collection<WikiPage>
        +getAllChangedSince(Date): Collection<WikiPage>
        +getPageCount(): int
        +findPages(QueryItem[]): Collection<SearchResult>
        +getPageInfo(String, int): WikiPage
        +getVersionHistory(String): List<WikiPage>
        +getProviderInfo(): String
        +deleteVersion(String, int): void
        +deletePage(String): void
        #setCustomProperties(WikiPage, Properties): void
        #getCustomProperties(WikiPage, Properties): void
        #addCustomProperties(WikiPage, Properties): Properties
        #validateCustomPageProperties(Properties): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
