@startuml

    class BasicAttachmentProvider [[BasicAttachmentProvider.html]] {
        {static} +PROP_STORAGEDIR: String
        {static} +PROP_DISABLECACHE: String
        {static} +PROPERTY_FILE: String
        {static} +DIR_EXTENSION: String
        {static} +ATTDIR_EXTENSION: String
        +initialize(Engine, Properties): void
        {static} #getFileExtension(String): String
        +putAttachmentData(Attachment, InputStream): void
        +getProviderInfo(): String
        +getAttachmentData(Attachment): InputStream
        +listAttachments(WikiPage): List<Attachment>
        +findAttachments(QueryItem[]): Collection<Attachment>
        +listAllChanged(Date): List<Attachment>
        +getAttachmentInfo(WikiPage, String, int): Attachment
        +getVersionHistory(Attachment): List<Attachment>
        +deleteVersion(Attachment): void
        +deleteAttachment(Attachment): void
        +moveAttachmentsForPage(String, String): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
