@startuml

    class CachingProvider [[CachingProvider.html]] {
        {static} +CACHE_NAME: String
        {static} +TEXTCACHE_NAME: String
        {static} +HISTORYCACHE_NAME: String
        {static} +DEFAULT_CACHECAPACITY: int
        {static} +DEFAULT_CACHETIMETOLIVESECONDS: int
        {static} +DEFAULT_CACHETIMETOIDLESECONDS: int
        +initialize(Engine, Properties): void
        +pageExists(String, int): boolean
        +pageExists(String): boolean
        +getPageText(String, int): String
        +putPageText(Page, String): void
        +getAllPages(): Collection<Page>
        +getAllChangedSince(Date): Collection<Page>
        +getPageCount(): int
        +findPages(QueryItem[]): Collection<SearchResult>
        +getPageInfo(String, int): Page
        +getVersionHistory(String): List<Page>
        +getProviderInfo(): String
        +deleteVersion(String, int): void
        +deletePage(String): void
        +movePage(String, String): void
        +getRealProvider(): PageProvider
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
