@startuml

    class VersioningFileProvider [[VersioningFileProvider.html]] {
        {static} +PAGEDIR: String
        {static} +PROPERTYFILE: String
        +initialize(WikiEngine, Properties): void
        +getPageText(String, int): String
        +putPageText(WikiPage, String): void
        +getPageInfo(String, int): WikiPage
        +pageExists(String, int): boolean
        +getVersionHistory(String): List<WikiPage>
        +deletePage(String): void
        +deleteVersion(String, int): void
        +getAllPages(): Collection<WikiPage>
        +getProviderInfo(): String
        +movePage(String, String): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
