@startuml

    interface WikiAttachmentProvider <<deprecated>> [[WikiAttachmentProvider.html]] {
        {abstract} + --putAttachmentData-- (Attachment, InputStream): void
        {abstract} + --getAttachmentData-- (Attachment): InputStream
        {abstract} + --listAttachments-- (WikiPage): List<Attachment>
        {abstract} + --findAttachments-- (QueryItem[]): Collection<Attachment>
        {abstract} + --listAllChanged-- (Date): List<Attachment>
        {abstract} + --getAttachmentInfo-- (WikiPage, String, int): Attachment
        {abstract} + --getVersionHistory-- (Attachment): List<Attachment>
        {abstract} + --deleteVersion-- (Attachment): void
        {abstract} + --deleteAttachment-- (Attachment): void
        {abstract} + --moveAttachmentsForPage-- (String, String): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
