@startuml

    class WikiAttachmentAdapterProvider <<deprecated>> [[WikiAttachmentAdapterProvider.html]] {
        + --initialize-- (Engine, Properties): void
        + --getProviderInfo-- (): String
        + --putAttachmentData-- (Attachment, InputStream): void
        + --getAttachmentData-- (Attachment): InputStream
        + --listAttachments-- (Page): List<Attachment>
        + --findAttachments-- (QueryItem[]): Collection<Attachment>
        + --listAllChanged-- (Date): List<Attachment>
        + --getAttachmentInfo-- (Page, String, int): Attachment
        + --getVersionHistory-- (Attachment): List<Attachment>
        + --deleteVersion-- (Attachment): void
        + --deleteAttachment-- (Attachment): void
        + --moveAttachmentsForPage-- (String, String): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
