@startuml

    interface Command [[Command.html]] {
        {abstract} +targetedCommand(Object): Command
        {abstract} +getContentTemplate(): String
        {abstract} +getJSP(): String
        {abstract} +getName(): String
        {abstract} +getRequestContext(): String
        {abstract} +requiredPermission(): Permission
        {abstract} +getTarget(): Object
        {abstract} +getURLPattern(): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
