@startuml

    interface Context [[Context.html]] {
        {static} +ATTR_CONTEXT: String
        {static} +VAR_EXECUTE_PLUGINS: String
        {static} +VAR_WYSIWYG_EDITOR_MODE: String
        +getURL(String, String): String
        +getURL(String, String, String): String
        {abstract} +getPage(): Page
        {abstract} +setPage(Page): void
        {abstract} +getRealPage(): Page
        {abstract} +setRealPage(Page): Page
        {abstract} +getEngine(): Engine
        {abstract} +setRequestContext(String): void
        {abstract} +getVariable(String): T
        {abstract} +setVariable(String, Object): void
        {abstract} +getBooleanWikiProperty(String, boolean): boolean
        {abstract} +getHttpParameter(String): String
        {abstract} +getHttpRequest(): HttpServletRequest
        {abstract} +setTemplate(String): void
        {abstract} +getTemplate(): String
        {abstract} +getWikiSession(): Session
        {abstract} +getCurrentUser(): Principal
        {abstract} +hasAdminPermissions(): boolean
        {abstract} +getViewURL(String): String
        {abstract} +getRedirectURL(): String
        {abstract} +getCommand(): Command
        {abstract} +clone(): Context
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
