@startuml

    interface Engine [[Engine.html]] {
        {static} +DEFAULT_INLINEPATTERN: String
        {static} +DEFAULT_TEMPLATE_NAME: String
        {static} +PROP_APPNAME: String
        {static} +PROP_INLINEIMAGEPTRN: String
        {static} +PROP_INTERWIKIREF: String
        {static} +PROP_STOREUSERNAME: String
        {static} +PROP_ENCODING: String
        {static} +PROP_NO_FILTER_ENCODING: String
        {static} +PROP_WORKDIR: String
        {static} +PREFS_COOKIE_NAME: String
        {static} +PROP_MATCHPLURALS: String
        {static} +PROP_TEMPLATEDIR: String
        {static} +PROP_FRONTPAGE: String
        {static} +PROP_URLCONSTRUCTOR: String
        {static} +PROP_ACL_MANAGER_IMPL: String
        {static} +PROP_ALLOW_CREATION_OF_EMPTY_PAGES: String
        +adapt(Class<E>): E
        +findConfigFile(String): URL
        {abstract} +getManager(Class<T>): T
        {abstract} +isConfigured(): boolean
        {abstract} +getWikiProperties(): Properties
        {abstract} +getWorkDir(): String
        {abstract} +getTemplateDir(): String
        {abstract} +getStartTime(): Date
        {abstract} +getBaseURL(): String
        {abstract} +getGlobalRSSURL(): String
        {abstract} +getInterWikiURL(String): String
        {abstract} +getURL(String, String, String): String
        {abstract} +getFrontPage(): String
        {abstract} +getServletContext(): ServletContext
        {abstract} +getAllInterWikiLinks(): Collection<String>
        {abstract} +getAllInlinedImagePatterns(): Collection<String>
        {abstract} +getSpecialPageReference(String): String
        {abstract} +getApplicationName(): String
        {abstract} +getRootPath(): String
        {abstract} +getFinalPageName(String): String
        {abstract} +encodeName(String): String
        {abstract} +decodeName(String): String
        {abstract} +getContentEncoding(): Charset
        {abstract} +addWikiEventListener(WikiEventListener): void
        {abstract} +removeWikiEventListener(WikiEventListener): void
        {abstract} +setAttribute(String, Object): void
        {abstract} +getAttribute(String): T
        {abstract} +removeAttribute(String): T
        {abstract} +shutdown(): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
