@startuml

    namespace org.apache.wiki.api.core {

        interface Command [[Command.html]] {
            {abstract} +targetedCommand(Object): Command
            {abstract} +getContentTemplate(): String
            {abstract} +getJSP(): String
            {abstract} +getName(): String
            {abstract} +getRequestContext(): String
            {abstract} +requiredPermission(): Permission
            {abstract} +getTarget(): Object
            {abstract} +getURLPattern(): String
        }

        interface Attachment [[Attachment.html]] {
            {abstract} +getFileName(): String
            {abstract} +setFileName(String): void
            {abstract} +getParentName(): String
            {abstract} +isCacheable(): boolean
            {abstract} +setCacheable(boolean): void
        }

        interface Page [[Page.html]] {
            {static} +DESCRIPTION: String
            {static} +ALIAS: String
            {static} +REDIRECT: String
            {static} +AUTHOR: String
            {static} +CHANGENOTE: String
            {static} +VIEWCOUNT: String
            {abstract} +getName(): String
            {abstract} +getLastModified(): Date
            {abstract} +setLastModified(Date): void
            {abstract} +setVersion(int): void
            {abstract} +getVersion(): int
            {abstract} +getSize(): long
            {abstract} +setSize(long): void
            {abstract} +setAuthor(String): void
            {abstract} +getAuthor(): String
            {abstract} +getWiki(): String
            {abstract} +invalidateMetadata(): void
            {abstract} +hasMetadata(): boolean
            {abstract} +setHasMetadata(): void
            {abstract} +getAttribute(String): T
            {abstract} +setAttribute(String, Object): void
            {abstract} +removeAttribute(String): T
            {abstract} +getAttributes(): Map<String, Object>
            {abstract} +clone(): Page
        }

        enum ContextEnum [[ContextEnum.html]] {
            {static} +GROUP_DELETE
            {static} +GROUP_EDIT
            {static} +GROUP_VIEW
            {static} +PAGE_ATTACH
            {static} +PAGE_COMMENT
            {static} +PAGE_CONFLICT
            {static} +PAGE_DELETE
            {static} +PAGE_DIFF
            {static} +PAGE_EDIT
            {static} +PAGE_INFO
            {static} +PAGE_NONE
            {static} +PAGE_PREVIEW
            {static} +PAGE_RENAME
            {static} +PAGE_RSS
            {static} +PAGE_UPLOAD
            {static} +PAGE_VIEW
            {static} +REDIRECT
            {static} +WIKI_ADMIN
            {static} +WIKI_CREATE_GROUP
            {static} +WIKI_ERROR
            {static} +WIKI_FIND
            {static} +WIKI_INSTALL
            {static} +WIKI_LOGIN
            {static} +WIKI_LOGOUT
            {static} +WIKI_MESSAGE
            {static} +WIKI_PREFS
            {static} +WIKI_WORKFLOW
            +getContentTemplate(): String
            +getRequestContext(): String
            +getUrlPattern(): String
        }

        interface AclEntry [[AclEntry.html]] {
            {abstract} +addPermission(Permission): boolean
            {abstract} +checkPermission(Permission): boolean
            {abstract} +getPrincipal(): Principal
            {abstract} +permissions(): Enumeration<Permission>
            {abstract} +removePermission(Permission): boolean
            {abstract} +setPrincipal(Principal): boolean
        }

        interface Acl [[Acl.html]] {
            {abstract} +addEntry(AclEntry): boolean
            {abstract} +aclEntries(): Enumeration<AclEntry>
            {abstract} +isEmpty(): boolean
            {abstract} +findPrincipals(Permission): Principal[]
            {abstract} +getAclEntry(Principal): AclEntry
            {abstract} +removeEntry(AclEntry): boolean
        }

        interface Context [[Context.html]] {
            {static} +ATTR_CONTEXT: String
            {static} +VAR_EXECUTE_PLUGINS: String
            {static} +VAR_WYSIWYG_EDITOR_MODE: String
            +getURL(String, String): String
            +getURL(String, String, String): String
            {static} +findContext(PageContext): Context
            {abstract} +setRequestContext(String): void
            {abstract} +getVariable(String): T
            {abstract} +setVariable(String, Object): void
            {abstract} +getBooleanWikiProperty(String, boolean): boolean
            {abstract} +getHttpParameter(String): String
            {abstract} +getHttpRequest(): HttpServletRequest
            {abstract} +setTemplate(String): void
            {abstract} +getTemplate(): String
            {abstract} +getCurrentUser(): Principal
            {abstract} +hasAdminPermissions(): boolean
            {abstract} +getViewURL(String): String
            {abstract} +getRedirectURL(): String
            {abstract} +clone(): Context
            {abstract} +deepClone(): Context
        }

        interface Engine [[Engine.html]] {
            {static} +DEFAULT_INLINEPATTERN: String
            {static} +DEFAULT_TEMPLATE_NAME: String
            {static} +PROP_APPNAME: String
            {static} +PROP_INLINEIMAGEPTRN: String
            {static} +PROP_INTERWIKIREF: String
            {static} +PROP_SEARCHPATH: String
            {static} +PROP_STOREUSERNAME: String
            {static} +PROP_ENCODING: String
            {static} +PROP_NO_FILTER_ENCODING: String
            {static} +PROP_WORKDIR: String
            {static} +PREFS_COOKIE_NAME: String
            {static} +PROP_MATCHPLURALS: String
            {static} +PROP_TEMPLATEDIR: String
            {static} +PROP_FRONTPAGE: String
            {static} +PROP_URLCONSTRUCTOR: String
            {static} +PROP_ACL_MANAGER_IMPL: String
            {static} +PROP_ALLOW_CREATION_OF_EMPTY_PAGES: String
            +adapt(Class<E>): E
            +getPluginSearchPath(): String
            +findConfigFile(String): URL
            {abstract} +getManager(Class<T>): T
            {abstract} +getManagers(Class<T>): List<T>
            {abstract} +isConfigured(): boolean
            {abstract} +getWikiProperties(): Properties
            {abstract} +getWorkDir(): String
            {abstract} +getTemplateDir(): String
            {abstract} +getStartTime(): Date
            {abstract} +getBaseURL(): String
            {abstract} +getGlobalRSSURL(): String
            {abstract} +getInterWikiURL(String): String
            {abstract} +getURL(String, String, String): String
            {abstract} +getFrontPage(): String
            {abstract} +getServletContext(): ServletContext
            {abstract} +getAllInterWikiLinks(): Collection<String>
            {abstract} +getAllInlinedImagePatterns(): Collection<String>
            {abstract} +getSpecialPageReference(String): String
            {abstract} +getApplicationName(): String
            {abstract} +getRootPath(): String
            {abstract} +getFinalPageName(String): String
            {abstract} +encodeName(String): String
            {abstract} +decodeName(String): String
            {abstract} +getContentEncoding(): Charset
            {abstract} +addWikiEventListener(WikiEventListener): void
            {abstract} +removeWikiEventListener(WikiEventListener): void
            {abstract} +setAttribute(String, Object): void
            {abstract} +getAttribute(String): T
            {abstract} +removeAttribute(String): T
            {abstract} +shutdown(): void
        }

        interface Session [[Session.html]] {
            {static} +ANONYMOUS: String
            {static} +ASSERTED: String
            {static} +AUTHENTICATED: String
            {static} +doPrivileged(Session, PrivilegedAction<?>): Object
            {abstract} +isAsserted(): boolean
            {abstract} +isAuthenticated(): boolean
            {abstract} +isAnonymous(): boolean
            {abstract} +getLoginPrincipal(): Principal
            {abstract} +getUserPrincipal(): Principal
            {abstract} +getLocale(): Locale
            {abstract} +addMessage(String): void
            {abstract} +addMessage(String, String): void
            {abstract} +clearMessages(): void
            {abstract} +clearMessages(String): void
            {abstract} +getMessages(): String[]
            {abstract} +getMessages(String): String[]
            {abstract} +getPrincipals(): Principal[]
            {abstract} +getRoles(): Principal[]
            {abstract} +hasPrincipal(Principal): boolean
            {abstract} +invalidate(): void
            {abstract} +getStatus(): String
            {abstract} +getSubject(): Subject
        }

        Page <|.. Attachment

        interface java.lang.Cloneable
        java.lang.Cloneable <|.. Page

        interface java.lang.Comparable<T> {
            {abstract} +compareTo(T): int
        }
        java.lang.Comparable <|.. Page

        java.lang.Cloneable <|.. Context

        Command <|.. Context

        interface org.apache.wiki.event.WikiEventListener {
            {abstract} +actionPerformed(WikiEvent): void
        }
        org.apache.wiki.event.WikiEventListener <|.. Session

        Page --> Acl: acl

        Context --> Page: page\nrealPage

        Context --> Engine: engine

        Context --> Session: wikiSession

        Context --> Command: command

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
