@startuml

    interface Page [[Page.html]] {
        {static} +DESCRIPTION: String
        {static} +ALIAS: String
        {static} +REDIRECT: String
        {static} +AUTHOR: String
        {static} +CHANGENOTE: String
        {static} +VIEWCOUNT: String
        {abstract} +getName(): String
        {abstract} +getLastModified(): Date
        {abstract} +setLastModified(Date): void
        {abstract} +setVersion(int): void
        {abstract} +getVersion(): int
        {abstract} +getSize(): long
        {abstract} +setSize(long): void
        {abstract} +setAuthor(String): void
        {abstract} +getAuthor(): String
        {abstract} +getWiki(): String
        {abstract} +invalidateMetadata(): void
        {abstract} +hasMetadata(): boolean
        {abstract} +setHasMetadata(): void
        {abstract} +getAttribute(String): T
        {abstract} +setAttribute(String, Object): void
        {abstract} +removeAttribute(String): T
        {abstract} +getAttributes(): Map<String, Object>
        {abstract} +getAcl(): Acl
        {abstract} +setAcl(Acl): void
        {abstract} +clone(): Page
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
