@startuml

    interface Session [[Session.html]] {
        {static} +ANONYMOUS: String
        {static} +ASSERTED: String
        {static} +AUTHENTICATED: String
        {static} +doPrivileged(Session, PrivilegedAction<?>): Object
        {abstract} +isAsserted(): boolean
        {abstract} +isAuthenticated(): boolean
        {abstract} +isAnonymous(): boolean
        {abstract} +getLoginPrincipal(): Principal
        {abstract} +getUserPrincipal(): Principal
        {abstract} +getLocale(): Locale
        {abstract} +addMessage(String): void
        {abstract} +addMessage(String, String): void
        {abstract} +clearMessages(): void
        {abstract} +clearMessages(String): void
        {abstract} +getMessages(): String[]
        {abstract} +getMessages(String): String[]
        {abstract} +getPrincipals(): Principal[]
        {abstract} +getRoles(): Principal[]
        {abstract} +hasPrincipal(Principal): boolean
        {abstract} +invalidate(): void
        {abstract} +getStatus(): String
        {abstract} +getSubject(): Subject
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
