@startuml

    class IfPlugin [[IfPlugin.html]] {
        {static} +PARAM_GROUP: String
        {static} +PARAM_USER: String
        {static} +PARAM_IP: String
        {static} +PARAM_PAGE: String
        {static} +PARAM_CONTAINS: String
        {static} +PARAM_VAR: String
        {static} +PARAM_IS: String
        {static} +PARAM_EXISTS: String
        +execute(WikiContext, Map<String, String>): String
        {static} +ifInclude(WikiContext, Map<String, String>): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
