@startuml

    class Note [[Note.html]] {
        {static} +PROP_NOTE_IMAGE: String
        {static} +DEFAULT_NOTE_IMAGE: String
        +execute(WikiContext, Map<String, String>): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
