@startuml

    class PageEventFilter [[PageEventFilter.html]] {
        +initialize(Properties): void
        +preTranslate(WikiContext, String): String
        +postTranslate(WikiContext, String): String
        +preSave(WikiContext, String): String
        +postSave(WikiContext, String): void
        +addWikiEventListener(WikiEventListener): void
        +removeWikiEventListener(WikiEventListener): void
        #fireEvent(int, WikiContext): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
