@startuml

    class HumanComparator [[HumanComparator.html]] {
        {static} +DEFAULT_HUMAN_COMPARATOR: Comparator<String>
        +HumanComparator()
        +HumanComparator(HumanComparator.CharType[])
        {static} +getInstance(): Comparator<String>
        +compare(String, String): int
        +getSortOrder(): HumanComparator.CharType[]
        +setSortOrder(HumanComparator.CharType[]): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
