@startuml

    class JavaNaturalComparator [[JavaNaturalComparator.html]] {
        {static} +DEFAULT_JAVA_COMPARATOR: Comparator<String>
        +compare(String, String): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
