@startuml

    namespace org.apache.wiki.ui.progress {

        abstract class ProgressItem [[ProgressItem.html]] {
            {static} +CREATED: int
            {static} +STARTED: int
            {static} +STOPPED: int
            {static} +FINISHED: int
            #m_state: int
            +getState(): int
            +setState(int): void
            {abstract} +getProgress(): int
        }

        class ProgressManager [[ProgressManager.html]] {
            {static} +JSON_PROGRESSTRACKER: String
            +getNewProgressIdentifier(): String
            +startProgress(ProgressItem, String): void
            +stopProgress(String): void
            +getProgress(String): int
        }

        class org.apache.wiki.ui.progress.ProgressManager.JSONTracker [[ProgressManager.JSONTracker.html]] {
            +getProgress(String): int
            +getServletMapping(): String
            +service(HttpServletRequest, HttpServletResponse, String, List<String>): void
        }

        interface org.apache.wiki.ajax.WikiAjaxServlet {
            {abstract} +getServletMapping(): String
            {abstract} +service(HttpServletRequest, HttpServletResponse, String, List<String>): void
        }
        org.apache.wiki.ajax.WikiAjaxServlet <|.. org.apache.wiki.ui.progress.ProgressManager.JSONTracker

        ProgressManager +-- org.apache.wiki.ui.progress.ProgressManager.JSONTracker

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
