@startuml

    interface AdminBeanManager [[AdminBeanManager.html]] {
        {abstract} +initialize(): void
        {abstract} +getAllBeans(): List<AdminBean>
        {abstract} +findBean(String): AdminBean
        {abstract} +actionPerformed(WikiEvent): void
        {abstract} +getTypeFromString(String): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
