@startuml

    namespace org.apache.wiki.preferences {

        class Preferences [[Preferences.html]] {
            {static} +SESSIONPREFS: String
            {static} +setupPreferences(PageContext): void
            {static} +reloadPreferences(PageContext): void
            {static} +getPreference(Context, String): String
            {static} +getPreference(PageContext, String): String
            {static} +getLocale(Context): Locale
            {static} +getBundle(Context, String): ResourceBundle
            {static} +getDateFormat(Context, Preferences.TimeFormat): SimpleDateFormat
            {static} +renderDate(Context, Date, Preferences.TimeFormat): String
        }

        enum org.apache.wiki.preferences.Preferences.TimeFormat [[Preferences.TimeFormat.html]] {
            {static} +TIME
            {static} +DATE
            {static} +DATETIME
        }

        class java.util.HashMap<K, V>
        java.util.HashMap <|-- Preferences

        Preferences +-- org.apache.wiki.preferences.Preferences.TimeFormat

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
