@startuml

    namespace org.apache.wiki.search.tika {

        class TikaSearchProvider [[TikaSearchProvider.html]] {
            #getAttachmentContent(Attachment): String
        }

        class org.apache.wiki.search.LuceneSearchProvider
        org.apache.wiki.search.LuceneSearchProvider <|-- TikaSearchProvider

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
