@startuml

    namespace org.apache.wiki.api.engine {

        interface AdminBeanManager [[AdminBeanManager.html]] {
            {abstract} +initialize(): void
            {abstract} +getAllBeans(): List<AdminBean>
            {abstract} +findBean(String): AdminBean
            {abstract} +actionPerformed(WikiEvent): void
            {abstract} +getTypeFromString(String): int
        }

        interface FilterManager [[FilterManager.html]] {
            {static} +PROP_FILTERXML: String
            {static} +DEFAULT_XMLFILE: String
            {static} +SYSTEM_FILTER_PRIORITY: int
            {static} +USER_FILTER_PRIORITY: int
            {abstract} +addPageFilter(PageFilter, int): void
            {abstract} +doPreTranslateFiltering(WikiContext, String): String
            {abstract} +doPostTranslateFiltering(WikiContext, String): String
            {abstract} +doPreSaveFiltering(WikiContext, String): String
            {abstract} +doPostSaveFiltering(WikiContext, String): void
            {abstract} +getFilterList(): List<PageFilter>
            {abstract} +destroy(): void
            {abstract} +modules(): Collection<WikiModuleInfo>
            {abstract} +getModuleInfo(String): WikiModuleInfo
        }

        interface PluginManager [[PluginManager.html]] {
            {static} +PROP_SEARCHPATH: String
            {static} +PROP_EXTERNALJARS: String
            {static} +DEFAULT_PACKAGE: String
            {static} +PARAM_BODY: String
            {static} +PARAM_CMDLINE: String
            {static} +PARAM_BOUNDS: String
            {static} +PARAM_DEBUG: String
            {abstract} +enablePlugins(boolean): void
            {abstract} +pluginsEnabled(): boolean
            {abstract} +getPluginPattern(): Pattern
            {abstract} +getPluginSearchPath(): String
            {abstract} +execute(WikiContext, String, Map<String, String>): String
            {abstract} +parseArgs(String): Map<String, String>
            {abstract} +execute(WikiContext, String): String
            {abstract} +modules(): Collection<WikiModuleInfo>
            {abstract} +getModuleInfo(String): DefaultPluginManager.WikiPluginInfo
            {abstract} +newWikiPlugin(String, ResourceBundle): WikiPlugin
        }

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
