@startuml

    namespace org.apache.wiki.modules {

        class WikiModuleInfo [[WikiModuleInfo.html]] {
            #m_name: String
            #m_description: String
            #m_moduleUrl: String
            #m_moduleVersion: String
            #m_htmlTemplate: String
            #m_scriptLocation: String
            #m_scriptText: String
            #m_stylesheetLocation: String
            #m_stylesheetText: String
            #m_author: String
            #m_authorUrl: String
            #m_resource: URL
            #m_minVersion: String
            #m_maxVersion: String
            #m_adminBeanClass: String
            +WikiModuleInfo(String)
            #initializeFromXML(Element): void
            +getAdminBeanClass(): String
            +getName(): String
            +getDescription(): String
            +getModuleUrl(): String
            +getModuleVersion(): String
            +getHtmlTemplate(): String
            +getStylesheetLocation(): String
            +getScriptLocation(): String
            +getAuthor(): String
            +getAuthorUrl(): String
            +getMinVersion(): String
            +getMaxVersion(): String
            #getTextResource(String): String
            +compareTo(WikiModuleInfo): int
        }

        interface ModuleManager [[ModuleManager.html]] {
            {static} +PLUGIN_RESOURCE_LOCATION: String
            {abstract} +checkCompatibility(WikiModuleInfo): boolean
            {abstract} +getModuleInfo(String): WikiModuleInfo
            {abstract} +modules(): Collection<WikiModuleInfo>
        }

        interface InternalModule [[InternalModule.html]] {
        }

        abstract class BaseModuleManager [[BaseModuleManager.html]] {
            #m_engine: Engine
            +BaseModuleManager(Engine)
            +checkCompatibility(WikiModuleInfo): boolean
            #modules(Iterator<T>): Collection<WikiModuleInfo>
        }

        interface java.lang.Comparable<T> {
            {abstract} +compareTo(T): int
        }
        java.lang.Comparable <|.. WikiModuleInfo

        ModuleManager <|.. BaseModuleManager

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
