@startuml

    interface Acl <<deprecated>> [[Acl.html]] {
        + --addEntry-- (AclEntry): boolean
        + --entries-- (): Enumeration<AclEntry>
        + --getEntry-- (Principal): AclEntry
        + --removeEntry-- (AclEntry): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
