@startuml

    class UserBean [[UserBean.html]] {
        +UserBean(WikiEngine)
        +getAttributeNames(): String[]
        +getMethodNames(): String[]
        +doPost(WikiContext): String
        +getTitle(): String
        +getType(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
