@startuml

    class DefaultRenderingManager [[DefaultRenderingManager.html]] {
        +initialize(Engine, Properties): void
        +beautifyTitle(String): String
        +beautifyTitleNoBreak(String): String
        +getParser(WikiContext, String): MarkupParser
        +getRenderedDocument(WikiContext, String): WikiDocument
        +getHTML(WikiContext, WikiDocument): String
        +getHTML(WikiContext, WikiPage): String
        +getHTML(String, int): String
        +textToHTML(WikiContext, String): String
        +textToHTML(WikiContext, String, StringTransmutator, StringTransmutator, StringTransmutator, boolean, boolean): String
        +getRenderer(WikiContext, WikiDocument): WikiRenderer
        +getWysiwygRenderer(WikiContext, WikiDocument): WikiRenderer
        +actionPerformed(WikiEvent): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
