@startuml

    namespace org.apache.wiki.render {

        class CustomXMLOutputProcessor [[CustomXMLOutputProcessor.html]] {
            #attributeEscapedEntitiesFilter(Writer, FormatStack, String): void
        }

        class XHTMLRenderer [[XHTMLRenderer.html]] {
            +XHTMLRenderer(WikiContext, WikiDocument)
            +getString(): String
        }

        abstract class WikiRenderer [[WikiRenderer.html]] {
            {static} +LINKS_TRANSLATION: String
            {static} +LINKS_SOURCE: String
            #m_context: WikiContext
            #m_document: WikiDocument
            #WikiRenderer(WikiContext, WikiDocument)
            {abstract} +getString(): String
        }

        class DefaultRenderingManager [[DefaultRenderingManager.html]] {
            +initialize(WikiEngine, Properties): void
            +beautifyTitle(String): String
            +beautifyTitleNoBreak(String): String
            +getParser(WikiContext, String): MarkupParser
            +getRenderedDocument(WikiContext, String): WikiDocument
            +getHTML(WikiContext, WikiDocument): String
            +getHTML(WikiContext, WikiPage): String
            +getHTML(String, int): String
            +textToHTML(WikiContext, String): String
            +textToHTML(WikiContext, String, StringTransmutator, StringTransmutator, StringTransmutator, boolean, boolean): String
            +getRenderer(WikiContext, WikiDocument): WikiRenderer
            +getWysiwygRenderer(WikiContext, WikiDocument): WikiRenderer
            +actionPerformed(WikiEvent): void
        }

        interface RenderingManager [[RenderingManager.html]] {
            {static} +PROP_PARSER: String
            {static} +PROP_RENDERER: String
            {static} +PROP_WYSIWYG_RENDERER: String
            {static} +PROP_BEAUTIFYTITLE: String
            {static} +DOCUMENTCACHE_NAME: String
            +getHTML(WikiContext, String): String
            +getHTML(String): String
            +textToHTML(WikiContext, String, StringTransmutator, StringTransmutator): String
            +textToHTML(WikiContext, String, StringTransmutator, StringTransmutator, StringTransmutator): String
            {abstract} +initialize(WikiEngine, Properties): void
            {abstract} +beautifyTitle(String): String
            {abstract} +beautifyTitleNoBreak(String): String
            {abstract} +getParser(WikiContext, String): MarkupParser
            {abstract} +getRenderedDocument(WikiContext, String): WikiDocument
            {abstract} +getRenderer(WikiContext, WikiDocument): WikiRenderer
            {abstract} +getWysiwygRenderer(WikiContext, WikiDocument): WikiRenderer
            {abstract} +getHTML(WikiContext, WikiDocument): String
            {abstract} +getHTML(WikiContext, WikiPage): String
            {abstract} +getHTML(String, int): String
            {abstract} +textToHTML(WikiContext, String): String
            {abstract} +textToHTML(WikiContext, String, StringTransmutator, StringTransmutator, StringTransmutator, boolean, boolean): String
        }

        class CreoleRenderer [[CreoleRenderer.html]] {
            +CreoleRenderer(WikiContext, WikiDocument)
            +getString(): String
        }

        class WysiwygEditingRenderer [[WysiwygEditingRenderer.html]] {
            +WysiwygEditingRenderer(WikiContext, WikiDocument)
            +getString(): String
        }

        class CleanTextRenderer [[CleanTextRenderer.html]] {
            +CleanTextRenderer(WikiContext, WikiDocument)
            +getString(): String
        }

        abstract class org.jdom2.output.support.AbstractXMLOutputProcessor
        org.jdom2.output.support.AbstractXMLOutputProcessor <|-- CustomXMLOutputProcessor

        WikiRenderer <|-- XHTMLRenderer

        RenderingManager <|.. DefaultRenderingManager

        interface org.apache.wiki.event.WikiEventListener {
            {abstract} +actionPerformed(WikiEvent): void
        }
        org.apache.wiki.event.WikiEventListener <|.. RenderingManager

        interface org.apache.wiki.modules.InternalModule
        org.apache.wiki.modules.InternalModule <|.. RenderingManager

        WikiRenderer <|-- CreoleRenderer

        WikiRenderer <|-- WysiwygEditingRenderer

        WikiRenderer <|-- CleanTextRenderer

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
