@startuml

    interface RenderingManager [[RenderingManager.html]] {
        {static} +PROP_PARSER: String
        {static} +PROP_RENDERER: String
        {static} +PROP_WYSIWYG_RENDERER: String
        {static} +PROP_BEAUTIFYTITLE: String
        {static} +DOCUMENTCACHE_NAME: String
        +getHTML(Context, String): String
        +getHTML(String): String
        +textToHTML(Context, String, StringTransmutator, StringTransmutator): String
        +textToHTML(Context, String, StringTransmutator, StringTransmutator, StringTransmutator): String
        {abstract} +beautifyTitle(String): String
        {abstract} +beautifyTitleNoBreak(String): String
        {abstract} +getParser(Context, String): MarkupParser
        {abstract} +getRenderedDocument(Context, String): WikiDocument
        {abstract} +getRenderer(Context, WikiDocument): WikiRenderer
        {abstract} +getWysiwygRenderer(Context, WikiDocument): WikiRenderer
        {abstract} +getHTML(Context, WikiDocument): String
        {abstract} +getHTML(Context, Page): String
        {abstract} +getHTML(String, int): String
        {abstract} +textToHTML(Context, String): String
        {abstract} +textToHTML(Context, String, StringTransmutator, StringTransmutator, StringTransmutator, boolean, boolean): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
