@startuml

    class SearchManager [[SearchManager.html]] {
        {static} +PROP_SEARCHPROVIDER: String
        {static} +JSON_SEARCH: String
        +SearchManager(WikiEngine, Properties)
        +initialize(WikiEngine, Properties): void
        +getSearchEngine(): SearchProvider
        +findPages(String, WikiContext): Collection<SearchResult>
        +pageRemoved(WikiPage): void
        +postSave(WikiContext, String): void
        +reindexPage(WikiPage): void
        +actionPerformed(WikiEvent): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
