@startuml

    class SearchMatcher [[SearchMatcher.html]] {
        +SearchMatcher(WikiEngine, QueryItem[])
        +matchPageContent(String, String): SearchResult
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
