@startuml

    class PluginException [[PluginException.html]] {
        +PluginException(String)
        +PluginException(String, Throwable)
        +getRootThrowable(): Throwable
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
