@startuml

    class WikiException [[WikiException.html]] {
        +WikiException(String)
        +WikiException(String, Throwable)
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
