@startuml

    namespace org.apache.wiki.ui.admin {

        interface AdminBeanManager [[AdminBeanManager.html]] {
            {abstract} +initialize(): void
            {abstract} +findBean(String): AdminBean
            {abstract} +actionPerformed(WikiEvent): void
            {abstract} +getTypeFromString(String): int
        }

        interface AdminBean [[AdminBean.html]] {
            {static} +UNKNOWN: int
            {static} +CORE: int
            {static} +EDITOR: int
            {abstract} +initialize(Engine): void
            {abstract} +getTitle(): String
            {abstract} +getType(): int
        }

        abstract class WikiFormAdminBean [[WikiFormAdminBean.html]] {
            +doGet(WikiContext): String
            +handlePost(WikiContext, HttpServletRequest, HttpServletResponse): String
            {abstract} +getForm(WikiContext): String
            {abstract} +handleResponse(WikiContext, Map<?, ?>): void
        }

        class DefaultAdminBeanManager [[DefaultAdminBeanManager.html]] {
            +DefaultAdminBeanManager(Engine)
            +initialize(): void
            +findBean(String): AdminBean
            +getTypeFromString(String): int
            +actionPerformed(WikiEvent): void
        }

        abstract class SimpleAdminBean [[SimpleAdminBean.html]] {
            #m_engine: Engine
            +initialize(Engine): void
            +doGet(WikiContext): String
            +doPost(WikiContext): String
            +getId(): String
        }

        interface org.apache.wiki.ui.GenericHTTPHandler {
            {abstract} +getId(): String
            {abstract} +doGet(WikiContext): String
            {abstract} +doPost(WikiContext): String
        }
        org.apache.wiki.ui.GenericHTTPHandler <|.. AdminBean

        AdminBean <|.. WikiFormAdminBean

        interface org.apache.wiki.event.WikiEventListener {
            {abstract} +actionPerformed(WikiEvent): void
        }
        org.apache.wiki.event.WikiEventListener <|.. DefaultAdminBeanManager

        AdminBeanManager <|.. DefaultAdminBeanManager

        abstract class org.apache.wiki.management.SimpleMBean {
            {abstract} +getAttributeNames(): String[]
            {abstract} +getMethodNames(): String[]
        }
        org.apache.wiki.management.SimpleMBean <|-- SimpleAdminBean

        AdminBean <|.. SimpleAdminBean

        AdminBeanManager --> "*" AdminBean: allBeans

        DefaultAdminBeanManager --> "*" AdminBean: allBeans

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
