@startuml

    abstract class SimpleAdminBean [[SimpleAdminBean.html]] {
        #m_engine: Engine
        +initialize(Engine): void
        +doGet(Context): String
        +doPost(Context): String
        +getId(): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
