@startuml

    abstract class WikiFormAdminBean [[WikiFormAdminBean.html]] {
        +doGet(WikiContext): String
        +handlePost(WikiContext, HttpServletRequest, HttpServletResponse): String
        {abstract} +getForm(WikiContext): String
        {abstract} +handleResponse(WikiContext, Map<?, ?>): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
