@startuml

    class BasicAttachmentProvider.AttachmentFilter [[BasicAttachmentProvider.AttachmentFilter.html]] {
        +accept(File, String): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
