@startuml

    class FileSystemProvider [[FileSystemProvider.html]] {
        {static} +PROP_EXT: String
        +putPageText(Page, String): void
        +getPageInfo(String, int): Page
        +deletePage(String): void
        +movePage(String, String): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
