@startuml

    abstract class AbstractRPCHandler [[AbstractRPCHandler.html]] {
        {static} +ERR_NOPAGE: int
        {static} +ERR_NOPERMISSION: int
        {static} +LINK_LOCAL: String
        {static} +LINK_EXTERNAL: String
        {static} +LINK_INLINE: String
        {static} +RPC_VERSION: int
        #m_engine: Engine
        #m_context: WikiContext
        +initialize(WikiContext): void
        +getRecentChanges(Date): Vector
        #checkPermission(Permission): void
        +getRPCVersionSupported(): int
        {abstract} #encodeWikiPage(WikiPage): Hashtable
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
