@startuml

    class MetaWeblogHandler [[MetaWeblogHandler.html]] {
        +initialize(Context): void
        +getCategories(String, String, String): Hashtable<Object, Object>
        +getRecentPosts(String, String, String, int): Hashtable
        +newPost(String, String, String, Hashtable<String, Object>, boolean): String
        +newMediaObject(String, String, String, Hashtable<String, Object>): Hashtable<String, Object>
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
