@startuml

    namespace org.apache.wiki.xmlrpc {

        class RPCHandler [[RPCHandler.html]] {
            +getApplicationName(): String
            +getAllPages(): Vector
            #encodeWikiPage(WikiPage): Hashtable<String, Object>
            +getRecentChanges(Date): Vector
            +getPageInfo(String): Hashtable
            +getPageInfoVersion(String, int): Hashtable
            +getPage(String): byte[]
            +getPageVersion(String, int): byte[]
            +getPageHTML(String): byte[]
            +getPageHTMLVersion(String, int): byte[]
            +listLinks(String): Vector
        }

        class RPCHandlerUTF8 [[RPCHandlerUTF8.html]] {
            +getApplicationName(): String
            +getAllPages(): Vector<String>
            #encodeWikiPage(WikiPage): Hashtable<String, Object>
            +getRecentChanges(Date): Vector<Hashtable<String, Object>>
            +getPageInfo(String): Hashtable<String, Object>
            +getPageInfoVersion(String, int): Hashtable<String, Object>
            +getPage(String): String
            +getPageVersion(String, int): String
            +getPageHTML(String): String
            +getPageHTMLVersion(String, int): String
            +listLinks(String): Vector<Hashtable<String, String>>
        }

        interface WikiRPCHandler [[WikiRPCHandler.html]] {
            {abstract} +initialize(WikiContext): void
        }

        class MetaWeblogHandler [[MetaWeblogHandler.html]] {
            +initialize(WikiContext): void
            +getCategories(String, String, String): Hashtable
            +getRecentPosts(String, String, String, int): Hashtable
            +newPost(String, String, String, Hashtable, boolean): String
            +newMediaObject(String, String, String, Hashtable): Hashtable
        }

        class RPCServlet [[RPCServlet.html]] {
            {static} +XMLRPC_PREFIX: String
            +initHandler(String, String): void
            +init(ServletConfig): void
            +doPost(HttpServletRequest, HttpServletResponse): void
            +doGet(HttpServletRequest, HttpServletResponse): void
        }

        abstract class AbstractRPCHandler [[AbstractRPCHandler.html]] {
            {static} +ERR_NOPAGE: int
            {static} +ERR_NOPERMISSION: int
            {static} +LINK_LOCAL: String
            {static} +LINK_EXTERNAL: String
            {static} +LINK_INLINE: String
            {static} +RPC_VERSION: int
            #m_engine: WikiEngine
            #m_context: WikiContext
            +initialize(WikiContext): void
            +getRecentChanges(Date): Vector
            #checkPermission(Permission): void
            +getRPCVersionSupported(): int
            {abstract} #encodeWikiPage(WikiPage): Hashtable
        }

        AbstractRPCHandler <|-- RPCHandler

        AbstractRPCHandler <|-- RPCHandlerUTF8

        WikiRPCHandler <|.. MetaWeblogHandler

        abstract class javax.servlet.http.HttpServlet
        javax.servlet.http.HttpServlet <|-- RPCServlet

        WikiRPCHandler <|.. AbstractRPCHandler

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
