@startuml

    class RPCHandlerUTF8 [[RPCHandlerUTF8.html]] {
        +getApplicationName(): String
        +getAllPages(): Vector<String>
        #encodeWikiPage(WikiPage): Hashtable<String, Object>
        +getRecentChanges(Date): Vector<Hashtable<String, Object>>
        +getPageInfo(String): Hashtable<String, Object>
        +getPageInfoVersion(String, int): Hashtable<String, Object>
        +getPage(String): String
        +getPageVersion(String, int): String
        +getPageHTML(String): String
        +getPageHTMLVersion(String, int): String
        +listLinks(String): Vector<Hashtable<String, String>>
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
