@startuml

    namespace org.apache.wiki.api.engine {

        interface RenderApi [[RenderApi.html]] {
            {abstract} +textToHTML(Context, String): String
        }

        interface Initializable [[Initializable.html]] {
            {abstract} +initialize(Engine, Properties): void
        }

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
