@startuml

    class ImageLinkAttributeProviderState [[ImageLinkAttributeProviderState.html]] {
        +ImageLinkAttributeProviderState(WikiContext, String, boolean)
        +setAttributes(Attributes, JSPWikiLink): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
