@startuml

    class TranslationsCheck [[TranslationsCheck.html]] {
        {static} +main(String[]): void
        +diff(String, String): Map<String, Integer>
        +detectDuplicates(String): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
