@startuml

    class WikiPage [[WikiPage.html]] {
        +WikiPage(Engine, String)
        +getName(): String
        +getAttribute(String): T
        +setAttribute(String, Object): void
        +getAttributes(): Map<String, Object>
        +removeAttribute(String): T
        +getLastModified(): Date
        +setLastModified(Date): void
        +setVersion(int): void
        +getVersion(): int
        +getSize(): long
        +setSize(long): void
        +getAcl(): Acl
        +setAuthor(String): void
        +getAuthor(): String
        +getWiki(): String
        +invalidateMetadata(): void
        +hasMetadata(): boolean
        +setHasMetadata(): void
        +compareTo(Page): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
