@startuml

    class FileUtil [[FileUtil.html]] {
        {static} +newTmpFile(String, Charset): File
        {static} +newTmpFile(String): File
        {static} +runSimpleCommand(String, String): String
        {static} +copyContents(Reader, Writer): void
        {static} +copyContents(InputStream, OutputStream): void
        {static} +readContents(InputStream, String): String
        {static} +readContents(Reader): String
        {static} +getThrowingMethod(Throwable): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
