@startuml

    class HttpUtil [[HttpUtil.html]] {
        {static} +getRemoteAddress(HttpServletRequest): String
        {static} +retrieveCookieValue(HttpServletRequest, String): String
        {static} +createETag(String, Date): String
        {static} +checkFor304(HttpServletRequest, String, Date): boolean
        {static} +guessValidURI(String): String
        {static} +safeGetQueryString(HttpServletRequest, Charset): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
