@startuml

    class Serializer [[Serializer.html]] {
        {static} #BASE64_PREFIX: String
        {static} +deserializeFromBase64(String): Map<String, ?>
        {static} +serializeToBase64(Map<String, Serializable>): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
