@startuml

    abstract class AbstractLoginModule [[AbstractLoginModule.html]] {
        {static} #NULL: String
        #m_handler: CallbackHandler
        #m_options: Map<String, ?>
        #m_principals: Collection<Principal>
        #m_state: Map<String, ?>
        #m_subject: Subject
        +abort(): boolean
        +commit(): boolean
        +initialize(Subject, CallbackHandler, Map<String, ?>, Map<String, ?>): void
        +logout(): boolean
        {abstract} +login(): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
