@startuml

    class PersistentMapDecorator [[PersistentMapDecorator.html]] {
        +PersistentMapDecorator(Map<Object, Object>)
        +clear(): void
        +containsKey(Object): boolean
        +containsValue(Object): boolean
        +entrySet(): Set<Map.Entry<Object, Object>>
        +equals(Object): boolean
        +get(Object): Object
        +hashCode(): int
        +isEmpty(): boolean
        +keySet(): Set<Object>
        +put(Object, Object): Object
        +putAll(Map<?, ?>): void
        +remove(Object): Object
        +size(): int
        +toString(): String
        +values(): Collection<Object>
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
