@startuml

    class XHtmlToWikiConfig [[XHtmlToWikiConfig.html]] {
        +XHtmlToWikiConfig()
        +XHtmlToWikiConfig(WikiContext)
        +getAttachPage(): String
        +setAttachPage(String): void
        +getOutlink(): String
        +setOutlink(String): void
        +getPageInfoJsp(): String
        +setPageInfoJsp(String): void
        +getPageName(): String
        +setPageName(String): void
        +getWikiJspPage(): String
        +setWikiJspPage(String): void
        +getEditJspPage(): String
        +setEditJspPage(String): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
