@startuml

    class XHtmlElementToWikiTranslator [[XHtmlElementToWikiTranslator.html]] {
        +XHtmlElementToWikiTranslator(Element)
        +XHtmlElementToWikiTranslator(Element, XHtmlToWikiConfig)
        +getWikiString(): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
