@startuml

    class Entry [[Entry.html]] {
        +setAuthor(String): void
        +getAuthor(): String
        +getPage(): WikiPage
        +setPage(WikiPage): void
        +setTitle(String): void
        +getTitle(): String
        +setURL(String): void
        +getURL(): String
        +setContent(String): void
        +getContent(): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
