@startuml

    namespace org.apache.wiki.rss {

        class AtomFeed [[AtomFeed.html]] {
            {static} +RFC3339FORMAT: String
            +AtomFeed(WikiContext)
            +getString(): String
        }

        class Entry [[Entry.html]] {
            +setAuthor(String): void
            +getAuthor(): String
            +getPage(): WikiPage
            +setPage(WikiPage): void
            +setTitle(String): void
            +getTitle(): String
            +setURL(String): void
            +getURL(): String
            +setContent(String): void
            +getContent(): String
        }

        class RSS20Feed [[RSS20Feed.html]] {
            +RSS20Feed(WikiContext)
            +getString(): String
        }

        class RSSThread [[RSSThread.html]] {
            +RSSThread(Engine, File, int)
            +startupTask(): void
            +backgroundTask(): void
        }

        class RSS10Feed [[RSS10Feed.html]] {
            +RSS10Feed(WikiContext)
            +getString(): String
        }

        abstract class Feed [[Feed.html]] {
            {static} +VAR_BLOGNAME: String
            #m_feedURL: String
            #m_channelTitle: String
            #m_channelDescription: String
            #m_channelLanguage: String
            #m_wikiContext: WikiContext
            #m_mode: String
            +Feed(WikiContext)
            {static} +getSiteName(WikiContext): String
            +setMode(String): void
            +addEntry(Entry): void
            +getChannelDescription(): String
            +setChannelDescription(String): void
            +getChannelLanguage(): String
            +setChannelLanguage(String): void
            +getChannelTitle(): String
            +setChannelTitle(String): void
            +getFeedURL(): String
            +setFeedURL(String): void
            #getMimeType(ServletContext, String): String
            {static} +format(String): String
            {abstract} +getString(): String
        }

        class RSSGenerator [[RSSGenerator.html]] {
            {static} +RSS10: String
            {static} +RSS20: String
            {static} +ATOM: String
            {static} +MODE_BLOG: String
            {static} +MODE_WIKI: String
            {static} +MODE_FULL: String
            {static} +PROP_CHANNEL_DESCRIPTION: String
            {static} +PROP_CHANNEL_LANGUAGE: String
            {static} +PROP_CHANNEL_TITLE: String
            {static} +PROP_GENERATE_RSS: String
            {static} +PROP_RSSFILE: String
            {static} +PROP_INTERVAL: String
            {static} +PROP_RSS_AUTHOR: String
            {static} +PROP_RSS_AUTHOREMAIL: String
            +RSSGenerator(Engine, Properties)
            {static} +format(String): String
            +generate(): String
            {static} +getContentType(String): String
            +generateFeed(WikiContext, List<WikiPage>, String, String): String
            +isEnabled(): boolean
            +setEnabled(boolean): void
            #generateFullWikiRSS(WikiContext, Feed): String
            #generateWikiPageRSS(WikiContext, List<WikiPage>, Feed): String
            #generateBlogRSS(WikiContext, List<WikiPage>, Feed): String
        }

        Feed <|-- AtomFeed

        Feed <|-- RSS20Feed

        abstract class org.apache.wiki.WikiBackgroundThread {
            {abstract} +backgroundTask(): void
        }
        org.apache.wiki.WikiBackgroundThread <|-- RSSThread

        Feed <|-- RSS10Feed

        Feed --> "*" Entry: m_entries

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
