@startuml

    class RSSGenerator [[RSSGenerator.html]] {
        {static} +RSS10: String
        {static} +RSS20: String
        {static} +ATOM: String
        {static} +MODE_BLOG: String
        {static} +MODE_WIKI: String
        {static} +MODE_FULL: String
        {static} +PROP_CHANNEL_DESCRIPTION: String
        {static} +PROP_CHANNEL_LANGUAGE: String
        {static} +PROP_CHANNEL_TITLE: String
        {static} +PROP_GENERATE_RSS: String
        {static} +PROP_RSSFILE: String
        {static} +PROP_INTERVAL: String
        {static} +PROP_RSS_AUTHOR: String
        {static} +PROP_RSS_AUTHOREMAIL: String
        +RSSGenerator(Engine, Properties)
        {static} +format(String): String
        +generate(): String
        {static} +getContentType(String): String
        +generateFeed(WikiContext, List<WikiPage>, String, String): String
        +isEnabled(): boolean
        +setEnabled(boolean): void
        #generateFullWikiRSS(WikiContext, Feed): String
        #generateWikiPageRSS(WikiContext, List<WikiPage>, Feed): String
        #generateBlogRSS(WikiContext, List<WikiPage>, Feed): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
