@startuml

    interface RSSGenerator [[RSSGenerator.html]] {
        {static} +RSS10: String
        {static} +RSS20: String
        {static} +ATOM: String
        {static} +MODE_BLOG: String
        {static} +MODE_WIKI: String
        {static} +MODE_FULL: String
        {static} +PROP_CHANNEL_DESCRIPTION: String
        {static} +PROP_CHANNEL_LANGUAGE: String
        {static} +PROP_CHANNEL_TITLE: String
        {static} +PROP_GENERATE_RSS: String
        {static} +PROP_RSSFILE: String
        {static} +PROP_INTERVAL: String
        {static} +PROP_RSS_AUTHOR: String
        {static} +PROP_RSS_AUTHOREMAIL: String
        {static} +format(String): String
        {static} +getContentType(String): String
        {abstract} +initialize(Engine, Properties): void
        {abstract} +generate(): String
        {abstract} +generateFeed(Context, List<Page>, String, String): String
        {abstract} +isEnabled(): boolean
        {abstract} +setEnabled(boolean): void
        {abstract} +getRssFile(): String
        {abstract} +generateFullWikiRSS(Context, Feed): String
        {abstract} +generateWikiPageRSS(Context, List<Page>, Feed): String
        {abstract} +generateBlogRSS(Context, List<Page>, Feed): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
