@startuml

    class ContentsDSL [[ContentsDSL.html]] {
        +attachment(Engine, String, String): Attachment
        +page(Engine, String): Page
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
