@startuml

    class SessionDSL [[SessionDSL.html]] {
        +remove(Engine, HttpServletRequest): void
        +find(Engine, HttpServletRequest): Session
        +guest(Engine): Session
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
