@startuml

    class Wiki [[Wiki.html]] {
        {static} +init(ServletContext): Properties
        {static} +acls(): AclsDSL
        {static} +contents(): ContentsDSL
        {static} +context(): ContextDSL
        {static} +engine(): EngineDSL
        {static} +session(): SessionDSL
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
