@startuml

    interface AclManager [[AclManager.html]] {
        {abstract} +initialize(Engine, Properties): void
        {abstract} +parseAcl(WikiPage, String): Acl
        {abstract} +getPermissions(WikiPage): Acl
        {abstract} +setPermissions(WikiPage, Acl): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
