@startuml

    class InputValidator [[InputValidator.html]] {
        {static} +STANDARD: int
        {static} +EMAIL: int
        {static} +ID: int
        {static} #EMAIL_PATTERN: Pattern
        {static} #UNSAFE_PATTERN: Pattern
        {static} #ID_PATTERN: Pattern
        +InputValidator(String, WikiContext)
        +validateNotNull(String, String): boolean
        +validateNotNull(String, String, int): boolean
        +validate(String, String, int): boolean
        {static} +isBlank(String): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
