@startuml

    class Installer [[Installer.html]] {
        {static} +ADMIN_ID: String
        {static} +ADMIN_NAME: String
        {static} +INSTALL_INFO: String
        {static} +INSTALL_ERROR: String
        {static} +INSTALL_WARNING: String
        {static} +APP_NAME: String
        {static} +STORAGE_DIR: String
        {static} +PAGE_DIR: String
        {static} +WORK_DIR: String
        {static} +ADMIN_GROUP: String
        {static} +PROPFILENAME: String
        {static} +TMP_DIR: String
        +Installer(HttpServletRequest, ServletConfig)
        +adminExists(): boolean
        +createAdministrator(): String
        +getPropertiesList(): String
        +getPropertiesPath(): String
        +getProperty(String): String
        +parseProperties(): void
        +saveProperties(): void
        +validateProperties(): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
