@startuml

    class WikiCommand [[WikiCommand.html]] {
        {static} +CREATE_GROUP: Command
        {static} +ERROR: Command
        {static} +FIND: Command
        {static} +INSTALL: Command
        {static} +LOGIN: Command
        {static} +LOGOUT: Command
        {static} +MESSAGE: Command
        {static} +PREFS: Command
        {static} +WORKFLOW: Command
        {static} +ADMIN: Command
        +targetedCommand(Object): Command
        +getName(): String
        +requiredPermission(): Permission
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
