@startuml

    class WikiEngineEvent [[WikiEngineEvent.html]] {
        {static} +INITIALIZING: int
        {static} +INITIALIZED: int
        {static} +SHUTDOWN: int
        {static} +STOPPED: int
        +WikiEngineEvent(Object, int)
        #setType(int): void
        +getEngine(): WikiEngine
        {static} +isValidType(int): boolean
        +eventName(): String
        +getTypeDescription(): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
