@startuml

    class WikiPageEvent [[WikiPageEvent.html]] {
        {static} +PAGE_LOCK: int
        {static} +PAGE_UNLOCK: int
        {static} +PRE_TRANSLATE_BEGIN: int
        {static} +PRE_TRANSLATE: int
        {static} +PRE_TRANSLATE_END: int
        {static} +POST_TRANSLATE_BEGIN: int
        {static} +POST_TRANSLATE: int
        {static} +POST_TRANSLATE_END: int
        {static} +PRE_SAVE_BEGIN: int
        {static} +PRE_SAVE: int
        {static} +PRE_SAVE_END: int
        {static} +POST_SAVE_BEGIN: int
        {static} +POST_SAVE: int
        {static} +POST_SAVE_END: int
        {static} +PAGE_REQUESTED: int
        {static} +PAGE_DELIVERED: int
        {static} +PAGE_DELETE_REQUEST: int
        {static} +PAGE_DELETED: int
        +WikiPageEvent(Object, int, String)
        +getPageName(): String
        {static} +isValidType(int): boolean
        +eventName(): String
        +getTypeDescription(): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
