@startuml

    class WikiPageRenameEvent [[WikiPageRenameEvent.html]] {
        {static} +PAGE_RENAMED: int
        +WikiPageRenameEvent(Object, String, String)
        +getOldPageName(): String
        +getNewPageName(): String
        {static} +isValidType(int): boolean
        +eventName(): String
        +getTypeDescription(): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
