@startuml

    class WorkflowEvent [[WorkflowEvent.html]] {
        {static} +CREATED: int
        {static} +STARTED: int
        {static} +RUNNING: int
        {static} +WAITING: int
        {static} +COMPLETED: int
        {static} +ABORTED: int
        +WorkflowEvent(Object, int)
        +eventName(int): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
