@startuml

    interface AdminBean [[AdminBean.html]] {
        {static} +UNKNOWN: int
        {static} +CORE: int
        {static} +EDITOR: int
        {abstract} +initialize(Engine): void
        {abstract} +getTitle(): String
        {abstract} +getType(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
