@startuml

    class DefaultAdminBeanManager [[DefaultAdminBeanManager.html]] {
        +DefaultAdminBeanManager(Engine)
        +initialize(): void
        +getAllBeans(): List<AdminBean>
        +findBean(String): AdminBean
        +getTypeFromString(String): int
        +actionPerformed(WikiEvent): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
