@startuml

    abstract class WikiFormAdminBean [[WikiFormAdminBean.html]] {
        +doGet(Context): String
        +handlePost(Context, HttpServletRequest, HttpServletResponse): String
        {abstract} +getForm(Context): String
        {abstract} +handleResponse(Context, Map<?, ?>): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
