@startuml

    class ExternalLinkNodePostProcessorState [[ExternalLinkNodePostProcessorState.html]] {
        +ExternalLinkNodePostProcessorState(WikiContext)
        +process(NodeTracker, JSPWikiLink): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
