@startuml

    class MetadataLinkNodePostProcessorState [[MetadataLinkNodePostProcessorState.html]] {
        +MetadataLinkNodePostProcessorState(WikiContext)
        +process(NodeTracker, JSPWikiLink): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
