@startuml

    class NoSuchPageTag [[NoSuchPageTag.html]] {
        +initTag(): void
        +setPage(String): void
        +getPage(): String
        +doWikiStartTag(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
