@startuml

    class ParamTag [[ParamTag.html]] {
        +release(): void
        +setName(String): void
        +setValue(String): void
        +doEndTag(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
