@startuml

    class PluginTag [[PluginTag.html]] {
        +release(): void
        +setPlugin(String): void
        +setArgs(String): void
        +doWikiStartTag(): int
        +doEndTag(): int
        +doAfterBody(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
