@startuml

    class RequestResourceTag [[RequestResourceTag.html]] {
        +initTag(): void
        +doWikiStartTag(): int
        +getResource(): String
        +setResource(String): void
        +getType(): String
        +setType(String): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
