@startuml

    class SearchResultIteratorTag [[SearchResultIteratorTag.html]] {
        +release(): void
        +setMaxItems(int): void
        +setStart(int): void
        +doStartTag(): int
        +doAfterBody(): int
        +doEndTag(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
