@startuml

    class AuthorizationManager [[AuthorizationManager.html]] {
        {static} +DEFAULT_AUTHORIZER: String
        {static} #POLICY: String
        {static} #DEFAULT_POLICY: String
        {static} +PROP_AUTHORIZER: String
        +checkPermission(WikiSession, Permission): boolean
        +isUserInRole(WikiSession, Principal): boolean
        +getAuthorizer(): Authorizer
        #hasRoleOrPrincipal(WikiSession, Principal): boolean
        +hasAccess(WikiContext, HttpServletResponse): boolean
        +hasAccess(WikiContext, HttpServletResponse, boolean): boolean
        +initialize(WikiEngine, Properties): void
        #allowedByLocalPolicy(Principal[], Permission): boolean
        #checkStaticPermission(WikiSession, Permission): boolean
        +resolvePrincipal(String): Principal
        +addWikiEventListener(WikiEventListener): void
        +removeWikiEventListener(WikiEventListener): void
        #fireEvent(int, Principal, Object): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
