@startuml

    class AuthenticationManager [[AuthenticationManager.html]] {
        {static} +COOKIE_MODULE: String
        {static} +COOKIE_AUTHENTICATION_MODULE: String
        {static} +PROP_STOREIPADDRESS: String
        {static} +PROP_ALLOW_COOKIE_AUTH: String
        {static} +PROP_LOGIN_THROTTLING: String
        {static} #log: Logger
        {static} #PREFIX_LOGIN_MODULE_OPTIONS: String
        {static} #PROP_ALLOW_COOKIE_ASSERTIONS: String
        {static} #PROP_LOGIN_MODULE: String
        {static} #EMPTY_MAP: Map<String, String>
        #m_loginModuleClass: Class<?>
        #m_loginModuleOptions: Map<String, String>
        +initialize(WikiEngine, Properties): void
        +isContainerAuthenticated(): boolean
        +login(HttpServletRequest): boolean
        +login(WikiSession, HttpServletRequest, String, String): boolean
        +logout(HttpServletRequest): void
        +allowsCookieAssertions(): boolean
        +allowsCookieAuthentication(): boolean
        {static} +isRolePrincipal(Principal): boolean
        {static} +isUserPrincipal(Principal): boolean
        #doJAASLogin(Class<?>, CallbackHandler, Map<String, String>): Set<Principal>
        {static} #findConfigFile(WikiEngine, String): URL
        #getLoginPrincipal(Set<Principal>): Principal
        +addWikiEventListener(WikiEventListener): void
        +removeWikiEventListener(WikiEventListener): void
        #fireEvent(int, Principal, Object): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
