@startuml

    namespace org.apache.wiki.auth {

        class NoSuchPrincipalException [[NoSuchPrincipalException.html]] {
            +NoSuchPrincipalException(String)
        }

        class WikiSecurityException [[WikiSecurityException.html]] {
            +WikiSecurityException(String)
            +WikiSecurityException(String, Throwable)
        }

        class PrincipalComparator [[PrincipalComparator.html]] {
            +compare(Principal, Principal): int
        }

        interface Authorizer [[Authorizer.html]] {
            {abstract} +findRole(String): Principal
            {abstract} +initialize(WikiEngine, Properties): void
            {abstract} +isUserInRole(WikiSession, Principal): boolean
        }

        class SecurityVerifier [[SecurityVerifier.html]] {
            {static} +ERROR: String
            {static} +WARNING: String
            {static} +INFO: String
            {static} +ERROR_POLICY: String
            {static} +WARNING_POLICY: String
            {static} +INFO_POLICY: String
            {static} +ERROR_JAAS: String
            {static} +WARNING_JAAS: String
            {static} +ERROR_ROLES: String
            {static} +INFO_ROLES: String
            {static} +ERROR_DB: String
            {static} +WARNING_DB: String
            {static} +INFO_DB: String
            {static} +ERROR_GROUPS: String
            {static} +WARNING_GROUPS: String
            {static} +INFO_GROUPS: String
            {static} +INFO_JAAS: String
            +SecurityVerifier(WikiEngine, WikiSession)
            +policyPrincipals(): Principal[]
            +policyRoleTable(): String
            +containerRoleTable(): String
            +isSecurityPolicyConfigured(): boolean
            +webContainerRoles(): Principal[]
            #verifyPolicyAndContainerRoles(): void
            #verifyGroupDatabase(): void
            #verifyJaas(): void
            #getFileFromProperty(String): File
            #verifyPolicy(): void
            #verifyStaticPermission(Principal, Permission): boolean
            #verifyUserDatabase(): void
        }

        class GroupPrincipal [[GroupPrincipal.html]] {
            +GroupPrincipal(String)
            +getName(): String
        }

        class WikiPrincipal [[WikiPrincipal.html]] {
            {static} +GUEST: Principal
            {static} +FULL_NAME: String
            {static} +LOGIN_NAME: String
            {static} +WIKI_NAME: String
            {static} +UNSPECIFIED: String
            {static} +COMPARATOR: Comparator<Principal>
            #WikiPrincipal()
            +WikiPrincipal(String)
            +WikiPrincipal(String, String)
            +getName(): String
            +getType(): String
            +compareTo(Principal): int
        }

        class SessionMonitor [[SessionMonitor.html]] {
            +SessionMonitor()
            {static} +getInstance(WikiEngine): SessionMonitor
            +find(HttpSession): WikiSession
            +remove(HttpSession): void
            +sessions(): int
            +userPrincipals(): Principal[]
            +addWikiEventListener(WikiEventListener): void
            +removeWikiEventListener(WikiEventListener): void
            #fireEvent(int, Principal, WikiSession): void
            +sessionCreated(HttpSessionEvent): void
            +sessionDestroyed(HttpSessionEvent): void
        }

        class UserManager [[UserManager.html]] {
            {static} +JSON_USERS: String
            +initialize(WikiEngine, Properties): void
            +getUserDatabase(): UserDatabase
            +getUserProfile(WikiSession): UserProfile
            +setUserProfile(WikiSession, UserProfile): void
            +startUserProfileCreationWorkflow(WikiSession, UserProfile): void
            +parseProfile(WikiContext): UserProfile
            +validateProfile(WikiContext, UserProfile): void
            +listWikiNames(): Principal[]
            +addWikiEventListener(WikiEventListener): void
            +removeWikiEventListener(WikiEventListener): void
            #fireEvent(int, WikiSession, Object): void
        }

        class org.apache.wiki.auth.UserManager.DummyUserDatabase [[UserManager.DummyUserDatabase.html]] {
            +deleteByLoginName(String): void
            +findByEmail(String): UserProfile
            +findByFullName(String): UserProfile
            +findByLoginName(String): UserProfile
            +findByUid(String): UserProfile
            +findByWikiName(String): UserProfile
            +initialize(WikiEngine, Properties): void
            +rename(String, String): void
            +save(UserProfile): void
        }

        class org.apache.wiki.auth.UserManager.JSONUserModule [[UserManager.JSONUserModule.html]] {
            +JSONUserModule(UserManager)
            +getServletMapping(): String
            +service(HttpServletRequest, HttpServletResponse, String, List<String>): void
            +getUserInfo(String): UserProfile
        }

        class AuthenticationManager [[AuthenticationManager.html]] {
            {static} +COOKIE_MODULE: String
            {static} +COOKIE_AUTHENTICATION_MODULE: String
            {static} +PROP_STOREIPADDRESS: String
            {static} +PROP_ALLOW_COOKIE_AUTH: String
            {static} +PROP_LOGIN_THROTTLING: String
            {static} #log: Logger
            {static} #PREFIX_LOGIN_MODULE_OPTIONS: String
            {static} #PROP_ALLOW_COOKIE_ASSERTIONS: String
            {static} #PROP_LOGIN_MODULE: String
            {static} #EMPTY_MAP: Map<String, String>
            #m_loginModuleClass: Class<?>
            #m_loginModuleOptions: Map<String, String>
            +initialize(WikiEngine, Properties): void
            +isContainerAuthenticated(): boolean
            +login(HttpServletRequest): boolean
            +login(WikiSession, HttpServletRequest, String, String): boolean
            +logout(HttpServletRequest): void
            +allowsCookieAssertions(): boolean
            +allowsCookieAuthentication(): boolean
            {static} +isRolePrincipal(Principal): boolean
            {static} +isUserPrincipal(Principal): boolean
            #doJAASLogin(Class<?>, CallbackHandler, Map<String, String>): Set<Principal>
            {static} #findConfigFile(WikiEngine, String): URL
            #getLoginPrincipal(Set<Principal>): Principal
            +addWikiEventListener(WikiEventListener): void
            +removeWikiEventListener(WikiEventListener): void
            #fireEvent(int, Principal, Object): void
        }

        class AuthorizationManager [[AuthorizationManager.html]] {
            {static} +DEFAULT_AUTHORIZER: String
            {static} #POLICY: String
            {static} #DEFAULT_POLICY: String
            {static} +PROP_AUTHORIZER: String
            +checkPermission(WikiSession, Permission): boolean
            +isUserInRole(WikiSession, Principal): boolean
            #hasRoleOrPrincipal(WikiSession, Principal): boolean
            +hasAccess(WikiContext, HttpServletResponse): boolean
            +hasAccess(WikiContext, HttpServletResponse, boolean): boolean
            +initialize(WikiEngine, Properties): void
            #allowedByLocalPolicy(Principal[], Permission): boolean
            #checkStaticPermission(WikiSession, Permission): boolean
            +resolvePrincipal(String): Principal
            +addWikiEventListener(WikiEventListener): void
            +removeWikiEventListener(WikiEventListener): void
            #fireEvent(int, Principal, Object): void
        }

        WikiSecurityException <|-- NoSuchPrincipalException

        class org.apache.wiki.api.exceptions.WikiException
        org.apache.wiki.api.exceptions.WikiException <|-- WikiSecurityException

        interface java.util.Comparator<T> {
            {abstract} +compare(T, T): int
        }
        java.util.Comparator <|.. PrincipalComparator

        interface java.io.Serializable
        java.io.Serializable <|.. PrincipalComparator

        interface java.security.Principal {
            {abstract} +getName(): String
        }
        java.security.Principal <|.. GroupPrincipal

        java.security.Principal <|.. WikiPrincipal

        interface java.lang.Comparable<T> {
            {abstract} +compareTo(T): int
        }
        java.lang.Comparable <|.. WikiPrincipal

        java.io.Serializable <|.. WikiPrincipal

        interface javax.servlet.http.HttpSessionListener {
            {abstract} +sessionCreated(HttpSessionEvent): void
            {abstract} +sessionDestroyed(HttpSessionEvent): void
        }
        javax.servlet.http.HttpSessionListener <|.. SessionMonitor

        abstract class org.apache.wiki.auth.user.AbstractUserDatabase {
            {abstract} +findByEmail(String): UserProfile
            {abstract} +findByFullName(String): UserProfile
            {abstract} +findByLoginName(String): UserProfile
            {abstract} +findByWikiName(String): UserProfile
            {abstract} +initialize(WikiEngine, Properties): void
            {abstract} +save(UserProfile): void
        }
        org.apache.wiki.auth.user.AbstractUserDatabase <|-- org.apache.wiki.auth.UserManager.DummyUserDatabase

        UserManager +-- org.apache.wiki.auth.UserManager.DummyUserDatabase

        interface org.apache.wiki.ajax.WikiAjaxServlet {
            {abstract} +getServletMapping(): String
            {abstract} +service(HttpServletRequest, HttpServletResponse, String, List<String>): void
        }
        org.apache.wiki.ajax.WikiAjaxServlet <|.. org.apache.wiki.auth.UserManager.JSONUserModule

        UserManager +-- org.apache.wiki.auth.UserManager.JSONUserModule

        Authorizer --> "*" java.security.Principal: roles

        org.apache.wiki.auth.UserManager.DummyUserDatabase --> "*" java.security.Principal: wikiNames

        AuthorizationManager --> Authorizer: authorizer

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
