@startuml

    class UserManager [[UserManager.html]] {
        {static} +JSON_USERS: String
        +initialize(WikiEngine, Properties): void
        +getUserDatabase(): UserDatabase
        +getUserProfile(WikiSession): UserProfile
        +setUserProfile(WikiSession, UserProfile): void
        +startUserProfileCreationWorkflow(WikiSession, UserProfile): void
        +parseProfile(WikiContext): UserProfile
        +validateProfile(WikiContext, UserProfile): void
        +listWikiNames(): Principal[]
        +addWikiEventListener(WikiEventListener): void
        +removeWikiEventListener(WikiEventListener): void
        #fireEvent(int, WikiSession, Object): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
