@startuml

    interface AttachmentManager [[AttachmentManager.html]] {
        {static} +PROP_PROVIDER: String
        {static} +PROP_MAXSIZE: String
        {static} +PROP_ALLOWEDEXTENSIONS: String
        {static} +PROP_FORBIDDENEXTENSIONS: String
        {static} +PROP_FORCEDOWNLOAD: String
        {static} +CACHE_NAME: String
        {static} +DEFAULT_CACHECAPACITY: int
        +getAttachmentInfo(String): Attachment
        +getAttachmentInfo(String, int): Attachment
        +getAttachmentInfo(Context, String): Attachment
        +hasAttachments(Page): boolean
        +getAttachmentStream(Attachment): InputStream
        +storeAttachment(Attachment, File): void
        {static} +validateFileName(String): String
        {abstract} +attachmentsEnabled(): boolean
        {abstract} +getAttachmentInfo(Context, String, int): Attachment
        {abstract} +getAttachmentInfoName(Context, String): String
        {abstract} +listAttachments(Page): List<Attachment>
        {abstract} +forceDownload(String): boolean
        {abstract} +getAttachmentStream(WikiContext, Attachment): InputStream
        {abstract} +storeDynamicAttachment(WikiContext, DynamicAttachment): void
        {abstract} +getDynamicAttachment(String): DynamicAttachment
        {abstract} +storeAttachment(Attachment, InputStream): void
        {abstract} +getVersionHistory(String): List<Attachment>
        {abstract} +getAllAttachments(): Collection<Attachment>
        {abstract} +getCurrentProvider(): AttachmentProvider
        {abstract} +deleteVersion(Attachment): void
        {abstract} +deleteAttachment(Attachment): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
