@startuml

    class AttachmentServlet [[AttachmentServlet.html]] {
        {static} #DEFAULT_EXPIRY: long
        +init(ServletConfig): void
        #doOptions(HttpServletRequest, HttpServletResponse): void
        +doGet(HttpServletRequest, HttpServletResponse): void
        +doPost(HttpServletRequest, HttpServletResponse): void
        #upload(HttpServletRequest): String
        #executeUpload(WikiContext, InputStream, String, String, String, String, long): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
