@startuml

    class DefaultAttachmentManager [[DefaultAttachmentManager.html]] {
        +DefaultAttachmentManager(Engine, Properties)
        +attachmentsEnabled(): boolean
        +getAttachmentInfoName(WikiContext, String): String
        +getAttachmentInfo(WikiContext, String, int): Attachment
        +listAttachments(WikiPage): List<Attachment>
        +forceDownload(String): boolean
        +getAttachmentStream(WikiContext, Attachment): InputStream
        +storeDynamicAttachment(WikiContext, DynamicAttachment): void
        +getDynamicAttachment(String): DynamicAttachment
        +storeAttachment(Attachment, InputStream): void
        +getVersionHistory(String): List<Attachment>
        +getAllAttachments(): Collection<Attachment>
        +getCurrentProvider(): WikiAttachmentProvider
        +deleteVersion(Attachment): void
        +deleteAttachment(Attachment): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
