@startuml

    namespace org.apache.wiki.attachment {

        class DefaultAttachmentManager [[DefaultAttachmentManager.html]] {
            +DefaultAttachmentManager(Engine, Properties)
            +attachmentsEnabled(): boolean
            +getAttachmentInfoName(WikiContext, String): String
            +getAttachmentInfo(WikiContext, String, int): Attachment
            +listAttachments(WikiPage): List<Attachment>
            +forceDownload(String): boolean
            +getAttachmentStream(WikiContext, Attachment): InputStream
            +storeDynamicAttachment(WikiContext, DynamicAttachment): void
            +getDynamicAttachment(String): DynamicAttachment
            +storeAttachment(Attachment, InputStream): void
            +getVersionHistory(String): List<Attachment>
            +getCurrentProvider(): WikiAttachmentProvider
            +deleteVersion(Attachment): void
            +deleteAttachment(Attachment): void
        }

        interface AttachmentManager [[AttachmentManager.html]] {
            {static} +PROP_PROVIDER: String
            {static} +PROP_MAXSIZE: String
            {static} +PROP_ALLOWEDEXTENSIONS: String
            {static} +PROP_FORBIDDENEXTENSIONS: String
            {static} +PROP_FORCEDOWNLOAD: String
            {static} +CACHE_NAME: String
            {static} +DEFAULT_CACHECAPACITY: int
            +getAttachmentInfo(String): Attachment
            +getAttachmentInfo(String, int): Attachment
            +getAttachmentInfo(WikiContext, String): Attachment
            +hasAttachments(WikiPage): boolean
            +getAttachmentStream(Attachment): InputStream
            +storeAttachment(Attachment, File): void
            {static} +validateFileName(String): String
            {abstract} +attachmentsEnabled(): boolean
            {abstract} +getAttachmentInfo(WikiContext, String, int): Attachment
            {abstract} +getAttachmentInfoName(WikiContext, String): String
            {abstract} +listAttachments(WikiPage): List<Attachment>
            {abstract} +forceDownload(String): boolean
            {abstract} +getAttachmentStream(WikiContext, Attachment): InputStream
            {abstract} +storeDynamicAttachment(WikiContext, DynamicAttachment): void
            {abstract} +getDynamicAttachment(String): DynamicAttachment
            {abstract} +storeAttachment(Attachment, InputStream): void
            {abstract} +getVersionHistory(String): List<Attachment>
            {abstract} +getCurrentProvider(): WikiAttachmentProvider
            {abstract} +deleteVersion(Attachment): void
            {abstract} +deleteAttachment(Attachment): void
        }

        class DynamicAttachment [[DynamicAttachment.html]] {
            +DynamicAttachment(Engine, String, String, DynamicAttachmentProvider)
        }

        class AttachmentServlet [[AttachmentServlet.html]] {
            {static} #DEFAULT_EXPIRY: long
            +init(ServletConfig): void
            #doOptions(HttpServletRequest, HttpServletResponse): void
            +doGet(HttpServletRequest, HttpServletResponse): void
            +doPost(HttpServletRequest, HttpServletResponse): void
            #upload(HttpServletRequest): String
            #executeUpload(WikiContext, InputStream, String, String, String, String, long): boolean
        }

        class Attachment [[Attachment.html]] {
            +Attachment(Engine, String, String)
            +getFileName(): String
            +setFileName(String): void
            +getParentName(): String
            +isCacheable(): boolean
            +setCacheable(boolean): void
        }

        interface DynamicAttachmentProvider [[DynamicAttachmentProvider.html]] {
            {abstract} +getAttachmentData(WikiContext, Attachment): InputStream
        }

        AttachmentManager <|.. DefaultAttachmentManager

        Attachment <|-- DynamicAttachment

        abstract class javax.servlet.http.HttpServlet
        javax.servlet.http.HttpServlet <|-- AttachmentServlet

        class org.apache.wiki.WikiPage
        org.apache.wiki.WikiPage <|-- Attachment

        DefaultAttachmentManager --> "*" Attachment: allAttachments

        AttachmentManager --> "*" Attachment: allAttachments

        DynamicAttachment --> DynamicAttachmentProvider: provider

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
