@startuml

    class PageViewPlugin.PageViewManager [[PageViewPlugin.PageViewManager.html]] {
        +initialize(WikiEngine): void
        +actionPerformed(WikiEvent): void
        +execute(WikiContext, Map<String, String>): String
        #getCount(Object): int
        #storeCounters(): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
