@startuml

    class InsertPage [[InsertPage.html]] {
        {static} +PARAM_PAGENAME: String
        {static} +PARAM_STYLE: String
        {static} +PARAM_MAXLENGTH: String
        {static} +PARAM_CLASS: String
        {static} +PARAM_SHOW: String
        {static} +PARAM_SECTION: String
        {static} +PARAM_DEFAULT: String
        {static} +ATTR_RECURSE: String
        +execute(Context, Map<String, String>): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
