@startuml

    class ReferredPagesPlugin [[ReferredPagesPlugin.html]] {
        {static} +PARAM_ROOT: String
        {static} +PARAM_DEPTH: String
        {static} +PARAM_TYPE: String
        {static} +PARAM_INCLUDE: String
        {static} +PARAM_EXCLUDE: String
        {static} +PARAM_FORMAT: String
        {static} +MIN_DEPTH: int
        {static} +MAX_DEPTH: int
        +execute(Context, Map<String, String>): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
