@startuml

    class DiffProvider.NullDiffProvider [[DiffProvider.NullDiffProvider.html]] {
        +makeDiffHtml(Context, String, String): String
        +initialize(Engine, Properties): void
        +getProviderInfo(): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
