@startuml

    interface DifferenceManager [[DifferenceManager.html]] {
        {static} +PROP_DIFF_PROVIDER: String
        {abstract} +makeDiff(Context, String, String): String
        {abstract} +getDiff(Context, int, int): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
