@startuml

    namespace org.apache.wiki.references {

        interface ReferenceManager [[ReferenceManager.html]] {
            {abstract} +initialize(Collection<Page>): void
            {abstract} +scanWikiLinks(Page, String): Collection<String>
            {abstract} +pageRemoved(Page): void
            {abstract} +updateReferences(Page): void
            {abstract} +updateReferences(String, Collection<String>): void
            {abstract} +clearPageEntries(String): void
            {abstract} +findUnreferenced(): Collection<String>
            {abstract} +findUncreated(): Collection<String>
            {abstract} +findReferrers(String): Set<String>
            {abstract} +findReferredBy(String): Set<String>
            {abstract} +findRefersTo(String): Collection<String>
            {abstract} +findCreated(): Set<String>
        }

        class DefaultReferenceManager [[DefaultReferenceManager.html]] {
            +DefaultReferenceManager(Engine)
            +initialize(Collection<Page>): void
            +postSave(Context, String): void
            +scanWikiLinks(Page, String): Collection<String>
            +pageRemoved(Page): void
            +updateReferences(Page): void
            +updateReferences(String, Collection<String>): void
            #getRefersTo(): Map<String, Collection<String>>
            #getReferredBy(): Map<String, Set<String>>
            +clearPageEntries(String): void
            +findUnreferenced(): Collection<String>
            +findUncreated(): Collection<String>
            +findReferrers(String): Set<String>
            +findReferredBy(String): Set<String>
            +findRefersTo(String): Collection<String>
            +deepHashCode(): int
            +findCreated(): Set<String>
            +actionPerformed(WikiEvent): void
        }

        interface org.apache.wiki.api.filters.PageFilter {
            {abstract} +initialize(Engine, Properties): void
        }
        org.apache.wiki.api.filters.PageFilter <|.. ReferenceManager

        interface org.apache.wiki.modules.InternalModule
        org.apache.wiki.modules.InternalModule <|.. ReferenceManager

        interface org.apache.wiki.event.WikiEventListener {
            {abstract} +actionPerformed(WikiEvent): void
        }
        org.apache.wiki.event.WikiEventListener <|.. ReferenceManager

        class org.apache.wiki.api.filters.BasePageFilter
        org.apache.wiki.api.filters.BasePageFilter <|-- DefaultReferenceManager

        ReferenceManager <|.. DefaultReferenceManager

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
