@startuml

    interface CommandResolver [[CommandResolver.html]] {
        {static} +PROP_SPECIALPAGE: String
        {static} +findCommand(String): Command
        {abstract} +findCommand(HttpServletRequest, String): Command
        {abstract} +getFinalPageName(String): String
        {abstract} +getSpecialPageReference(String): String
        {abstract} +extractPageFromParameter(String, HttpServletRequest): String
        {abstract} +resolvePage(HttpServletRequest, String): Page
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
