@startuml

    class DefaultTemplateManager [[DefaultTemplateManager.html]] {
        +DefaultTemplateManager(Engine, Properties)
        +templateExists(String): boolean
        +findJSP(PageContext, String): String
        +findJSP(PageContext, String, String): String
        +findResource(Context, String, String): String
        +listSkins(PageContext, String): Set<String>
        +listTimeFormats(PageContext): Map<String, String>
        +modules(): Collection<WikiModuleInfo>
        +getModuleInfo(String): WikiModuleInfo
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
