@startuml

    class PageCommand [[PageCommand.html]] {
        {static} +ATTACH: Command
        {static} +COMMENT: Command
        {static} +CONFLICT: Command
        {static} +DELETE: Command
        {static} +DIFF: Command
        {static} +EDIT: Command
        {static} +INFO: Command
        {static} +PREVIEW: Command
        {static} +RENAME: Command
        {static} +RSS: Command
        {static} +UPLOAD: Command
        {static} +VIEW: Command
        {static} +NONE: Command
        {static} +OTHER: Command
        +targetedCommand(Object): Command
        +getName(): String
        +requiredPermission(): Permission
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
