@startuml

    interface PageManager [[PageManager.html]] {
        {static} +PROP_PAGEPROVIDER: String
        {static} +PROP_USECACHE: String
        {static} +PROP_LOCKEXPIRY: String
        {abstract} +getProvider(): WikiPageProvider
        {abstract} +getAllPages(): Collection<WikiPage>
        {abstract} +getPageText(String, int): String
        {abstract} +getEngine(): WikiEngine
        {abstract} +putPageText(WikiPage, String): void
        {abstract} +lockPage(WikiPage, String): PageLock
        {abstract} +unlockPage(PageLock): void
        {abstract} +getCurrentLock(WikiPage): PageLock
        {abstract} +getActiveLocks(): List<PageLock>
        {abstract} +getPageInfo(String, int): WikiPage
        {abstract} +getVersionHistory(String): List<WikiPage>
        {abstract} +getProviderDescription(): String
        {abstract} +getTotalPageCount(): int
        {abstract} +pageExists(String): boolean
        {abstract} +pageExists(String, int): boolean
        {abstract} +deleteVersion(WikiPage): void
        {abstract} +deletePage(WikiPage): void
        {abstract} +actionPerformed(WikiEvent): void
        {abstract} +getPageSorter(): PageSorter
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
