@startuml

    abstract class FormElement [[FormElement.html]] {
        {static} +HANDLERPARAM_PREFIX: String
        {static} +FORM_VALUES_CARRIER: String
        {static} +HIDE_SUCCESS: String
        {static} +PARAM_SUBMITHANDLER: String
        {static} +PARAM_ELEMENT: String
        {static} +PARAM_HANDLER: String
        {static} +PARAM_FORM: String
        {static} +PARAM_INPUTNAME: String
        {static} +PARAM_VALUE: String
        {static} +PARAM_HIDEFORM: String
        {static} +PARAM_POPULATE: String
        {static} +PARAM_FORMNAMEHIDDEN: String
        #storeFormInfo(WikiContext, FormInfo): void
        #getFormInfo(WikiContext): FormInfo
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
