@startuml

    class CachingAttachmentProvider [[CachingAttachmentProvider.html]] {
        {static} +m_capacity: int
        {static} +ATTCOLLCACHE_NAME: String
        {static} +ATTCACHE_NAME: String
        {static} +DIR_EXTENSION: String
        {static} +PROP_STORAGEDIR: String
        +initialize(WikiEngine, Properties): void
        +putAttachmentData(Attachment, InputStream): void
        +getAttachmentData(Attachment): InputStream
        +listAttachments(WikiPage): List<Attachment>
        +findAttachments(QueryItem[]): Collection<Attachment>
        +listAllChanged(Date): List<Attachment>
        +getAttachmentInfo(WikiPage, String, int): Attachment
        +getVersionHistory(Attachment): List<Attachment>
        +deleteVersion(Attachment): void
        +deleteAttachment(Attachment): void
        +getProviderInfo(): String
        +getRealProvider(): WikiAttachmentProvider
        +moveAttachmentsForPage(String, String): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
