@startuml

    class WikiI18nException [[WikiI18nException.html]] {
        #args: Object[]
        +WikiI18nException(String, Object[])
        +getArgs(): Object[]
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
