@startuml

    namespace org.apache.wiki.tasks {

        interface TasksManager [[TasksManager.html]] {
            {static} +WIKIPAGE_PRESAVE_TASK_MESSAGE_KEY: String
            {static} +WIKIPAGE_SAVE_TASK_MESSAGE_KEY: String
            {static} +USER_PROFILE_SAVE_TASK_MESSAGE_KEY: String
            {abstract} +buildPreSaveWikiPageTask(String): Step
            {abstract} +buildSaveWikiPageTask(): Step
            {abstract} +buildSaveUserProfileTask(Locale): Step
        }

        class DefaultTasksManager [[DefaultTasksManager.html]] {
            +buildPreSaveWikiPageTask(String): Step
            +buildSaveWikiPageTask(): Step
            +buildSaveUserProfileTask(Locale): Step
        }

        TasksManager <|.. DefaultTasksManager

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
