@startuml

    class AllPermissionCollection [[AllPermissionCollection.html]] {
        #m_permissions: Hashtable<Permission, Permission>
        +add(Permission): void
        +elements(): Enumeration<Permission>
        +implies(Permission): boolean
        +isReadOnly(): boolean
        +setReadOnly(): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
