@startuml

    class GroupPermission [[GroupPermission.html]] {
        {static} +MEMBER_TOKEN: String
        {static} +DELETE_ACTION: String
        {static} +EDIT_ACTION: String
        {static} +VIEW_ACTION: String
        {static} #DELETE_MASK: int
        {static} #EDIT_MASK: int
        {static} #VIEW_MASK: int
        {static} +DELETE: GroupPermission
        {static} +EDIT: GroupPermission
        {static} +VIEW: GroupPermission
        #GroupPermission()
        +GroupPermission(String, String)
        +getActions(): String
        +getGroup(): String
        +getWiki(): String
        +implies(Permission): boolean
        {static} #impliedMask(int): int
        {static} #createMask(String): int
        #impliesMember(Permission): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
