@startuml

    interface ReferenceManager [[ReferenceManager.html]] {
        {abstract} +initialize(Collection<Page>): void
        {abstract} +scanWikiLinks(Page, String): Collection<String>
        {abstract} +pageRemoved(Page): void
        {abstract} +updateReferences(Page): void
        {abstract} +updateReferences(String, Collection<String>): void
        {abstract} +clearPageEntries(String): void
        {abstract} +findUnreferenced(): Collection<String>
        {abstract} +findUncreated(): Collection<String>
        {abstract} +findReferrers(String): Set<String>
        {abstract} +findReferredBy(String): Set<String>
        {abstract} +findRefersTo(String): Collection<String>
        {abstract} +findCreated(): Set<String>
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
