@startuml

    interface PageManager [[PageManager.html]] {
        {static} +PROP_PAGEPROVIDER: String
        {static} +PROP_USECACHE: String
        {static} +PROP_LOCKEXPIRY: String
        +getPureText(Page): String
        +getText(String): String
        +getText(Page): String
        +pageExists(Page): boolean
        +wikiPageExists(Page): boolean
        {abstract} +getProvider(): PageProvider
        {abstract} +getAllPages(): Collection<Page>
        {abstract} +getPageText(String, int): String
        {abstract} +getPureText(String, int): String
        {abstract} +getText(String, int): String
        {abstract} +saveText(Context, String): void
        {abstract} +putPageText(Page, String): void
        {abstract} +lockPage(Page, String): PageLock
        {abstract} +unlockPage(PageLock): void
        {abstract} +getCurrentLock(Page): PageLock
        {abstract} +getActiveLocks(): List<PageLock>
        {abstract} +getPage(String): Page
        {abstract} +getPage(String, int): Page
        {abstract} +getPageInfo(String, int): Page
        {abstract} +getVersionHistory(String): List<T>
        {abstract} +getCurrentProvider(): String
        {abstract} +getProviderDescription(): String
        {abstract} +getTotalPageCount(): int
        {abstract} +getRecentChanges(): Set<Page>
        {abstract} +pageExists(String): boolean
        {abstract} +pageExists(String, int): boolean
        {abstract} +wikiPageExists(String): boolean
        {abstract} +wikiPageExists(String, int): boolean
        {abstract} +deleteVersion(Page): void
        {abstract} +deletePage(String): void
        {abstract} +deletePage(Page): void
        {abstract} +getPageSorter(): PageSorter
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
