@startuml

    abstract class WikiEvent [[WikiEvent.html]] {
        {static} +ERROR: int
        {static} +UNDEFINED: int
        +WikiEvent(Object, int)
        +WikiEvent(Object, int, Object[])
        +getSrc(): T
        +getWhen(): long
        #setType(int): void
        +getType(): int
        +getArgs(): Object[]
        +getArg(int, Class<T>): T
        +getTypeDescription(): String
        {static} +isValidType(int): boolean
        +eventName(): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
