@startuml

    abstract class WikiBodyTag [[WikiBodyTag.html]] {
        #m_wikiContext: WikiContext
        +doStartTag(): int
        +doCatch(Throwable): void
        +doFinally(): void
        {abstract} +doWikiStartTag(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
