@startuml

    enum HumanComparator.CharType [[HumanComparator.CharType.html]] {
        {static} +TYPE_OTHER
        {static} +TYPE_DIGIT
        {static} +TYPE_LETTER
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
