@startuml

    namespace org.apache.wiki.tasks.pages {

        class SaveWikiPageTask [[SaveWikiPageTask.html]] {
            +execute(): Outcome
        }

        class PreSaveWikiPageTask [[PreSaveWikiPageTask.html]] {
            +PreSaveWikiPageTask(WikiContext, String)
            +execute(): Outcome
        }

        abstract class org.apache.wiki.workflow.Task
        org.apache.wiki.workflow.Task <|-- SaveWikiPageTask

        org.apache.wiki.workflow.Task <|-- PreSaveWikiPageTask

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
