@startuml

    namespace org.apache.wiki.markdown.extensions.jspwikilinks.attributeprovider {

        class WysiwygEditingAttributeProviderState [[WysiwygEditingAttributeProviderState.html]] {
            +WysiwygEditingAttributeProviderState(WikiContext)
            +setAttributes(Attributes, JSPWikiLink): void
        }

        interface NodeAttributeProviderState<T> [[NodeAttributeProviderState.html]] {
            {abstract} +setAttributes(Attributes, T): void
        }

        class LocalReadLinkAttributeProviderState [[LocalReadLinkAttributeProviderState.html]] {
            +LocalReadLinkAttributeProviderState(WikiContext)
            +setAttributes(Attributes, JSPWikiLink): void
        }

        class LocalEditLinkAttributeProviderState [[LocalEditLinkAttributeProviderState.html]] {
            +LocalEditLinkAttributeProviderState(WikiContext, String)
            +setAttributes(Attributes, JSPWikiLink): void
        }

        class JSPWikiLinkAttributeProviderFactory [[JSPWikiLinkAttributeProviderFactory.html]] {
            +JSPWikiLinkAttributeProviderFactory(WikiContext)
            +apply(LinkResolverContext): AttributeProvider
        }

        class LocalFootnoteRefLinkAttributeProviderState [[LocalFootnoteRefLinkAttributeProviderState.html]] {
            +LocalFootnoteRefLinkAttributeProviderState(WikiContext)
            +setAttributes(Attributes, JSPWikiLink): void
        }

        class ImageLinkAttributeProviderState [[ImageLinkAttributeProviderState.html]] {
            +ImageLinkAttributeProviderState(WikiContext, String, boolean)
            +setAttributes(Attributes, JSPWikiLink): void
        }

        class LocalLinkAttributeProviderState [[LocalLinkAttributeProviderState.html]] {
            +LocalLinkAttributeProviderState(WikiContext, boolean)
            +setAttributes(Attributes, JSPWikiLink): void
        }

        class InterWikiLinkAttributeProviderState [[InterWikiLinkAttributeProviderState.html]] {
            +InterWikiLinkAttributeProviderState(WikiContext, boolean)
            +setAttributes(Attributes, JSPWikiLink): void
        }

        class ExternalLinkAttributeProviderState [[ExternalLinkAttributeProviderState.html]] {
            +ExternalLinkAttributeProviderState(WikiContext, boolean)
            +setAttributes(Attributes, JSPWikiLink): void
        }

        class LocalFootnoteLinkAttributeProviderState [[LocalFootnoteLinkAttributeProviderState.html]] {
            +LocalFootnoteLinkAttributeProviderState(WikiContext)
            +setAttributes(Attributes, JSPWikiLink): void
        }

        class JSPWikiLinkAttributeProvider [[JSPWikiLinkAttributeProvider.html]] {
            #wikiContext: WikiContext
            #linkOperations: LinkParsingOperations
            +JSPWikiLinkAttributeProvider(WikiContext)
            +setAttributes(Node, AttributablePart, Attributes): void
        }

        NodeAttributeProviderState <|.. WysiwygEditingAttributeProviderState

        NodeAttributeProviderState <|.. LocalReadLinkAttributeProviderState

        NodeAttributeProviderState <|.. LocalEditLinkAttributeProviderState

        abstract class com.vladsch.flexmark.html.IndependentAttributeProviderFactory
        com.vladsch.flexmark.html.IndependentAttributeProviderFactory <|-- JSPWikiLinkAttributeProviderFactory

        NodeAttributeProviderState <|.. LocalFootnoteRefLinkAttributeProviderState

        NodeAttributeProviderState <|.. ImageLinkAttributeProviderState

        NodeAttributeProviderState <|.. LocalLinkAttributeProviderState

        NodeAttributeProviderState <|.. InterWikiLinkAttributeProviderState

        NodeAttributeProviderState <|.. ExternalLinkAttributeProviderState

        NodeAttributeProviderState <|.. LocalFootnoteLinkAttributeProviderState

        interface com.vladsch.flexmark.html.AttributeProvider {
            {abstract} +setAttributes(Node, AttributablePart, Attributes): void
        }
        com.vladsch.flexmark.html.AttributeProvider <|.. JSPWikiLinkAttributeProvider

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
