@startuml

    abstract class AbstractReferralPlugin [[AbstractReferralPlugin.html]] {
        {static} +ALL_ITEMS: int
        {static} +PARAM_MAXWIDTH: String
        {static} +PARAM_SEPARATOR: String
        {static} +PARAM_AFTER: String
        {static} +PARAM_BEFORE: String
        {static} +PARAM_EXCLUDE: String
        {static} +PARAM_INCLUDE: String
        {static} +PARAM_SHOW: String
        {static} +PARAM_SHOW_VALUE_PAGES: String
        {static} +PARAM_SHOW_VALUE_COUNT: String
        {static} +PARAM_LASTMODIFIED: String
        {static} #PARAM_SORTORDER: String
        {static} #PARAM_SORTORDER_HUMAN: String
        {static} #PARAM_SORTORDER_JAVA: String
        {static} #PARAM_SORTORDER_LOCALE: String
        #m_maxwidth: int
        #m_before: String
        #m_separator: String
        #m_after: String
        #m_exclude: Pattern[]
        #m_include: Pattern[]
        #m_sorter: PageSorter
        #m_show: String
        #m_lastModified: boolean
        #m_dateLastModified: Date
        #m_dateFormat: SimpleDateFormat
        #m_engine: Engine
        +initialize(WikiContext, Map<String, String>): void
        #filterWikiPageCollection(Collection<WikiPage>): List<WikiPage>
        #filterCollection(Collection<String>): List<String>
        #filterAndSortCollection(Collection<String>): List<String>
        #wikitizeCollection(Collection<String>, String, int): String
        #makeHTML(WikiContext, String): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
