@startuml

    class Counter [[Counter.html]] {
        {static} +PARAM_NAME: String
        {static} +PARAM_INCREMENT: String
        {static} +PARAM_SHOW_RESULT: String
        {static} +PARAM_START: String
        {static} +DEFAULT_NAME: String
        +execute(WikiContext, Map<String, String>): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
