@startuml

    class DefaultPluginManager [[DefaultPluginManager.html]] {
        +DefaultPluginManager(Engine, Properties)
        +enablePlugins(boolean): void
        +pluginsEnabled(): boolean
        +getPluginPattern(): Pattern
        +getPluginSearchPath(): String
        +execute(Context, String, Map<String, String>): String
        +parseArgs(String): Map<String, String>
        +execute(Context, String): String
        +modules(): Collection<WikiModuleInfo>
        +getModuleInfo(String): DefaultPluginManager.WikiPluginInfo
        +newWikiPlugin(String, ResourceBundle): Plugin
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
