@startuml

    class DefaultPluginManager.WikiPluginInfo [[DefaultPluginManager.WikiPluginInfo.html]] {
        {static} #newInstance(String, Element, List<String>, List<String>): DefaultPluginManager.WikiPluginInfo
        #initializePlugin(DefaultPluginManager.WikiPluginInfo, Engine, List<String>, List<String>): void
        #initializeFromXML(Element): void
        {static} #newInstance(Class<?>): DefaultPluginManager.WikiPluginInfo
        +getClassName(): String
        +getAlias(): String
        +getAjaxAlias(): String
        +newPluginInstance(List<String>, List<String>): WikiPlugin
        +getIncludeText(String): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
