@startuml

    class Denounce [[Denounce.html]] {
        {static} +PARAM_LINK: String
        {static} +PARAM_TEXT: String
        +execute(WikiContext, Map<String, String>): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
