@startuml

    class Image [[Image.html]] {
        {static} +PARAM_SRC: String
        {static} +PARAM_ALIGN: String
        {static} +PARAM_HEIGHT: String
        {static} +PARAM_WIDTH: String
        {static} +PARAM_ALT: String
        {static} +PARAM_CAPTION: String
        {static} +PARAM_LINK: String
        {static} +PARAM_TARGET: String
        {static} +PARAM_STYLE: String
        {static} +PARAM_CLASS: String
        {static} +PARAM_BORDER: String
        {static} +PARAM_TITLE: String
        +execute(Context, Map<String, String>): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
