@startuml

    namespace org.apache.wiki.plugin {

        class Note [[Note.html]] {
            {static} +PROP_NOTE_IMAGE: String
            {static} +DEFAULT_NOTE_IMAGE: String
            +execute(WikiContext, Map<String, String>): String
        }

        class Counter [[Counter.html]] {
            {static} +PARAM_NAME: String
            {static} +PARAM_INCREMENT: String
            {static} +PARAM_SHOW_RESULT: String
            {static} +PARAM_START: String
            {static} +DEFAULT_NAME: String
            +execute(WikiContext, Map<String, String>): String
        }

        class CurrentTimePlugin [[CurrentTimePlugin.html]] {
            +execute(WikiContext, Map<String, String>): String
        }

        class DefaultPluginManager [[DefaultPluginManager.html]] {
            +DefaultPluginManager(WikiEngine, Properties)
            +enablePlugins(boolean): void
            +pluginsEnabled(): boolean
            +getPluginPattern(): Pattern
            +getPluginSearchPath(): String
            +execute(WikiContext, String, Map<String, String>): String
            +parseArgs(String): Map<String, String>
            +execute(WikiContext, String): String
            +modules(): Collection<WikiModuleInfo>
            +getModuleInfo(String): DefaultPluginManager.WikiPluginInfo
            +newWikiPlugin(String, ResourceBundle): WikiPlugin
        }

        class org.apache.wiki.plugin.DefaultPluginManager.WikiPluginInfo [[DefaultPluginManager.WikiPluginInfo.html]] {
            {static} #newInstance(String, Element, List<String>, List<String>): DefaultPluginManager.WikiPluginInfo
            #initializePlugin(DefaultPluginManager.WikiPluginInfo, WikiEngine, List<String>, List<String>): void
            #initializeFromXML(Element): void
            {static} #newInstance(Class<?>): DefaultPluginManager.WikiPluginInfo
            +getClassName(): String
            +getAlias(): String
            +getAjaxAlias(): String
            +newPluginInstance(List<String>, List<String>): WikiPlugin
            +getIncludeText(String): String
        }

        class WeblogArchivePlugin [[WeblogArchivePlugin.html]] {
            {static} +PARAM_PAGE: String
            +execute(WikiContext, Map<String, String>): String
        }

        class IndexPlugin [[IndexPlugin.html]] {
            +execute(WikiContext, Map<String, String>): String
        }

        class WeblogEntryPlugin [[WeblogEntryPlugin.html]] {
            {static} +PARAM_ENTRYTEXT: String
            {static} +PARAM_BLOGNAME: String
            +getNewEntryPage(WikiEngine, String): String
            +execute(WikiContext, Map<String, String>): String
        }

        class UnusedPagesPlugin [[UnusedPagesPlugin.html]] {
            {static} +PARAM_EXCLUDEATTS: String
            +execute(WikiContext, Map<String, String>): String
        }

        class ReferringPagesPlugin [[ReferringPagesPlugin.html]] {
            {static} +PARAM_MAX: String
            {static} +PARAM_EXTRAS: String
            {static} +PARAM_PAGE: String
            +execute(WikiContext, Map<String, String>): String
        }

        class RecentChangesPlugin [[RecentChangesPlugin.html]] {
            {static} +PARAM_FORMAT: String
            {static} +PARAM_TIME_FORMAT: String
            {static} +PARAM_DATE_FORMAT: String
            {static} +DEFAULT_TIME_FORMAT: String
            {static} +DEFAULT_DATE_FORMAT: String
            +execute(WikiContext, Map<String, String>): String
        }

        class UndefinedPagesPlugin [[UndefinedPagesPlugin.html]] {
            +execute(WikiContext, Map<String, String>): String
        }

        class ReferredPagesPlugin [[ReferredPagesPlugin.html]] {
            {static} +PARAM_ROOT: String
            {static} +PARAM_DEPTH: String
            {static} +PARAM_TYPE: String
            {static} +PARAM_INCLUDE: String
            {static} +PARAM_EXCLUDE: String
            {static} +PARAM_FORMAT: String
            {static} +MIN_DEPTH: int
            {static} +MAX_DEPTH: int
            +execute(WikiContext, Map<String, String>): String
        }

        class TableOfContents [[TableOfContents.html]] {
            {static} +PARAM_TITLE: String
            {static} +PARAM_NUMBERED: String
            {static} +PARAM_START: String
            {static} +PARAM_PREFIX: String
            +headingAdded(WikiContext, Heading): void
            +execute(WikiContext, Map<String, String>): String
        }

        class WeblogPlugin [[WeblogPlugin.html]] {
            {static} +DEFAULT_DATEFORMAT: String
            {static} +PARAM_STARTDATE: String
            {static} +PARAM_ENTRYFORMAT: String
            {static} +PARAM_DAYS: String
            {static} +PARAM_ALLOWCOMMENTS: String
            {static} +PARAM_MAXENTRIES: String
            {static} +PARAM_PAGE: String
            {static} +PARAM_PREVIEW: String
            {static} +ATTR_ISWEBLOG: String
            {static} +makeEntryPage(String, String, String): String
            {static} +makeEntryPage(String): String
            {static} +makeEntryPage(String, String): String
            +execute(WikiContext, Map<String, String>): String
            +findBlogEntries(WikiEngine, String, Date, Date): List<WikiPage>
            +executeParser(PluginElement, WikiContext, Map<String, String>): void
        }

        class IfPlugin [[IfPlugin.html]] {
            {static} +PARAM_GROUP: String
            {static} +PARAM_USER: String
            {static} +PARAM_IP: String
            {static} +PARAM_PAGE: String
            {static} +PARAM_CONTAINS: String
            {static} +PARAM_VAR: String
            {static} +PARAM_IS: String
            {static} +PARAM_EXISTS: String
            +execute(WikiContext, Map<String, String>): String
            {static} +ifInclude(WikiContext, Map<String, String>): boolean
        }

        class BugReportHandler [[BugReportHandler.html]] {
            {static} +PARAM_TITLE: String
            {static} +PARAM_DESCRIPTION: String
            {static} +PARAM_VERSION: String
            {static} +PARAM_MAPPINGS: String
            {static} +PARAM_PAGE: String
            +execute(WikiContext, Map<String, String>): String
        }

        class ListLocksPlugin [[ListLocksPlugin.html]] {
            +execute(WikiContext, Map<String, String>): String
        }

        class Search [[Search.html]] {
            {static} +PARAM_QUERY: String
            {static} +PARAM_SET: String
            {static} +DEFAULT_SETNAME: String
            {static} +PARAM_MAX: String
            +execute(WikiContext, Map<String, String>): String
        }

        abstract class AbstractReferralPlugin [[AbstractReferralPlugin.html]] {
            {static} +ALL_ITEMS: int
            {static} +PARAM_MAXWIDTH: String
            {static} +PARAM_SEPARATOR: String
            {static} +PARAM_AFTER: String
            {static} +PARAM_BEFORE: String
            {static} +PARAM_EXCLUDE: String
            {static} +PARAM_INCLUDE: String
            {static} +PARAM_SHOW: String
            {static} +PARAM_SHOW_VALUE_PAGES: String
            {static} +PARAM_SHOW_VALUE_COUNT: String
            {static} +PARAM_LASTMODIFIED: String
            {static} #PARAM_SORTORDER: String
            {static} #PARAM_SORTORDER_HUMAN: String
            {static} #PARAM_SORTORDER_JAVA: String
            {static} #PARAM_SORTORDER_LOCALE: String
            #m_maxwidth: int
            #m_before: String
            #m_separator: String
            #m_after: String
            #m_exclude: Pattern[]
            #m_include: Pattern[]
            #m_sorter: PageSorter
            #m_show: String
            #m_lastModified: boolean
            #m_dateLastModified: Date
            #m_dateFormat: SimpleDateFormat
            #m_engine: WikiEngine
            +initialize(WikiContext, Map<String, String>): void
            #filterWikiPageCollection(Collection<WikiPage>): List<WikiPage>
            #filterCollection(Collection<String>): List<String>
            #filterAndSortCollection(Collection<String>): List<String>
            #wikitizeCollection(Collection<String>, String, int): String
            #makeHTML(WikiContext, String): String
        }

        class PageViewPlugin [[PageViewPlugin.html]] {
            +initialize(WikiEngine): void
            +execute(WikiContext, Map<String, String>): String
        }

        class org.apache.wiki.plugin.PageViewPlugin.PageViewManager [[PageViewPlugin.PageViewManager.html]] {
            +initialize(WikiEngine): void
            +actionPerformed(WikiEvent): void
            +execute(WikiContext, Map<String, String>): String
            #getCount(Object): int
            #storeCounters(): void
        }

        class InsertPage [[InsertPage.html]] {
            {static} +PARAM_PAGENAME: String
            {static} +PARAM_STYLE: String
            {static} +PARAM_MAXLENGTH: String
            {static} +PARAM_CLASS: String
            {static} +PARAM_SHOW: String
            {static} +PARAM_SECTION: String
            {static} +PARAM_DEFAULT: String
            {static} +ATTR_RECURSE: String
            +execute(WikiContext, Map<String, String>): String
        }

        class SessionsPlugin [[SessionsPlugin.html]] {
            {static} +PARAM_PROP: String
            +execute(WikiContext, Map<String, String>): String
        }

        class ReferringUndefinedPagesPlugin [[ReferringUndefinedPagesPlugin.html]] {
            {static} +PARAM_MAX: String
            {static} +PARAM_EXTRAS: String
            +execute(WikiContext, Map<String, String>): String
        }

        class Groups [[Groups.html]] {
            +execute(WikiContext, Map<String, String>): String
        }

        class Image [[Image.html]] {
            {static} +PARAM_SRC: String
            {static} +PARAM_ALIGN: String
            {static} +PARAM_HEIGHT: String
            {static} +PARAM_WIDTH: String
            {static} +PARAM_ALT: String
            {static} +PARAM_CAPTION: String
            {static} +PARAM_LINK: String
            {static} +PARAM_TARGET: String
            {static} +PARAM_STYLE: String
            {static} +PARAM_CLASS: String
            {static} +PARAM_BORDER: String
            {static} +PARAM_TITLE: String
            +execute(WikiContext, Map<String, String>): String
        }

        class Denounce [[Denounce.html]] {
            {static} +PARAM_LINK: String
            {static} +PARAM_TEXT: String
            +execute(WikiContext, Map<String, String>): String
        }

        class SampleAjaxPlugin [[SampleAjaxPlugin.html]] {
            +execute(WikiContext, Map<String, String>): String
            +getServletMapping(): String
            +service(HttpServletRequest, HttpServletResponse, String, List<String>): void
        }

        interface org.apache.wiki.api.plugin.WikiPlugin {
            {abstract} +execute(WikiContext, Map<String, String>): String
        }
        org.apache.wiki.api.plugin.WikiPlugin <|.. Note

        org.apache.wiki.api.plugin.WikiPlugin <|.. Counter

        org.apache.wiki.api.plugin.WikiPlugin <|.. CurrentTimePlugin

        abstract class org.apache.wiki.modules.ModuleManager {
            {abstract} +modules(): Collection<WikiModuleInfo>
            {abstract} +getModuleInfo(String): WikiModuleInfo
        }
        org.apache.wiki.modules.ModuleManager <|-- DefaultPluginManager

        interface org.apache.wiki.api.engine.PluginManager {
            {abstract} +enablePlugins(boolean): void
            {abstract} +pluginsEnabled(): boolean
            {abstract} +getPluginPattern(): Pattern
            {abstract} +getPluginSearchPath(): String
            {abstract} +execute(WikiContext, String, Map<String, String>): String
            {abstract} +parseArgs(String): Map<String, String>
            {abstract} +execute(WikiContext, String): String
            {abstract} +modules(): Collection<WikiModuleInfo>
            {abstract} +getModuleInfo(String): DefaultPluginManager.WikiPluginInfo
            {abstract} +newWikiPlugin(String, ResourceBundle): WikiPlugin
        }
        org.apache.wiki.api.engine.PluginManager <|.. DefaultPluginManager

        class org.apache.wiki.modules.WikiModuleInfo
        org.apache.wiki.modules.WikiModuleInfo <|-- org.apache.wiki.plugin.DefaultPluginManager.WikiPluginInfo

        DefaultPluginManager +-- org.apache.wiki.plugin.DefaultPluginManager.WikiPluginInfo

        org.apache.wiki.api.plugin.WikiPlugin <|.. WeblogArchivePlugin

        AbstractReferralPlugin <|-- IndexPlugin

        org.apache.wiki.api.plugin.WikiPlugin <|.. IndexPlugin

        org.apache.wiki.api.plugin.WikiPlugin <|.. WeblogEntryPlugin

        AbstractReferralPlugin <|-- UnusedPagesPlugin

        AbstractReferralPlugin <|-- ReferringPagesPlugin

        AbstractReferralPlugin <|-- RecentChangesPlugin

        org.apache.wiki.api.plugin.WikiPlugin <|.. RecentChangesPlugin

        AbstractReferralPlugin <|-- UndefinedPagesPlugin

        org.apache.wiki.api.plugin.WikiPlugin <|.. ReferredPagesPlugin

        org.apache.wiki.api.plugin.WikiPlugin <|.. TableOfContents

        interface org.apache.wiki.parser.HeadingListener {
            {abstract} +headingAdded(WikiContext, Heading): void
        }
        org.apache.wiki.parser.HeadingListener <|.. TableOfContents

        org.apache.wiki.api.plugin.WikiPlugin <|.. WeblogPlugin

        interface org.apache.wiki.api.plugin.ParserStagePlugin {
            {abstract} +executeParser(PluginElement, WikiContext, Map<String, String>): void
        }
        org.apache.wiki.api.plugin.ParserStagePlugin <|.. WeblogPlugin

        org.apache.wiki.api.plugin.WikiPlugin <|.. IfPlugin

        org.apache.wiki.api.plugin.WikiPlugin <|.. BugReportHandler

        org.apache.wiki.api.plugin.WikiPlugin <|.. ListLocksPlugin

        org.apache.wiki.api.plugin.WikiPlugin <|.. Search

        org.apache.wiki.api.plugin.WikiPlugin <|.. AbstractReferralPlugin

        AbstractReferralPlugin <|-- PageViewPlugin

        org.apache.wiki.api.plugin.WikiPlugin <|.. PageViewPlugin

        interface org.apache.wiki.api.plugin.InitializablePlugin {
            {abstract} +initialize(WikiEngine): void
        }
        org.apache.wiki.api.plugin.InitializablePlugin <|.. PageViewPlugin

        interface org.apache.wiki.event.WikiEventListener {
            {abstract} +actionPerformed(WikiEvent): void
        }
        org.apache.wiki.event.WikiEventListener <|.. org.apache.wiki.plugin.PageViewPlugin.PageViewManager

        PageViewPlugin +-- org.apache.wiki.plugin.PageViewPlugin.PageViewManager

        org.apache.wiki.api.plugin.WikiPlugin <|.. InsertPage

        org.apache.wiki.api.plugin.WikiPlugin <|.. SessionsPlugin

        AbstractReferralPlugin <|-- ReferringUndefinedPagesPlugin

        org.apache.wiki.api.plugin.WikiPlugin <|.. Groups

        org.apache.wiki.api.plugin.WikiPlugin <|.. Image

        org.apache.wiki.api.plugin.WikiPlugin <|.. Denounce

        org.apache.wiki.api.plugin.WikiPlugin <|.. SampleAjaxPlugin

        interface org.apache.wiki.ajax.WikiAjaxServlet {
            {abstract} +getServletMapping(): String
            {abstract} +service(HttpServletRequest, HttpServletResponse, String, List<String>): void
        }
        org.apache.wiki.ajax.WikiAjaxServlet <|.. SampleAjaxPlugin

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
