@startuml

    interface PluginManager [[PluginManager.html]] {
        {static} +PROP_EXTERNALJARS: String
        {static} +DEFAULT_PACKAGE: String
        {static} +PARAM_BODY: String
        {static} +PARAM_CMDLINE: String
        {static} +PARAM_BOUNDS: String
        {static} +PARAM_DEBUG: String
        {abstract} +enablePlugins(boolean): void
        {abstract} +pluginsEnabled(): boolean
        {abstract} +getPluginPattern(): Pattern
        {abstract} +execute(Context, String, Map<String, String>): String
        {abstract} +parseArgs(String): Map<String, String>
        {abstract} +execute(Context, String): String
        {abstract} +newWikiPlugin(String, ResourceBundle): Plugin
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
