@startuml

    class RecentChangesPlugin [[RecentChangesPlugin.html]] {
        {static} +PARAM_FORMAT: String
        {static} +PARAM_TIME_FORMAT: String
        {static} +PARAM_DATE_FORMAT: String
        {static} +DEFAULT_TIME_FORMAT: String
        {static} +DEFAULT_DATE_FORMAT: String
        +execute(Context, Map<String, String>): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
