@startuml

    class ReferringPagesPlugin [[ReferringPagesPlugin.html]] {
        {static} +PARAM_MAX: String
        {static} +PARAM_EXTRAS: String
        {static} +PARAM_PAGE: String
        +execute(Context, Map<String, String>): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
