@startuml

    class TableOfContents [[TableOfContents.html]] {
        {static} +PARAM_TITLE: String
        {static} +PARAM_NUMBERED: String
        {static} +PARAM_START: String
        {static} +PARAM_PREFIX: String
        +headingAdded(Context, Heading): void
        +execute(Context, Map<String, String>): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
