@startuml

    class WeblogPlugin [[WeblogPlugin.html]] {
        {static} +DEFAULT_DATEFORMAT: String
        {static} +PARAM_STARTDATE: String
        {static} +PARAM_ENTRYFORMAT: String
        {static} +PARAM_DAYS: String
        {static} +PARAM_ALLOWCOMMENTS: String
        {static} +PARAM_MAXENTRIES: String
        {static} +PARAM_PAGE: String
        {static} +PARAM_PREVIEW: String
        {static} +ATTR_ISWEBLOG: String
        {static} +makeEntryPage(String, String, String): String
        {static} +makeEntryPage(String): String
        {static} +makeEntryPage(String, String): String
        +execute(WikiContext, Map<String, String>): String
        +findBlogEntries(WikiEngine, String, Date, Date): List<WikiPage>
        +executeParser(PluginElement, WikiContext, Map<String, String>): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
