@startuml

    class Attachment [[Attachment.html]] {
        +Attachment(Engine, String, String)
        +getFileName(): String
        +setFileName(String): void
        +getParentName(): String
        +isCacheable(): boolean
        +setCacheable(boolean): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
