@startuml

    class DefaultAttachmentManager [[DefaultAttachmentManager.html]] {
        +DefaultAttachmentManager(Engine, Properties)
        +attachmentsEnabled(): boolean
        +getAttachmentInfoName(Context, String): String
        +getAttachmentInfo(Context, String, int): Attachment
        +listAttachments(Page): List<Attachment>
        +forceDownload(String): boolean
        +getAttachmentStream(Context, Attachment): InputStream
        +storeDynamicAttachment(Context, DynamicAttachment): void
        +getDynamicAttachment(String): DynamicAttachment
        +storeAttachment(Attachment, InputStream): void
        +getVersionHistory(String): List<Attachment>
        +getAllAttachments(): Collection<Attachment>
        +getCurrentProvider(): AttachmentProvider
        +deleteVersion(Attachment): void
        +deleteAttachment(Attachment): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
