@startuml

    class DefaultGroupManager [[DefaultGroupManager.html]] {
        #m_engine: Engine
        #m_groupListener: WikiEventListener
        +findRole(String): Principal
        +getGroup(String): Group
        +getGroupDatabase(): GroupDatabase
        +getRoles(): Principal[]
        +initialize(Engine, Properties): void
        +isUserInRole(Session, Principal): boolean
        +parseGroup(String, String, boolean): Group
        +removeGroup(String): void
        +setGroup(Session, Group): void
        +validateGroup(Context, Group): void
        +checkGroupName(Context, String): void
        #extractMembers(String): String[]
        +addWikiEventListener(WikiEventListener): void
        +removeWikiEventListener(WikiEventListener): void
        +actionPerformed(WikiEvent): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
