@startuml

    interface GroupDatabase [[GroupDatabase.html]] {
        {abstract} +delete(Group): void
        {abstract} +initialize(Engine, Properties): void
        {abstract} +save(Group, Principal): void
        {abstract} +groups(): Group[]
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
