@startuml

    class Role [[Role.html]] {
        {static} +ALL: Role
        {static} +ANONYMOUS: Role
        {static} +ASSERTED: Role
        {static} +AUTHENTICATED: Role
        #Role()
        +Role(String)
        {static} +isBuiltInRole(Role): boolean
        {static} +isReservedName(String): boolean
        +getName(): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
