@startuml

    class WebContainerAuthorizer [[WebContainerAuthorizer.html]] {
        #m_engine: Engine
        #m_containerRoles: Role[]
        #m_containerAuthorized: boolean
        +initialize(Engine, Properties): void
        +isUserInRole(HttpServletRequest, Principal): boolean
        +isUserInRole(Session, Principal): boolean
        +findRole(String): Principal
        +isConstrained(String, Role): boolean
        +isContainerAuthorized(): boolean
        +getRoles(): Principal[]
        #getRoles(Document): Role[]
        #getWebXml(): Document
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
