@startuml

    namespace org.apache.wiki.tasks.pages {

        class PreSaveWikiPageTask [[PreSaveWikiPageTask.html]] {
            +PreSaveWikiPageTask(String)
            +execute(Context): Outcome
        }

        class SaveWikiPageTask [[SaveWikiPageTask.html]] {
            +execute(Context): Outcome
        }

        abstract class org.apache.wiki.workflow.Task
        org.apache.wiki.workflow.Task <|-- PreSaveWikiPageTask

        org.apache.wiki.workflow.Task <|-- SaveWikiPageTask

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
