@startuml

    class JSPWikiLinkNodePostProcessor [[JSPWikiLinkNodePostProcessor.html]] {
        #m_context: WikiContext
        #linkOperations: LinkParsingOperations
        #m_useOutlinkImage: boolean
        #document: Document
        +JSPWikiLinkNodePostProcessor(WikiContext, Document, boolean, List<Pattern>)
        +process(NodeTracker, Node): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
