@startuml

    namespace org.apache.wiki.markdown.extensions.jspwikilinks.postprocessor {

        class LocalFootnoteLinkNodePostProcessorState [[LocalFootnoteLinkNodePostProcessorState.html]] {
            +LocalFootnoteLinkNodePostProcessorState(WikiContext)
            +process(NodeTracker, JSPWikiLink): void
        }

        interface NodePostProcessorState<T> [[NodePostProcessorState.html]] {
            {abstract} +process(NodeTracker, T): void
        }

        class LocalLinkNodePostProcessorState [[LocalLinkNodePostProcessorState.html]] {
            +LocalLinkNodePostProcessorState(WikiContext)
            +process(NodeTracker, JSPWikiLink): void
        }

        class LocalFootnoteRefLinkNodePostProcessorState [[LocalFootnoteRefLinkNodePostProcessorState.html]] {
            +LocalFootnoteRefLinkNodePostProcessorState(WikiContext)
            +process(NodeTracker, JSPWikiLink): void
        }

        class AccessRuleLinkNodePostProcessorState [[AccessRuleLinkNodePostProcessorState.html]] {
            +AccessRuleLinkNodePostProcessorState(WikiContext)
            +process(NodeTracker, JSPWikiLink): void
        }

        class JSPWikiNodePostProcessorFactory [[JSPWikiNodePostProcessorFactory.html]] {
            +JSPWikiNodePostProcessorFactory(WikiContext, DataHolder)
            +apply(Document): NodePostProcessor
        }

        class ImageLinkNodePostProcessorState [[ImageLinkNodePostProcessorState.html]] {
            +ImageLinkNodePostProcessorState(WikiContext, String, boolean)
            +process(NodeTracker, JSPWikiLink): void
        }

        class PluginLinkNodePostProcessorState [[PluginLinkNodePostProcessorState.html]] {
            +PluginLinkNodePostProcessorState(WikiContext)
            +process(NodeTracker, JSPWikiLink): void
        }

        class MetadataLinkNodePostProcessorState [[MetadataLinkNodePostProcessorState.html]] {
            +MetadataLinkNodePostProcessorState(WikiContext)
            +process(NodeTracker, JSPWikiLink): void
        }

        class JSPWikiLinkNodePostProcessor [[JSPWikiLinkNodePostProcessor.html]] {
            #m_context: WikiContext
            #linkOperations: LinkParsingOperations
            #m_useOutlinkImage: boolean
            #document: Document
            +JSPWikiLinkNodePostProcessor(WikiContext, Document)
            +process(NodeTracker, Node): void
        }

        class VariableLinkNodePostProcessorState [[VariableLinkNodePostProcessorState.html]] {
            +VariableLinkNodePostProcessorState(WikiContext)
            +process(NodeTracker, JSPWikiLink): void
        }

        class ExternalLinkNodePostProcessorState [[ExternalLinkNodePostProcessorState.html]] {
            +ExternalLinkNodePostProcessorState(WikiContext)
            +process(NodeTracker, JSPWikiLink): void
        }

        class InterWikiLinkNodePostProcessorState [[InterWikiLinkNodePostProcessorState.html]] {
            +InterWikiLinkNodePostProcessorState(WikiContext, Document)
            +process(NodeTracker, JSPWikiLink): void
        }

        NodePostProcessorState <|.. LocalFootnoteLinkNodePostProcessorState

        NodePostProcessorState <|.. LocalLinkNodePostProcessorState

        NodePostProcessorState <|.. LocalFootnoteRefLinkNodePostProcessorState

        NodePostProcessorState <|.. AccessRuleLinkNodePostProcessorState

        abstract class com.vladsch.flexmark.parser.block.NodePostProcessorFactory {
            {abstract} +apply(Document): NodePostProcessor
        }
        com.vladsch.flexmark.parser.block.NodePostProcessorFactory <|-- JSPWikiNodePostProcessorFactory

        NodePostProcessorState <|.. ImageLinkNodePostProcessorState

        NodePostProcessorState <|.. PluginLinkNodePostProcessorState

        NodePostProcessorState <|.. MetadataLinkNodePostProcessorState

        abstract class com.vladsch.flexmark.parser.block.NodePostProcessor
        com.vladsch.flexmark.parser.block.NodePostProcessor <|-- JSPWikiLinkNodePostProcessor

        NodePostProcessorState <|.. VariableLinkNodePostProcessorState

        NodePostProcessorState <|.. ExternalLinkNodePostProcessorState

        NodePostProcessorState <|.. InterWikiLinkNodePostProcessorState

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
