@startuml

    interface AuthorizationManager [[AuthorizationManager.html]] {
        {static} +DEFAULT_AUTHORIZER: String
        {static} +POLICY: String
        {static} +DEFAULT_POLICY: String
        {static} +PROP_AUTHORIZER: String
        +isUserInRole(Session, Principal): boolean
        +hasAccess(Context, HttpServletResponse): boolean
        +fireEvent(int, Principal, Object): void
        {abstract} +checkPermission(Session, Permission): boolean
        {abstract} +getAuthorizer(): Authorizer
        {abstract} +hasRoleOrPrincipal(Session, Principal): boolean
        {abstract} +hasAccess(Context, HttpServletResponse, boolean): boolean
        {abstract} +allowedByLocalPolicy(Principal[], Permission): boolean
        {abstract} +checkStaticPermission(Session, Permission): boolean
        {abstract} +resolvePrincipal(String): Principal
        {abstract} +addWikiEventListener(WikiEventListener): void
        {abstract} +removeWikiEventListener(WikiEventListener): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
