@startuml

    interface Authorizer [[Authorizer.html]] {
        {abstract} +getRoles(): Principal[]
        {abstract} +findRole(String): Principal
        {abstract} +initialize(Engine, Properties): void
        {abstract} +isUserInRole(WikiSession, Principal): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
