@startuml

    class DefaultAuthenticationManager [[DefaultAuthenticationManager.html]] {
        {static} #EMPTY_MAP: Map<String, String>
        #m_loginModuleClass: Class<?>
        #m_loginModuleOptions: Map<String, String>
        +initialize(Engine, Properties): void
        +isContainerAuthenticated(): boolean
        +login(HttpServletRequest): boolean
        +login(WikiSession, HttpServletRequest, String, String): boolean
        +logout(HttpServletRequest): void
        +allowsCookieAssertions(): boolean
        +allowsCookieAuthentication(): boolean
        +doJAASLogin(Class<?>, CallbackHandler, Map<String, String>): Set<Principal>
        +addWikiEventListener(WikiEventListener): void
        +removeWikiEventListener(WikiEventListener): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
