@startuml

    class DefaultAuthorizationManager [[DefaultAuthorizationManager.html]] {
        +checkPermission(Session, Permission): boolean
        +getAuthorizer(): Authorizer
        +hasRoleOrPrincipal(Session, Principal): boolean
        +hasAccess(WikiContext, HttpServletResponse, boolean): boolean
        +initialize(Engine, Properties): void
        +allowedByLocalPolicy(Principal[], Permission): boolean
        +checkStaticPermission(Session, Permission): boolean
        +resolvePrincipal(String): Principal
        +addWikiEventListener(WikiEventListener): void
        +removeWikiEventListener(WikiEventListener): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
