@startuml

    class SecurityVerifier [[SecurityVerifier.html]] {
        {static} +ERROR: String
        {static} +WARNING: String
        {static} +INFO: String
        {static} +ERROR_POLICY: String
        {static} +WARNING_POLICY: String
        {static} +INFO_POLICY: String
        {static} +ERROR_JAAS: String
        {static} +WARNING_JAAS: String
        {static} +ERROR_ROLES: String
        {static} +INFO_ROLES: String
        {static} +ERROR_DB: String
        {static} +WARNING_DB: String
        {static} +INFO_DB: String
        {static} +ERROR_GROUPS: String
        {static} +WARNING_GROUPS: String
        {static} +INFO_GROUPS: String
        {static} +INFO_JAAS: String
        +SecurityVerifier(Engine, WikiSession)
        +policyPrincipals(): Principal[]
        +policyRoleTable(): String
        +containerRoleTable(): String
        +isSecurityPolicyConfigured(): boolean
        +webContainerRoles(): Principal[]
        #verifyPolicyAndContainerRoles(): void
        #verifyGroupDatabase(): void
        #verifyJaas(): void
        #getFileFromProperty(String): File
        #verifyPolicy(): void
        #verifyStaticPermission(Principal, Permission): boolean
        #verifyUserDatabase(): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
