@startuml

    class SessionMonitor [[SessionMonitor.html]] {
        +SessionMonitor()
        {static} +getInstance(Engine): SessionMonitor
        +find(HttpSession): WikiSession
        +remove(HttpSession): void
        +sessions(): int
        +userPrincipals(): Principal[]
        +addWikiEventListener(WikiEventListener): void
        +removeWikiEventListener(WikiEventListener): void
        #fireEvent(int, Principal, WikiSession): void
        +sessionCreated(HttpSessionEvent): void
        +sessionDestroyed(HttpSessionEvent): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
