@startuml

    interface Acl [[Acl.html]] {
        {abstract} +addEntry(AclEntry): boolean
        {abstract} +aclEntries(): Enumeration<AclEntry>
        {abstract} +isEmpty(): boolean
        {abstract} +findPrincipals(Permission): Principal[]
        {abstract} +getAclEntry(Principal): AclEntry
        {abstract} +removeEntry(AclEntry): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
