@startuml

    enum ContextEnum [[ContextEnum.html]] {
        {static} +GROUP_DELETE
        {static} +GROUP_EDIT
        {static} +GROUP_VIEW
        {static} +PAGE_ATTACH
        {static} +PAGE_COMMENT
        {static} +PAGE_CONFLICT
        {static} +PAGE_DELETE
        {static} +PAGE_DIFF
        {static} +PAGE_EDIT
        {static} +PAGE_INFO
        {static} +PAGE_NONE
        {static} +PAGE_PREVIEW
        {static} +PAGE_RENAME
        {static} +PAGE_RSS
        {static} +PAGE_UPLOAD
        {static} +PAGE_VIEW
        {static} +REDIRECT
        {static} +WIKI_ADMIN
        {static} +WIKI_CREATE_GROUP
        {static} +WIKI_ERROR
        {static} +WIKI_FIND
        {static} +WIKI_INSTALL
        {static} +WIKI_LOGIN
        {static} +WIKI_LOGOUT
        {static} +WIKI_MESSAGE
        {static} +WIKI_PREFS
        {static} +WIKI_WORKFLOW
        +getContentTemplate(): String
        +getRequestContext(): String
        +getUrlPattern(): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
