@startuml

    namespace org.apache.wiki.auth.acl {

        class AclEntryImpl [[AclEntryImpl.html]] {
            +addPermission(Permission): boolean
            +checkPermission(Permission): boolean
            +permissions(): Enumeration<Permission>
            +removePermission(Permission): boolean
        }

        interface Acl [[Acl.html]] {
            {abstract} +addEntry(AclEntry): boolean
            {abstract} +entries(): Enumeration<AclEntry>
            {abstract} +isEmpty(): boolean
            {abstract} +findPrincipals(Permission): Principal[]
            {abstract} +getEntry(Principal): AclEntry
            {abstract} +removeEntry(AclEntry): boolean
        }

        class DefaultAclManager [[DefaultAclManager.html]] {
            {static} +ACL_PATTERN: Pattern
            +initialize(WikiEngine, Properties): void
            +parseAcl(WikiPage, String): Acl
            +getPermissions(WikiPage): Acl
            +setPermissions(WikiPage, Acl): void
            {static} #printAcl(Acl): String
        }

        class UnresolvedPrincipal [[UnresolvedPrincipal.html]] {
            +UnresolvedPrincipal(String)
            +getName(): String
        }

        interface AclEntry [[AclEntry.html]] {
            {abstract} +addPermission(Permission): boolean
            {abstract} +checkPermission(Permission): boolean
            {abstract} +permissions(): Enumeration<Permission>
            {abstract} +removePermission(Permission): boolean
        }

        class AclImpl [[AclImpl.html]] {
            +findPrincipals(Permission): Principal[]
            +addEntry(AclEntry): boolean
            +removeEntry(AclEntry): boolean
            +entries(): Enumeration<AclEntry>
            +getEntry(Principal): AclEntry
            +isEmpty(): boolean
        }

        interface AclManager [[AclManager.html]] {
            {abstract} +initialize(WikiEngine, Properties): void
            {abstract} +parseAcl(WikiPage, String): Acl
            {abstract} +getPermissions(WikiPage): Acl
            {abstract} +setPermissions(WikiPage, Acl): void
        }

        AclEntry <|.. AclEntryImpl

        interface java.io.Serializable
        java.io.Serializable <|.. AclEntryImpl

        AclManager <|.. DefaultAclManager

        interface java.security.Principal {
            {abstract} +getName(): String
        }
        java.security.Principal <|.. UnresolvedPrincipal

        java.io.Serializable <|.. UnresolvedPrincipal

        Acl <|.. AclImpl

        java.io.Serializable <|.. AclImpl

        AclEntryImpl --> java.security.Principal: principal

        AclEntry --> java.security.Principal: principal

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
