@startuml

    class CookieAssertionLoginModule [[CookieAssertionLoginModule.html]] {
        {static} +PREFS_COOKIE_NAME: String
        {static} #log: Logger
        +login(): boolean
        {static} +getUserCookie(HttpServletRequest): String
        {static} +setUserCookie(HttpServletResponse, String): void
        {static} +clearUserCookie(HttpServletResponse): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
