@startuml

    class ContextualDiffProvider [[ContextualDiffProvider.html]] {
        {static} +PROP_UNCHANGED_CONTEXT_LIMIT: String
        {static} +CHANGE_START_HTML: String
        {static} +CHANGE_END_HTML: String
        {static} +DIFF_START: String
        {static} +DIFF_END: String
        {static} +INSERTION_START_HTML: String
        {static} +INSERTION_END_HTML: String
        {static} +DELETION_START_HTML: String
        {static} +DELETION_END_HTML: String
        {static} +ELIDED_HEAD_INDICATOR_HTML: String
        {static} +ELIDED_TAIL_INDICATOR_HTML: String
        {static} +LINE_BREAK_HTML: String
        {static} +ALTERNATING_SPACE_HTML: String
        +m_emitChangeNextPreviousHyperlinks: boolean
        +getProviderInfo(): String
        +initialize(Engine, Properties): void
        +makeDiffHtml(WikiContext, String, String): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
