@startuml

    class DefaultDifferenceManager [[DefaultDifferenceManager.html]] {
        +DefaultDifferenceManager(WikiEngine, Properties)
        +makeDiff(WikiContext, String, String): String
        +getDiff(WikiContext, int, int): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
