@startuml

    class DifferenceManager [[DifferenceManager.html]] {
        {static} +PROP_DIFF_PROVIDER: String
        +DifferenceManager(WikiEngine, Properties)
        +makeDiff(WikiContext, String, String): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
