@startuml

    class ExternalDiffProvider [[ExternalDiffProvider.html]] {
        {static} +PROP_DIFFCOMMAND: String
        +getProviderInfo(): String
        +initialize(Engine, Properties): void
        +makeDiffHtml(WikiContext, String, String): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
