@startuml

    namespace org.apache.wiki.diff {

        interface DiffProvider [[DiffProvider.html]] {
            {abstract} +makeDiffHtml(WikiContext, String, String): String
        }

        class org.apache.wiki.diff.DiffProvider.NullDiffProvider [[DiffProvider.NullDiffProvider.html]] {
            +makeDiffHtml(WikiContext, String, String): String
            +initialize(WikiEngine, Properties): void
            +getProviderInfo(): String
        }

        class DifferenceManager [[DifferenceManager.html]] {
            {static} +PROP_DIFF_PROVIDER: String
            +DifferenceManager(WikiEngine, Properties)
            +makeDiff(WikiContext, String, String): String
        }

        class TraditionalDiffProvider [[TraditionalDiffProvider.html]] {
            +getProviderInfo(): String
            +initialize(WikiEngine, Properties): void
            +makeDiffHtml(WikiContext, String, String): String
        }

        class ContextualDiffProvider [[ContextualDiffProvider.html]] {
            {static} +PROP_UNCHANGED_CONTEXT_LIMIT: String
            +m_emitChangeNextPreviousHyperlinks: boolean
            +m_changeStartHtml: String
            +m_changeEndHtml: String
            +m_diffStart: String
            +m_diffEnd: String
            +m_insertionStartHtml: String
            +m_insertionEndHtml: String
            +m_deletionStartHtml: String
            +m_deletionEndHtml: String
            +m_elidedHeadIndicatorHtml: String
            +m_elidedTailIndicatorHtml: String
            +m_lineBreakHtml: String
            +m_alternatingSpaceHtml: String
            +getProviderInfo(): String
            +initialize(WikiEngine, Properties): void
            +makeDiffHtml(WikiContext, String, String): String
        }

        class ExternalDiffProvider [[ExternalDiffProvider.html]] {
            {static} +PROP_DIFFCOMMAND: String
            +getProviderInfo(): String
            +initialize(WikiEngine, Properties): void
            +makeDiffHtml(WikiContext, String, String): String
        }

        interface org.apache.wiki.WikiProvider {
            {abstract} +initialize(WikiEngine, Properties): void
            {abstract} +getProviderInfo(): String
        }
        org.apache.wiki.WikiProvider <|.. DiffProvider

        DiffProvider <|.. org.apache.wiki.diff.DiffProvider.NullDiffProvider

        DiffProvider +-- org.apache.wiki.diff.DiffProvider.NullDiffProvider

        DiffProvider <|.. TraditionalDiffProvider

        DiffProvider <|.. ContextualDiffProvider

        DiffProvider <|.. ExternalDiffProvider

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
