@startuml

    class TraditionalDiffProvider [[TraditionalDiffProvider.html]] {
        +getProviderInfo(): String
        +initialize(WikiEngine, Properties): void
        +makeDiffHtml(WikiContext, String, String): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
