@startuml

    class PluginBean [[PluginBean.html]] {
        +PluginBean(WikiEngine)
        +getTitle(): String
        +getType(): int
        #modules(): Collection<WikiModuleInfo>
        #heading(): Element
        #rowBody(WikiModuleInfo): Element
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
