@startuml

    class LuceneSearchProvider [[LuceneSearchProvider.html]] {
        {static} #log: Logger
        {static} +PROP_LUCENE_ANALYZER: String
        {static} +SEARCHABLE_FILE_SUFFIXES: String[]
        {static} #LUCENE_ID: String
        {static} #LUCENE_PAGE_CONTENTS: String
        {static} #LUCENE_AUTHOR: String
        {static} #LUCENE_ATTACHMENTS: String
        {static} #LUCENE_PAGE_NAME: String
        {static} #LUCENE_PAGE_KEYWORDS: String
        {static} +MAX_SEARCH_HITS: int
        {static} +FLAG_CONTEXTS: int
        #m_updates: List<Object[]>
        +initialize(WikiEngine, Properties): void
        #getEngine(): WikiEngine
        #doFullLuceneReindex(): void
        #getAttachmentContent(String, int): String
        #getAttachmentContent(Attachment): String
        #updateLuceneIndex(WikiPage, String): void
        #luceneIndexPage(WikiPage, String, IndexWriter): Document
        +pageRemoved(WikiPage): void
        +reindexPage(WikiPage): void
        +findPages(String, WikiContext): Collection<SearchResult>
        +findPages(String, int, WikiContext): Collection<SearchResult>
        +getProviderInfo(): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
