@startuml

    class AclEntryImpl [[AclEntryImpl.html]] {
        +addPermission(Permission): boolean
        +checkPermission(Permission): boolean
        +getPrincipal(): Principal
        +permissions(): Enumeration<Permission>
        +removePermission(Permission): boolean
        +setPrincipal(Principal): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
