@startuml

    class AclImpl [[AclImpl.html]] {
        +findPrincipals(Permission): Principal[]
        +addEntry(AclEntry): boolean
        +removeEntry(AclEntry): boolean
        +entries(): Enumeration<AclEntry>
        +getEntry(Principal): AclEntry
        +isEmpty(): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
