@startuml

    class DefaultAclManager [[DefaultAclManager.html]] {
        {static} +ACL_PATTERN: Pattern
        +initialize(WikiEngine, Properties): void
        +parseAcl(WikiPage, String): Acl
        +getPermissions(WikiPage): Acl
        +setPermissions(WikiPage, Acl): void
        {static} #printAcl(Acl): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
