@startuml

    class CookieTag [[CookieTag.html]] {
        +setName(String): void
        +setItem(String): void
        +setValue(String): void
        +setVar(String): void
        +setClear(String): void
        +setScope(String): void
        +release(): void
        +doEndTag(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
