@startuml

    class InsertDiffTag [[InsertDiffTag.html]] {
        {static} +ATTR_OLDVERSION: String
        {static} +ATTR_NEWVERSION: String
        #m_pageName: String
        +initTag(): void
        +setPage(String): void
        +getPage(): String
        +doWikiStartTag(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
