@startuml

    class PageDateTag [[PageDateTag.html]] {
        {static} +DEFAULT_FORMAT: String
        +initTag(): void
        +getFormat(): String
        +setFormat(String): void
        +doWikiStartTag(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
