@startuml

    class TabbedSectionTag [[TabbedSectionTag.html]] {
        +release(): void
        +setDefaultTab(String): void
        +validateDefaultTab(String): boolean
        +doStartTag(): int
        +isStateFindDefaultTab(): boolean
        +isStateGenerateTabMenu(): boolean
        +isStateGenerateTabBody(): boolean
        +doAfterBody(): int
        +doEndTag(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
