@startuml

    class UserProfileTag [[UserProfileTag.html]] {
        {static} +BLANK: String
        +initTag(): void
        +doWikiStartTag(): int
        +setProperty(String): void
        {static} +printGroups(WikiContext): String
        {static} +printRoles(WikiContext): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
