@startuml

    abstract class WikiLinkTag [[WikiLinkTag.html]] {
        {static} +ANCHOR: int
        {static} +URL: int
        #m_pageName: String
        #m_format: int
        #m_template: String
        +initTag(): void
        +setPage(String): void
        +getPage(): String
        +getTemplate(): String
        +setTemplate(String): void
        +setFormat(String): void
        +doEndTag(): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
