@startuml

    interface ContextSPI [[ContextSPI.html]] {
        {abstract} +create(Engine, Page): Context
        {abstract} +create(Engine, HttpServletRequest, Command): Context
        {abstract} +create(Engine, HttpServletRequest, Page): Context
        {abstract} +create(Engine, HttpServletRequest, String): Context
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
