@startuml

    class ContextDSL [[ContextDSL.html]] {
        +create(Engine, Page): Context
        +create(Engine, HttpServletRequest, Command): Context
        +create(Engine, HttpServletRequest, Page): Context
        +create(Engine, HttpServletRequest, String): Context
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
