@startuml

    interface ContentsSPI [[ContentsSPI.html]] {
        {abstract} +attachment(Engine, String, String): Attachment
        {abstract} +page(Engine, String): Page
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
