@startuml

    namespace org.apache.wiki.api.spi {

        class Wiki [[Wiki.html]] {
            {static} +init(ServletContext): Properties
            {static} +acls(): AclsDSL
            {static} +contents(): ContentsDSL
            {static} +context(): ContextDSL
            {static} +engine(): EngineDSL
            {static} +session(): SessionDSL
        }

        interface AclsSPI [[AclsSPI.html]] {
            {abstract} +acl(): Acl
            {abstract} +entry(): AclEntry
        }

        interface ContextSPI [[ContextSPI.html]] {
            {abstract} +create(Engine, Page): Context
            {abstract} +create(Engine, HttpServletRequest, Command): Context
            {abstract} +create(Engine, HttpServletRequest, Page): Context
            {abstract} +create(Engine, HttpServletRequest, String): Context
        }

        interface SessionSPI [[SessionSPI.html]] {
            {abstract} +remove(Engine, HttpServletRequest): void
            {abstract} +find(Engine, HttpServletRequest): Session
            {abstract} +guest(Engine): Session
        }

        interface EngineSPI [[EngineSPI.html]] {
            {abstract} +find(ServletContext, Properties): Engine
        }

        interface ContentsSPI [[ContentsSPI.html]] {
            {abstract} +attachment(Engine, String, String): Attachment
            {abstract} +page(Engine, String): Page
        }

        class SessionDSL [[SessionDSL.html]] {
            +remove(Engine, HttpServletRequest): void
            +find(Engine, HttpServletRequest): Session
            +guest(Engine): Session
        }

        class AclsDSL [[AclsDSL.html]] {
            +acl(): Acl
            +entry(): AclEntry
        }

        class EngineDSL [[EngineDSL.html]] {
            +find(ServletConfig): Engine
            +find(ServletConfig, Properties): Engine
            +find(ServletContext, Properties): Engine
        }

        class ContextDSL [[ContextDSL.html]] {
            +create(Engine, Page): Context
            +create(Engine, HttpServletRequest, Command): Context
            +create(Engine, HttpServletRequest, Page): Context
            +create(Engine, HttpServletRequest, String): Context
        }

        class ContentsDSL [[ContentsDSL.html]] {
            +attachment(Engine, String, String): Attachment
            +page(Engine, String): Page
        }

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
