@startuml

    class Preferences [[Preferences.html]] {
        {static} +SESSIONPREFS: String
        {static} +setupPreferences(PageContext): void
        {static} +reloadPreferences(PageContext): void
        {static} +getPreference(Context, String): String
        {static} +getPreference(PageContext, String): String
        {static} +getLocale(Context): Locale
        {static} +getBundle(Context, String): ResourceBundle
        {static} +getDateFormat(Context, Preferences.TimeFormat): SimpleDateFormat
        {static} +renderDate(Context, Date, Preferences.TimeFormat): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
