@startuml

    class DefaultWorkflowManager [[DefaultWorkflowManager.html]] {
        +getWorkflows(): Set<Workflow>
        +getCompletedWorkflows(): List<Workflow>
        +initialize(Engine, Properties): void
        +requiresApproval(String): boolean
        +getApprover(String): Principal
        #getEngine(): Engine
        +getDecisionQueue(): DecisionQueue
        +getOwnerWorkflows(Session): List<Workflow>
        +actionPerformed(WikiEvent): void
        #add(Workflow): void
        #remove(Workflow): void
        #removeFromDecisionQueue(Decision): void
        #addToDecisionQueue(Decision): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
