@startuml

    class Outcome [[Outcome.html]] {
        {static} +STEP_COMPLETE: Outcome
        {static} +STEP_ABORT: Outcome
        {static} +STEP_CONTINUE: Outcome
        {static} +DECISION_ACKNOWLEDGE: Outcome
        {static} +DECISION_APPROVE: Outcome
        {static} +DECISION_DENY: Outcome
        {static} +DECISION_HOLD: Outcome
        {static} +DECISION_REASSIGN: Outcome
        +isCompletion(): boolean
        +getMessageKey(): String
        {static} +forName(String): Outcome
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
