@startuml

    interface Step [[Step.html]] {
        {static} +TIME_NOT_SET: Date
        {abstract} +addSuccessor(Outcome, Step): void
        {abstract} +getAvailableOutcomes(): Collection<Outcome>
        {abstract} +getErrors(): List<String>
        {abstract} +execute(Context): Outcome
        {abstract} +getActor(): Principal
        {abstract} +getEndTime(): Date
        {abstract} +getMessageKey(): String
        {abstract} +getOutcome(): Outcome
        {abstract} +getStartTime(): Date
        {abstract} +isCompleted(): boolean
        {abstract} +isStarted(): boolean
        {abstract} +start(): void
        {abstract} +setOutcome(Outcome): void
        {abstract} +getSuccessor(Outcome): Step
        {abstract} +setWorkflow(int, Map<String, Serializable>): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
