@startuml

    interface WorkflowManager [[WorkflowManager.html]] {
        {static} +WF_WP_SAVE_APPROVER: String
        {static} +WF_WP_SAVE_DECISION_MESSAGE_KEY: String
        {static} +WF_WP_SAVE_REJECT_MESSAGE_KEY: String
        {static} +WF_WP_SAVE_FACT_PAGE_NAME: String
        {static} +WF_WP_SAVE_FACT_DIFF_TEXT: String
        {static} +WF_WP_SAVE_FACT_CURRENT_TEXT: String
        {static} +WF_WP_SAVE_FACT_PROPOSED_TEXT: String
        {static} +WF_WP_SAVE_FACT_IS_AUTHENTICATED: String
        {static} +WF_UP_CREATE_SAVE_ATTR_SAVED_PROFILE: String
        {static} +WF_UP_CREATE_SAVE_APPROVER: String
        {static} +WF_UP_CREATE_SAVE_DECISION_MESSAGE_KEY: String
        {static} +WF_UP_CREATE_SAVE_FACT_SUBMITTER: String
        {static} +WF_UP_CREATE_SAVE_FACT_PREFS_LOGIN_NAME: String
        {static} +WF_UP_CREATE_SAVE_FACT_PREFS_FULL_NAME: String
        {static} +WF_UP_CREATE_SAVE_FACT_PREFS_EMAIL: String
        {static} +PROPERTY_APPROVER_PREFIX: String
        {abstract} +getWorkflows(): Set<Workflow>
        {abstract} +getCompletedWorkflows(): List<Workflow>
        {abstract} +requiresApproval(String): boolean
        {abstract} +getApprover(String): Principal
        {abstract} +getDecisionQueue(): DecisionQueue
        {abstract} +getOwnerWorkflows(Session): List<Workflow>
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
