@startuml

    class WorkflowBuilder [[WorkflowBuilder.html]] {
        {static} +getBuilder(Engine): WorkflowBuilder
        +buildApprovalWorkflow(Principal, String, Step, String, Fact[], Step, String): Workflow
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
