@startuml

    class Workflow [[Workflow.html]] {
        {static} +ID_NOT_SET: int
        {static} +COMPLETED: int
        {static} +ABORTED: int
        {static} +WAITING: int
        {static} +RUNNING: int
        {static} +CREATED: int
        +Workflow(String, Principal)
        +abort(): void
        +addMessageArgument(Serializable): void
        +getCurrentActor(): Principal
        +getCurrentState(): int
        +getCurrentStep(): Step
        +getAttribute(String): Object
        +getAttributes(): Map<String, Serializable>
        +getEndTime(): Date
        +getId(): int
        +getMessageArguments(): Serializable[]
        +getMessageKey(): String
        +getOwner(): Principal
        +getStartTime(): Date
        +getHistory(): List<Step>
        +isAborted(): boolean
        +isCompleted(): boolean
        +isStarted(): boolean
        +getPreviousStep(): Step
        +restart(): void
        +setAttribute(String, Serializable): void
        +setFirstStep(Step): void
        +setId(int): void
        +start(): void
        +waitstate(): void
        #cleanup(): void
        #complete(): void
        #previousStep(Step): Step
        #processCurrentStep(): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
