@startuml

    namespace org.apache.wiki.markdown.extensions.jspwikilinks.postprocessor {

        class ExternalLinkNodePostProcessorState [[ExternalLinkNodePostProcessorState.html]] {
            +ExternalLinkNodePostProcessorState(Context, boolean, List<Pattern>)
            +process(NodeTracker, JSPWikiLink): void
        }

        class LocalLinkNodePostProcessorState [[LocalLinkNodePostProcessorState.html]] {
            +LocalLinkNodePostProcessorState(Context, boolean, List<Pattern>)
            +process(NodeTracker, JSPWikiLink): void
        }

        class LocalFootnoteRefLinkNodePostProcessorState [[LocalFootnoteRefLinkNodePostProcessorState.html]] {
            +LocalFootnoteRefLinkNodePostProcessorState(Context)
            +process(NodeTracker, JSPWikiLink): void
        }

        interface NodePostProcessorState<T> [[NodePostProcessorState.html]] {
            {abstract} +process(NodeTracker, T): void
        }

        class JSPWikiLinkNodePostProcessor [[JSPWikiLinkNodePostProcessor.html]] {
            #m_context: Context
            #linkOperations: LinkParsingOperations
            #m_useOutlinkImage: boolean
            #document: Document
            +JSPWikiLinkNodePostProcessor(Context, Document, boolean, List<Pattern>)
            +process(NodeTracker, Node): void
        }

        class LocalFootnoteLinkNodePostProcessorState [[LocalFootnoteLinkNodePostProcessorState.html]] {
            +LocalFootnoteLinkNodePostProcessorState(Context)
            +process(NodeTracker, JSPWikiLink): void
        }

        class InterWikiLinkNodePostProcessorState [[InterWikiLinkNodePostProcessorState.html]] {
            +InterWikiLinkNodePostProcessorState(Context, Document, boolean, List<Pattern>)
            +process(NodeTracker, JSPWikiLink): void
        }

        class VariableLinkNodePostProcessorState [[VariableLinkNodePostProcessorState.html]] {
            +VariableLinkNodePostProcessorState(Context)
            +process(NodeTracker, JSPWikiLink): void
        }

        class JSPWikiNodePostProcessorFactory [[JSPWikiNodePostProcessorFactory.html]] {
            +JSPWikiNodePostProcessorFactory(Context, DataHolder, boolean, List<Pattern>)
            +apply(Document): NodePostProcessor
        }

        class PluginLinkNodePostProcessorState [[PluginLinkNodePostProcessorState.html]] {
            +PluginLinkNodePostProcessorState(Context)
            +process(NodeTracker, JSPWikiLink): void
        }

        class MetadataLinkNodePostProcessorState [[MetadataLinkNodePostProcessorState.html]] {
            +MetadataLinkNodePostProcessorState(Context)
            +process(NodeTracker, JSPWikiLink): void
        }

        class ImageLinkNodePostProcessorState [[ImageLinkNodePostProcessorState.html]] {
            +ImageLinkNodePostProcessorState(Context, String, boolean)
            +process(NodeTracker, JSPWikiLink): void
        }

        class AccessRuleLinkNodePostProcessorState [[AccessRuleLinkNodePostProcessorState.html]] {
            +AccessRuleLinkNodePostProcessorState(Context)
            +process(NodeTracker, JSPWikiLink): void
        }

        NodePostProcessorState <|.. ExternalLinkNodePostProcessorState

        NodePostProcessorState <|.. LocalLinkNodePostProcessorState

        NodePostProcessorState <|.. LocalFootnoteRefLinkNodePostProcessorState

        abstract class com.vladsch.flexmark.parser.block.NodePostProcessor
        com.vladsch.flexmark.parser.block.NodePostProcessor <|-- JSPWikiLinkNodePostProcessor

        NodePostProcessorState <|.. LocalFootnoteLinkNodePostProcessorState

        NodePostProcessorState <|.. InterWikiLinkNodePostProcessorState

        NodePostProcessorState <|.. VariableLinkNodePostProcessorState

        abstract class com.vladsch.flexmark.parser.block.NodePostProcessorFactory {
            {abstract} +apply(Document): NodePostProcessor
        }
        com.vladsch.flexmark.parser.block.NodePostProcessorFactory <|-- JSPWikiNodePostProcessorFactory

        NodePostProcessorState <|.. PluginLinkNodePostProcessorState

        NodePostProcessorState <|.. MetadataLinkNodePostProcessorState

        NodePostProcessorState <|.. ImageLinkNodePostProcessorState

        NodePostProcessorState <|.. AccessRuleLinkNodePostProcessorState

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
