@startuml

    interface PageRenamer [[PageRenamer.html]] {
        {abstract} +renamePage(WikiContext, String, String, boolean): String
        {abstract} +firePageRenameEvent(String, String): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
