@startuml

    class ReadWikiPage [[ReadWikiPage.html]] {
        +authenticatedText(): String
        +clickOnLogin(): LoginPage
        +clickOnShowReaderView(): ReadWikiPage
        +hoverLoginArea(): ReadWikiPage
        +hoverMoreArea(): ReadWikiPage
        +logout(): ReadWikiPage
        +navigateTo(String): ReadWikiPage
        +sidebar(): SelenideElement
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
