@startuml

    abstract class AbstractCommand [[AbstractCommand.html]] {
        #AbstractCommand(String, String, String, Object)
        +getContentTemplate(): String
        +getJSP(): String
        +getRequestContext(): String
        +getTarget(): Object
        +getURLPattern(): String
        #getJSPFriendlyName(): String
        {abstract} +targetedCommand(Object): Command
        {abstract} +getName(): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
