@startuml

    class DefaultEditorManager [[DefaultEditorManager.html]] {
        +DefaultEditorManager(Engine)
        +initialize(Properties): void
        +getEditorName(Context): String
        +getEditorList(): String[]
        +getEditorPath(Context): String
        +modules(): Collection<WikiModuleInfo>
        +getModuleInfo(String): DefaultEditorManager.WikiEditorInfo
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
