@startuml

    class DefaultCommandResolver [[DefaultCommandResolver.html]] {
        +DefaultCommandResolver(WikiEngine, Properties)
        +findCommand(HttpServletRequest, String): Command
        +getFinalPageName(String): String
        +getSpecialPageReference(String): String
        #extractCommandFromPath(HttpServletRequest): Command
        +extractPageFromParameter(String, HttpServletRequest): String
        +resolvePage(HttpServletRequest, String): WikiPage
        #simplePageExists(String): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
