@startuml

    interface EditorManager [[EditorManager.html]] {
        {static} +PROP_EDITORTYPE: String
        {static} +PARA_EDITOR: String
        {static} +EDITOR_PLAIN: String
        {static} +EDITOR_PREVIEW: String
        {static} +REQ_EDITEDTEXT: String
        {static} +ATTR_EDITEDTEXT: String
        {static} +getEditedText(PageContext): String
        {abstract} +initialize(Properties): void
        {abstract} +getEditorName(WikiContext): String
        {abstract} +getEditorList(): String[]
        {abstract} +getEditorPath(WikiContext): String
        {abstract} +modules(): Collection<WikiModuleInfo>
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
