@startuml

    class EditorManager [[EditorManager.html]] {
        {static} +PROP_EDITORTYPE: String
        {static} +PARA_EDITOR: String
        {static} +EDITOR_PLAIN: String
        {static} +EDITOR_PREVIEW: String
        {static} +REQ_EDITEDTEXT: String
        {static} +ATTR_EDITEDTEXT: String
        +EditorManager(WikiEngine)
        +initialize(Properties): void
        +getEditorName(WikiContext): String
        +getEditorList(): String[]
        +getEditorPath(WikiContext): String
        {static} +getEditedText(PageContext): String
        +modules(): Collection<WikiModuleInfo>
        +getModuleInfo(String): EditorManager.WikiEditorInfo
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
