@startuml

    class GroupCommand [[GroupCommand.html]] {
        {static} +DELETE_GROUP: Command
        {static} +EDIT_GROUP: Command
        {static} +VIEW_GROUP: Command
        +targetedCommand(Object): Command
        +getName(): String
        +requiredPermission(): Permission
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
