@startuml

    namespace org.apache.wiki.ui {

        class WikiRequestWrapper [[WikiRequestWrapper.html]] {
            +WikiRequestWrapper(WikiEngine, HttpServletRequest)
            +getRemoteUser(): String
            +getUserPrincipal(): Principal
            +isUserInRole(String): boolean
        }

        class RedirectCommand [[RedirectCommand.html]] {
            {static} +REDIRECT: Command
            +targetedCommand(Object): Command
            +getName(): String
            +requiredPermission(): Permission
        }

        class EditorManager [[EditorManager.html]] {
            {static} +PROP_EDITORTYPE: String
            {static} +PARA_EDITOR: String
            {static} +EDITOR_PLAIN: String
            {static} +EDITOR_PREVIEW: String
            {static} +REQ_EDITEDTEXT: String
            {static} +ATTR_EDITEDTEXT: String
            +EditorManager(WikiEngine)
            +initialize(Properties): void
            +getEditorName(WikiContext): String
            +getEditorList(): String[]
            +getEditorPath(WikiContext): String
            {static} +getEditedText(PageContext): String
            +modules(): Collection<WikiModuleInfo>
            +getModuleInfo(String): EditorManager.WikiEditorInfo
        }

        class InputValidator [[InputValidator.html]] {
            {static} +STANDARD: int
            {static} +EMAIL: int
            {static} +ID: int
            {static} #EMAIL_PATTERN: Pattern
            {static} #UNSAFE_PATTERN: Pattern
            {static} #ID_PATTERN: Pattern
            +InputValidator(String, WikiContext)
            +validateNotNull(String, String): boolean
            +validateNotNull(String, String, int): boolean
            +validate(String, String, int): boolean
            {static} +isBlank(String): boolean
        }

        class TemplateManager [[TemplateManager.html]] {
            {static} +RESOURCE_JSFUNCTION: String
            {static} +RESOURCE_JSLOCALIZEDSTRINGS: String
            {static} +RESOURCE_STYLESHEET: String
            {static} +RESOURCE_SCRIPT: String
            {static} +RESOURCE_INLINECSS: String
            {static} +DIRECTORY: String
            {static} +DEFAULT_TEMPLATE: String
            {static} +PROPERTYFILE: String
            {static} +I18NRESOURCE_PREFIX: String
            {static} +I18NRESOURCE_SUFFIX: String
            {static} +I18NRESOURCE_EN: String
            {static} +I18NRESOURCE_EN_ID: String
            {static} +I18NDEFAULT_LOCALE: String
            {static} +I18NSERVER_TIMEZONE: String
            {static} +TIMEFORMATPROPERTIES: String
            {static} +RESOURCE_INCLUDES: String
            {static} #log: Logger
            {static} +RESOURCE_HTTPHEADER: String
            +TemplateManager(WikiEngine, Properties)
            +templateExists(String): boolean
            +findJSP(PageContext, String): String
            +findJSP(PageContext, String, String): String
            +findResource(WikiContext, String, String): String
            +listSkins(PageContext, String): Set<String>
            +listLanguages(PageContext): Map<String, String>
            +listTimeFormats(PageContext): Map<String, String>
            +listTimeZones(PageContext): Map<String, String>
            {static} +getMarker(WikiContext, String): String
            {static} +addResourceRequest(WikiContext, String, String): void
            {static} +getResourceRequests(WikiContext, String): String[]
            {static} +getResourceTypes(WikiContext): String[]
            +modules(): Collection<WikiModuleInfo>
            +getModuleInfo(String): WikiModuleInfo
        }

        class WikiCommand [[WikiCommand.html]] {
            {static} +CREATE_GROUP: Command
            {static} +ERROR: Command
            {static} +FIND: Command
            {static} +INSTALL: Command
            {static} +LOGIN: Command
            {static} +LOGOUT: Command
            {static} +MESSAGE: Command
            {static} +PREFS: Command
            {static} +WORKFLOW: Command
            {static} +ADMIN: Command
            +targetedCommand(Object): Command
            +getName(): String
            +requiredPermission(): Permission
        }

        abstract class AbstractCommand [[AbstractCommand.html]] {
            #AbstractCommand(String, String, String, Object)
            {static} +allCommands(): Command[]
            +getContentTemplate(): String
            +getJSP(): String
            +getRequestContext(): String
            +getTarget(): Object
            +getURLPattern(): String
            #getJSPFriendlyName(): String
            {abstract} +targetedCommand(Object): Command
            {abstract} +getName(): String
        }

        class Editor [[Editor.html]] {
            +Editor(WikiContext, String)
            +getName(): String
            +isSelected(): String
            +isSelected(String): String
            +isSelected(String, String): String
        }

        class Installer [[Installer.html]] {
            {static} +ADMIN_ID: String
            {static} +ADMIN_NAME: String
            {static} +INSTALL_INFO: String
            {static} +INSTALL_ERROR: String
            {static} +INSTALL_WARNING: String
            {static} +APP_NAME: String
            {static} +STORAGE_DIR: String
            {static} +PAGE_DIR: String
            {static} +WORK_DIR: String
            {static} +ADMIN_GROUP: String
            {static} +PROPFILENAME: String
            {static} +TMP_DIR: String
            +Installer(HttpServletRequest, ServletConfig)
            +adminExists(): boolean
            +createAdministrator(): String
            +getPropertiesList(): String
            +getPropertiesPath(): String
            +getProperty(String): String
            +parseProperties(): void
            +saveProperties(): void
            +validateProperties(): boolean
        }

        class PageCommand [[PageCommand.html]] {
            {static} +ATTACH: Command
            {static} +COMMENT: Command
            {static} +CONFLICT: Command
            {static} +DELETE: Command
            {static} +DIFF: Command
            {static} +EDIT: Command
            {static} +INFO: Command
            {static} +PREVIEW: Command
            {static} +RENAME: Command
            {static} +RSS: Command
            {static} +UPLOAD: Command
            {static} +VIEW: Command
            {static} +NONE: Command
            {static} +OTHER: Command
            +targetedCommand(Object): Command
            +getName(): String
            +requiredPermission(): Permission
        }

        class WikiServletFilter [[WikiServletFilter.html]] {
            {static} #log: Logger
            #m_engine: WikiEngine
            +init(FilterConfig): void
            +destroy(): void
            +doFilter(ServletRequest, ServletResponse, FilterChain): void
            #getWikiContext(ServletRequest): WikiContext
        }

        interface Command [[Command.html]] {
            {abstract} +targetedCommand(Object): Command
            {abstract} +getContentTemplate(): String
            {abstract} +getJSP(): String
            {abstract} +getName(): String
            {abstract} +getRequestContext(): String
            {abstract} +requiredPermission(): Permission
            {abstract} +getTarget(): Object
            {abstract} +getURLPattern(): String
        }

        class CommandResolver [[CommandResolver.html]] {
            +CommandResolver(WikiEngine, Properties)
            {static} +findCommand(String): Command
            +findCommand(HttpServletRequest, String): Command
            +getFinalPageName(String): String
            +getSpecialPageReference(String): String
            #extractCommandFromPath(HttpServletRequest): Command
            #extractPageFromParameter(String, HttpServletRequest): String
            #resolvePage(HttpServletRequest, String): WikiPage
            #simplePageExists(String): boolean
        }

        class WikiJSPFilter [[WikiJSPFilter.html]] {
            +init(FilterConfig): void
            +doFilter(ServletRequest, ServletResponse, FilterChain): void
            #fireEvent(int, String): void
        }

        interface GenericHTTPHandler [[GenericHTTPHandler.html]] {
            {abstract} +getId(): String
            {abstract} +doGet(WikiContext): String
            {abstract} +doPost(WikiContext): String
        }

        class GroupCommand [[GroupCommand.html]] {
            {static} +DELETE_GROUP: Command
            {static} +EDIT_GROUP: Command
            {static} +VIEW_GROUP: Command
            +targetedCommand(Object): Command
            +getName(): String
            +requiredPermission(): Permission
        }

        class javax.servlet.http.HttpServletRequestWrapper
        javax.servlet.http.HttpServletRequestWrapper <|-- WikiRequestWrapper

        AbstractCommand <|-- RedirectCommand

        abstract class org.apache.wiki.modules.ModuleManager {
            {abstract} +modules(): Collection<WikiModuleInfo>
            {abstract} +getModuleInfo(String): WikiModuleInfo
        }
        org.apache.wiki.modules.ModuleManager <|-- EditorManager

        org.apache.wiki.modules.ModuleManager <|-- TemplateManager

        AbstractCommand <|-- WikiCommand

        Command <|.. AbstractCommand

        AbstractCommand <|-- PageCommand

        interface javax.servlet.Filter {
            {abstract} +init(FilterConfig): void
            {abstract} +doFilter(ServletRequest, ServletResponse, FilterChain): void
            {abstract} +destroy(): void
        }
        javax.servlet.Filter <|.. WikiServletFilter

        WikiServletFilter <|-- WikiJSPFilter

        AbstractCommand <|-- GroupCommand

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
