@startuml

    class RedirectCommand [[RedirectCommand.html]] {
        {static} +REDIRECT: Command
        +targetedCommand(Object): Command
        +getName(): String
        +requiredPermission(): Permission
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
