@startuml

    interface TemplateManager [[TemplateManager.html]] {
        {static} +SKIN_DIRECTORY: String
        {static} +RESOURCE_JSFUNCTION: String
        {static} +RESOURCE_JSLOCALIZEDSTRINGS: String
        {static} +RESOURCE_STYLESHEET: String
        {static} +RESOURCE_SCRIPT: String
        {static} +RESOURCE_INLINECSS: String
        {static} +DIRECTORY: String
        {static} +DEFAULT_TEMPLATE: String
        {static} +PROPERTYFILE: String
        {static} +I18NRESOURCE_PREFIX: String
        {static} +I18NRESOURCE_SUFFIX: String
        {static} +I18NRESOURCE_EN: String
        {static} +I18NRESOURCE_EN_ID: String
        {static} +I18NDEFAULT_LOCALE: String
        {static} +I18NSERVER_TIMEZONE: String
        {static} +TIMEFORMATPROPERTIES: String
        {static} +RESOURCE_INCLUDES: String
        {static} +RESOURCE_HTTPHEADER: String
        +listLanguages(PageContext): Map<String, String>
        +listTimeZones(PageContext): Map<String, String>
        {static} +getMarker(Context, String): String
        {static} +getJSLocalizedStrings(Context): String
        {static} +addResourceRequest(Context, String, String): void
        {static} +getResourceRequests(Context, String): String[]
        {static} +getResourceTypes(Context): String[]
        {abstract} +templateExists(String): boolean
        {abstract} +findJSP(PageContext, String): String
        {abstract} +findJSP(PageContext, String, String): String
        {abstract} +findResource(Context, String, String): String
        {abstract} +listSkins(PageContext, String): Set<String>
        {abstract} +listTimeFormats(PageContext): Map<String, String>
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
