@startuml

    class TemplateManager [[TemplateManager.html]] {
        {static} +RESOURCE_JSFUNCTION: String
        {static} +RESOURCE_JSLOCALIZEDSTRINGS: String
        {static} +RESOURCE_STYLESHEET: String
        {static} +RESOURCE_SCRIPT: String
        {static} +RESOURCE_INLINECSS: String
        {static} +DIRECTORY: String
        {static} +DEFAULT_TEMPLATE: String
        {static} +PROPERTYFILE: String
        {static} +I18NRESOURCE_PREFIX: String
        {static} +I18NRESOURCE_SUFFIX: String
        {static} +I18NRESOURCE_EN: String
        {static} +I18NRESOURCE_EN_ID: String
        {static} +I18NDEFAULT_LOCALE: String
        {static} +I18NSERVER_TIMEZONE: String
        {static} +TIMEFORMATPROPERTIES: String
        {static} +RESOURCE_INCLUDES: String
        {static} +RESOURCE_HTTPHEADER: String
        +TemplateManager(WikiEngine, Properties)
        +templateExists(String): boolean
        +findJSP(PageContext, String): String
        +findJSP(PageContext, String, String): String
        +findResource(WikiContext, String, String): String
        +listSkins(PageContext, String): Set<String>
        +listLanguages(PageContext): Map<String, String>
        +listTimeFormats(PageContext): Map<String, String>
        +listTimeZones(PageContext): Map<String, String>
        {static} +getMarker(WikiContext, String): String
        {static} +addResourceRequest(WikiContext, String, String): void
        {static} +getResourceRequests(WikiContext, String): String[]
        {static} +getResourceTypes(WikiContext): String[]
        +modules(): Collection<WikiModuleInfo>
        +getModuleInfo(String): WikiModuleInfo
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
