@startuml

    class WikiRequestWrapper [[WikiRequestWrapper.html]] {
        +WikiRequestWrapper(WikiEngine, HttpServletRequest)
        +getRemoteUser(): String
        +getUserPrincipal(): Principal
        +isUserInRole(String): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
