@startuml

    class WikiServletFilter [[WikiServletFilter.html]] {
        #m_engine: WikiEngine
        +init(FilterConfig): void
        +destroy(): void
        +doFilter(ServletRequest, ServletResponse, FilterChain): void
        #getWikiContext(ServletRequest): WikiContext
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
