@startuml

    namespace org.apache.wiki.tasks.auth {

        class SaveUserProfileTask [[SaveUserProfileTask.html]] {
            +SaveUserProfileTask(WikiEngine, Locale)
            +execute(): Outcome
        }

        abstract class org.apache.wiki.workflow.Task
        org.apache.wiki.workflow.Task <|-- SaveUserProfileTask

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
