@startuml

    interface WikiPageProvider [[WikiPageProvider.html]] {
        {abstract} +putPageText(WikiPage, String): void
        {abstract} +pageExists(String): boolean
        {abstract} +pageExists(String, int): boolean
        {abstract} +findPages(QueryItem[]): Collection<SearchResult>
        {abstract} +getPageInfo(String, int): WikiPage
        {abstract} +getAllPages(): Collection<WikiPage>
        {abstract} +getAllChangedSince(Date): Collection<WikiPage>
        {abstract} +getPageCount(): int
        {abstract} +getVersionHistory(String): List<WikiPage>
        {abstract} +getPageText(String, int): String
        {abstract} +deleteVersion(String, int): void
        {abstract} +deletePage(String): void
        {abstract} +movePage(String, String): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
