@startuml

    namespace org.apache.wiki.its {

        class LoginIT [[LoginIT.html]] {
        }

        class AnonymousViewIT [[AnonymousViewIT.html]] {
        }

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
