@startuml

    namespace org.apache.wiki.auth.user {

        class XMLUserDatabase [[XMLUserDatabase.html]] {
            {static} +PROP_USERDATABASE: String
            +deleteByLoginName(String): void
            +findByEmail(String): UserProfile
            +findByFullName(String): UserProfile
            +findByLoginName(String): UserProfile
            +findByUid(String): UserProfile
            +findByWikiName(String): UserProfile
            +getWikiNames(): Principal[]
            +initialize(WikiEngine, Properties): void
            +rename(String, String): void
            +save(UserProfile): void
        }

        interface UserDatabase [[UserDatabase.html]] {
            {abstract} +deleteByLoginName(String): void
            {abstract} +getPrincipals(String): Principal[]
            {abstract} +getWikiNames(): Principal[]
            {abstract} +find(String): UserProfile
            {abstract} +findByEmail(String): UserProfile
            {abstract} +findByLoginName(String): UserProfile
            {abstract} +findByUid(String): UserProfile
            {abstract} +findByWikiName(String): UserProfile
            {abstract} +findByFullName(String): UserProfile
            {abstract} +initialize(WikiEngine, Properties): void
            {abstract} +newProfile(): UserProfile
            {abstract} +rename(String, String): void
            {abstract} +save(UserProfile): void
            {abstract} +validatePassword(String, String): boolean
        }

        abstract class AbstractUserDatabase [[AbstractUserDatabase.html]] {
            {static} #log: Logger
            {static} #SHA_PREFIX: String
            {static} #SSHA_PREFIX: String
            +find(String): UserProfile
            +getPrincipals(String): Principal[]
            +newProfile(): UserProfile
            +validatePassword(String, String): boolean
            {static} #generateUid(UserDatabase): String
            #getHash(String): String
            #parseLong(String): long
            {abstract} +findByEmail(String): UserProfile
            {abstract} +findByFullName(String): UserProfile
            {abstract} +findByLoginName(String): UserProfile
            {abstract} +findByWikiName(String): UserProfile
            {abstract} +initialize(WikiEngine, Properties): void
            {abstract} +save(UserProfile): void
        }

        class DefaultUserProfile [[DefaultUserProfile.html]] {
            {static} #newProfile(UserDatabase): UserProfile
            +getCreated(): Date
            +getEmail(): String
            +getFullname(): String
            +getLastModified(): Date
            +getLoginName(): String
            +getPassword(): String
            +getWikiName(): String
            +isNew(): boolean
            +setCreated(Date): void
            +setEmail(String): void
            +setFullname(String): void
            +setLastModified(Date): void
            +setLoginName(String): void
            +setPassword(String): void
            +getAttributes(): Map<String, Serializable>
            +getLockExpiry(): Date
            +getUid(): String
            +isLocked(): boolean
            +setLockExpiry(Date): void
            +setUid(String): void
        }

        interface UserProfile [[UserProfile.html]] {
            {abstract} +getAttributes(): Map<String, Serializable>
            {abstract} +getCreated(): Date
            {abstract} +getEmail(): String
            {abstract} +getFullname(): String
            {abstract} +getLastModified(): Date
            {abstract} +getLockExpiry(): Date
            {abstract} +getLoginName(): String
            {abstract} +getPassword(): String
            {abstract} +getUid(): String
            {abstract} +getWikiName(): String
            {abstract} +isLocked(): boolean
            {abstract} +isNew(): boolean
            {abstract} +setCreated(Date): void
            {abstract} +setEmail(String): void
            {abstract} +setFullname(String): void
            {abstract} +setLastModified(Date): void
            {abstract} +setLockExpiry(Date): void
            {abstract} +setLoginName(String): void
            {abstract} +setPassword(String): void
            {abstract} +setUid(String): void
        }

        class DuplicateUserException [[DuplicateUserException.html]] {
            +DuplicateUserException(String)
            +DuplicateUserException(String, Object[])
        }

        class JDBCUserDatabase [[JDBCUserDatabase.html]] {
            {static} +DEFAULT_DB_ATTRIBUTES: String
            {static} +DEFAULT_DB_CREATED: String
            {static} +DEFAULT_DB_EMAIL: String
            {static} +DEFAULT_DB_FULL_NAME: String
            {static} +DEFAULT_DB_JNDI_NAME: String
            {static} +DEFAULT_DB_LOCK_EXPIRY: String
            {static} +DEFAULT_DB_MODIFIED: String
            {static} +DEFAULT_DB_ROLE: String
            {static} +DEFAULT_DB_ROLE_TABLE: String
            {static} +DEFAULT_DB_TABLE: String
            {static} +DEFAULT_DB_LOGIN_NAME: String
            {static} +DEFAULT_DB_PASSWORD: String
            {static} +DEFAULT_DB_UID: String
            {static} +DEFAULT_DB_WIKI_NAME: String
            {static} +PROP_DB_ATTRIBUTES: String
            {static} +PROP_DB_CREATED: String
            {static} +PROP_DB_EMAIL: String
            {static} +PROP_DB_FULL_NAME: String
            {static} +PROP_DB_DATASOURCE: String
            {static} +PROP_DB_LOCK_EXPIRY: String
            {static} +PROP_DB_LOGIN_NAME: String
            {static} +PROP_DB_MODIFIED: String
            {static} +PROP_DB_PASSWORD: String
            {static} +PROP_DB_UID: String
            {static} +PROP_DB_ROLE: String
            {static} +PROP_DB_ROLE_TABLE: String
            {static} +PROP_DB_TABLE: String
            {static} +PROP_DB_WIKI_NAME: String
            +deleteByLoginName(String): void
            +findByEmail(String): UserProfile
            +findByFullName(String): UserProfile
            +findByLoginName(String): UserProfile
            +findByUid(String): UserProfile
            +findByWikiName(String): UserProfile
            +getWikiNames(): Principal[]
            +initialize(WikiEngine, Properties): void
            +rename(String, String): void
            +save(UserProfile): void
        }

        AbstractUserDatabase <|-- XMLUserDatabase

        UserDatabase <|.. AbstractUserDatabase

        UserProfile <|.. DefaultUserProfile

        interface java.io.Serializable
        java.io.Serializable <|.. UserProfile

        class org.apache.wiki.api.exceptions.WikiI18nException
        org.apache.wiki.api.exceptions.WikiI18nException <|-- DuplicateUserException

        AbstractUserDatabase <|-- JDBCUserDatabase

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
