@startuml

    namespace org.apache.wiki.api.plugin {

        interface InitializablePlugin [[InitializablePlugin.html]] {
            {abstract} +initialize(WikiEngine): void
        }

        interface WikiPlugin [[WikiPlugin.html]] {
            {static} +CORE_PLUGINS_RESOURCEBUNDLE: String
            {abstract} +execute(WikiContext, Map<String, String>): String
        }

        interface ParserStagePlugin [[ParserStagePlugin.html]] {
            {abstract} +executeParser(PluginContent, WikiContext, Map<String, String>): void
        }

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
