@startuml

    namespace org.apache.wiki.api.plugin {

        interface ParserStagePlugin [[ParserStagePlugin.html]] {
            {abstract} +executeParser(PluginElement, WikiContext, Map<String, String>): void
        }

        interface InitializablePlugin [[InitializablePlugin.html]] {
            {abstract} +initialize(Engine): void
        }

        interface PluginElement [[PluginElement.html]] {
            {abstract} +getPluginName(): String
            {abstract} +getParameter(String): String
            {abstract} +getParameters(): Map<String, String>
            {abstract} +getValue(): String
            {abstract} +getText(): String
            {abstract} +invoke(WikiContext): String
            {abstract} +executeParse(WikiContext): void
        }

        interface WikiPlugin [[WikiPlugin.html]] {
            {static} +CORE_PLUGINS_RESOURCEBUNDLE: String
            {abstract} +execute(WikiContext, Map<String, String>): String
        }

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
