@startuml

    interface PluginElement [[PluginElement.html]] {
        {abstract} +getPluginName(): String
        {abstract} +getParameter(String): String
        {abstract} +getParameters(): Map<String, String>
        {abstract} +getValue(): String
        {abstract} +getText(): String
        {abstract} +invoke(Context): String
        {abstract} +executeParse(Context): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
