@startuml

    interface WikiPlugin <<deprecated>> [[WikiPlugin.html]] {
        + --execute-- (Context, Map<String, String>): String
        {abstract} + --execute-- (WikiContext, Map<String, String>): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
