@startuml

    interface FilterManager [[FilterManager.html]] {
        {static} +PROP_FILTERXML: String
        {static} +DEFAULT_XMLFILE: String
        {static} +SYSTEM_FILTER_PRIORITY: int
        {static} +USER_FILTER_PRIORITY: int
        {abstract} +addPageFilter(PageFilter, int): void
        {abstract} +doPreTranslateFiltering(Context, String): String
        {abstract} +doPostTranslateFiltering(Context, String): String
        {abstract} +doPreSaveFiltering(Context, String): String
        {abstract} +doPostSaveFiltering(Context, String): void
        {abstract} +getFilterList(): List<PageFilter>
        {abstract} +destroy(): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
