@startuml

    class PageEventFilter [[PageEventFilter.html]] {
        +initialize(Engine, Properties): void
        +preTranslate(Context, String): String
        +postTranslate(Context, String): String
        +preSave(Context, String): String
        +postSave(Context, String): void
        +addWikiEventListener(WikiEventListener): void
        +removeWikiEventListener(WikiEventListener): void
        #fireEvent(int, Context): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
