@startuml

    class JSPWikiMarkupParser [[JSPWikiMarkupParser.html]] {
        {static} #READ: int
        {static} #EDIT: int
        {static} #EMPTY: int
        {static} #LOCAL: int
        {static} #LOCALREF: int
        {static} #IMAGE: int
        {static} #EXTERNAL: int
        {static} #INTERWIKI: int
        {static} #IMAGELINK: int
        {static} #IMAGEWIKILINK: int
        {static} #ATTACHMENT: int
        {static} #CHARACTER: int
        {static} #ELEMENT: int
        {static} #IGNORE: int
        +JSPWikiMarkupParser(Context, Reader)
        #callMutatorChain(Collection<StringTransmutator>, String): String
        #callHeadingListenerChain(Heading): void
        #createAnchor(int, String, String, String): Element
        +makeHeading(int, String, Heading): Element
        #parseToken(int): int
        +parse(): WikiDocument
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
