@startuml

    abstract class MarkupParser [[MarkupParser.html]] {
        {static} #PUSHBACK_BUFFER_SIZE: int
        {static} +PROP_ALLOWHTML: String
        {static} +PROP_RUNPLUGINS: String
        {static} +PROP_USEOUTLINKIMAGE: String
        {static} +PROP_USERELNOFOLLOW: String
        {static} +HASHLINK: String
        {static} +OUTLINK_IMAGE: String
        {static} +OUTLINK: String
        {static} +CLASS_WIKIPAGE: String
        {static} +CLASS_EDITPAGE: String
        {static} +CLASS_INTERWIKI: String
        {static} +CLASS_FOOTNOTE: String
        {static} +CLASS_FOOTNOTE_REF: String
        {static} +CLASS_EXTERNAL: String
        {static} +CLASS_ATTACHMENT: String
        {static} +CLASS_TYPES: String[]
        #m_in: PushbackReader
        #m_engine: Engine
        #m_context: WikiContext
        #m_localLinkMutatorChain: ArrayList<StringTransmutator>
        #m_externalLinkMutatorChain: ArrayList<StringTransmutator>
        #m_attachmentLinkMutatorChain: ArrayList<StringTransmutator>
        #m_linkMutators: ArrayList<StringTransmutator>
        #m_headingListenerChain: ArrayList<HeadingListener>
        #m_inlineImages: boolean
        #m_parseAccessRules: boolean
        #m_inlineImagePatterns: List<Pattern>
        #m_linkParsingOperations: LinkParsingOperations
        #MarkupParser(WikiContext, Reader)
        +setInputReader(Reader): Reader
        +addLinkTransmutator(StringTransmutator): void
        +addLocalLinkHook(StringTransmutator): void
        +addExternalLinkHook(StringTransmutator): void
        +addAttachmentLinkHook(StringTransmutator): void
        +addHeadingListener(HeadingListener): void
        +disableAccessRules(): void
        +isParseAccessRules(): boolean
        +enableImageInlining(boolean): void
        +isImageInlining(): boolean
        #initInlineImagePatterns(): void
        +getInlineImagePatterns(): List<Pattern>
        +getPosition(): int
        #nextToken(): int
        #pushBack(int): void
        {static} +makeError(String): Element
        {static} +cleanLink(String): String
        {static} +wikifyLink(String): String
        {abstract} +parse(): WikiDocument
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
