@startuml

    class AtomAPIServlet [[AtomAPIServlet.html]] {
        +init(ServletConfig): void
        +doPost(HttpServletRequest, HttpServletResponse): void
        +doGet(HttpServletRequest, HttpServletResponse): void
        +doDelete(HttpServletRequest, HttpServletResponse): void
        +doPut(HttpServletRequest, HttpServletResponse): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
