@startuml

    class VariableManager [[VariableManager.html]] {
        {static} +VAR_ERROR: String
        {static} +VAR_MSG: String
        +VariableManager(Properties)
        +parseAndGetValue(WikiContext, String): String
        +expandVariables(WikiContext, String): String
        +getValue(WikiContext, String, String): String
        +getValue(WikiContext, String): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
