@startuml

    class WatchDog [[WatchDog.html]] {
        +WatchDog(Engine, Watchable)
        +WatchDog(Engine, Thread)
        {static} +getCurrentWatchDog(Engine): WatchDog
        +enable(): void
        +disable(): void
        +enterState(String): void
        +enterState(String, int): void
        +exitState(): void
        +exitState(String): void
        +isStateStackNotEmpty(): boolean
        +isWatchableAlive(): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
