@startuml

    class WikiEngine [[WikiEngine.html]] {
        {static} +DEFAULT_INLINEPATTERN: String
        {static} +DEFAULT_TEMPLATE_NAME: String
        {static} +PROP_APPNAME: String
        {static} +PROP_INLINEIMAGEPTRN: String
        {static} +PROP_INTERWIKIREF: String
        {static} +PROP_STOREUSERNAME: String
        {static} +PROP_ENCODING: String
        {static} +PROP_NO_FILTER_ENCODING: String
        {static} +PROP_REFSTYLE: String
        {static} +PROP_BEAUTIFYTITLE: String
        {static} +PROP_WORKDIR: String
        {static} +PREFS_COOKIE_NAME: String
        {static} +PROP_MATCHPLURALS: String
        {static} +PROP_TEMPLATEDIR: String
        {static} +PROP_FRONTPAGE: String
        {static} +PROP_URLCONSTRUCTOR: String
        {static} +PROP_RUNFILTERS: String
        {static} +PROP_ACL_MANAGER_IMPL: String
        {static} +PROP_ALLOW_CREATION_OF_EMPTY_PAGES: String
        +WikiEngine(Properties)
        #WikiEngine(ServletContext, String, Properties)
        {static} +getInstance(ServletConfig): WikiEngine
        {static} +getInstance(ServletConfig, Properties): WikiEngine
        {static} +getInstance(ServletContext, Properties): WikiEngine
        +initReferenceManager(): void
        +getWikiProperties(): Properties
        +getWorkDir(): String
        +getTemplateDir(): String
        +getTemplateManager(): TemplateManager
        +getBaseURL(): String
        +getStartTime(): Date
        +getViewURL(String): String
        +getURL(String, String, String, boolean): String
        +getFrontPage(): String
        +getServletContext(): ServletContext
        +getInterWikiURL(String): String
        +getAllInterWikiLinks(): Collection<String>
        +getAllInlinedImagePatterns(): Collection<String>
        +getSpecialPageReference(String): String
        +getApplicationName(): String
        +beautifyTitle(String): String
        +beautifyTitleNoBreak(String): String
        +pageExists(String): boolean
        +pageExists(String, int): boolean
        +pageExists(WikiPage): boolean
        +getFinalPageName(String): String
        +encodeName(String): String
        +decodeName(String): String
        +getContentEncoding(): Charset
        +getWorkflowManager(): WorkflowManager
        +getText(String): String
        +getText(String, int): String
        +getText(WikiContext, WikiPage): String
        +getPureText(String, int): String
        +getPureText(WikiPage): String
        +getHTML(WikiContext, WikiPage): String
        +getHTML(String): String
        +getHTML(String, int): String
        +textToHTML(WikiContext, String): String
        #shutdown(): void
        +scanWikiLinks(WikiPage, String): Collection<String>
        +textToHTML(WikiContext, String, StringTransmutator, StringTransmutator): String
        +textToHTML(WikiContext, String, StringTransmutator, StringTransmutator, StringTransmutator): String
        +updateReferences(WikiPage): void
        +saveText(WikiContext, String): void
        +getPageCount(): int
        +getCurrentProvider(): String
        +getCurrentProviderInfo(): String
        +getRecentChanges(): Set<WikiPage>
        +getPage(String): WikiPage
        +getPage(String, int): WikiPage
        +getVersionHistory(String): List<?>
        +getReferenceManager(): ReferenceManager
        +getRenderingManager(): RenderingManager
        +getPluginManager(): T
        +getVariableManager(): VariableManager
        +getPageManager(): PageManager
        +getCommandResolver(): CommandResolver
        +getAttachmentManager(): AttachmentManager
        +getAuthorizationManager(): AuthorizationManager
        +getAuthenticationManager(): AuthenticationManager
        +getFilterManager(): T
        +getSearchManager(): SearchManager
        +getProgressManager(): ProgressManager
        +getRedirectURL(WikiContext): String
        +createContext(HttpServletRequest, String): WikiContext
        +deletePage(String): void
        +deleteVersion(WikiPage): void
        +getGlobalRSSURL(): String
        +getRootPath(): String
        +getURLConstructor(): URLConstructor
        +getRSSGenerator(): RSSGenerator
        +getPageRenamer(): PageRenamer
        +getUserManager(): UserManager
        +getTasksManager(): TasksManager
        +getGroupManager(): GroupManager
        +getAdminBeanManager(): AdminBeanManager
        +getAclManager(): AclManager
        +getDifferenceManager(): DifferenceManager
        +getEditorManager(): EditorManager
        +getInternationalizationManager(): InternationalizationManager
        +addWikiEventListener(WikiEventListener): void
        +removeWikiEventListener(WikiEventListener): void
        #fireEvent(int): void
        #firePageEvent(int, String): void
        +setAttribute(String, Object): void
        +getAttribute(String): Object
        +removeAttribute(String): Object
        +getCurrentWatchDog(): WatchDog
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
