@startuml

    class WikiContext [[WikiContext.html]] {
        {static} +ADMIN: String
        {static} +ATTACH: String
        {static} +COMMENT: String
        {static} +CONFLICT: String
        {static} +CREATE_GROUP: String
        {static} +DELETE: String
        {static} +DELETE_GROUP: String
        {static} +DIFF: String
        {static} +EDIT: String
        {static} +EDIT_GROUP: String
        {static} +ERROR: String
        {static} +FIND: String
        {static} +INFO: String
        {static} +INSTALL: String
        {static} +LOGIN: String
        {static} +LOGOUT: String
        {static} +MESSAGE: String
        {static} +NONE: String
        {static} +OTHER: String
        {static} +PREFS: String
        {static} +PREVIEW: String
        {static} +RENAME: String
        {static} +RSS: String
        {static} +UPLOAD: String
        {static} +VIEW: String
        {static} +VIEW_GROUP: String
        {static} +WORKFLOW: String
        #m_request: HttpServletRequest
        +WikiContext(Engine, Page)
        +WikiContext(Engine, HttpServletRequest, Command)
        +WikiContext(Engine, HttpServletRequest, Page)
        +WikiContext(Engine, HttpServletRequest, String)
        +getContentTemplate(): String
        +getJSP(): String
        +setRealPage(Page): WikiPage
        +getRealPage(): WikiPage
        +getRedirectURL(): String
        +getEngine(): WikiEngine
        +getPage(): WikiPage
        +setPage(Page): void
        +getRequestContext(): String
        +setRequestContext(String): void
        +getTarget(): Object
        +getURLPattern(): String
        +getVariable(String): T
        +setVariable(String, Object): void
        +getBooleanWikiProperty(String, boolean): boolean
        +getHttpParameter(String): String
        +getHttpRequest(): HttpServletRequest
        +setTemplate(String): void
        +getName(): String
        +getTemplate(): String
        +getCurrentUser(): Principal
        +getViewURL(String): String
        +getURL(String, String): String
        +getURL(String, String, String): String
        +getCommand(): Command
        +deepClone(): WikiContext
        +getWikiSession(): WikiSession
        +requiredPermission(): Permission
        +targetedCommand(Object): Command
        +hasAdminPermissions(): boolean
        #setDefaultTemplate(HttpServletRequest): void
        {static} #findCommand(Engine, HttpServletRequest, Page): Command
        #updateCommand(String): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
