@startuml

    class WikiSession [[WikiSession.html]] {
        {static} +ANONYMOUS: String
        {static} +ASSERTED: String
        {static} +AUTHENTICATED: String
        #isInGroup(Group): boolean
        +isAsserted(): boolean
        +isAuthenticated(): boolean
        +isAnonymous(): boolean
        +getLoginPrincipal(): Principal
        +getUserPrincipal(): Principal
        +getLocale(): Locale
        +addMessage(String): void
        +addMessage(String, String): void
        +clearMessages(): void
        +clearMessages(String): void
        +getMessages(): String[]
        +getMessages(String): String[]
        +getPrincipals(): Principal[]
        +getRoles(): Principal[]
        {static} +removeWikiSession(WikiEngine, HttpServletRequest): void
        +hasPrincipal(Principal): boolean
        +actionPerformed(WikiEvent): void
        +invalidate(): void
        #injectGroupPrincipals(): void
        #injectUserProfilePrincipals(): void
        +getStatus(): String
        {static} +getWikiSession(WikiEngine, HttpServletRequest): WikiSession
        {static} +guestSession(WikiEngine): WikiSession
        {static} +sessions(WikiEngine): int
        {static} +userPrincipals(WikiEngine): Principal[]
        {static} +doPrivileged(WikiSession, PrivilegedAction<?>): Object
        {static} #isIPV4Address(String): boolean
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
