@startuml

    abstract class WikiBackgroundThread [[WikiBackgroundThread.html]] {
        +WikiBackgroundThread(Engine, int)
        +actionPerformed(WikiEvent): void
        +getEngine(): Engine
        +shutdown(): void
        +run(): void
        +shutdownTask(): void
        +startupTask(): void
        {abstract} +backgroundTask(): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
