@startuml

    class WikiEngine [[WikiEngine.html]] {
        #managers: Map<Class<?>, Object>
        +WikiEngine(Properties)
        #WikiEngine(ServletContext, String, Properties)
        {static} +getInstance(ServletConfig): WikiEngine
        {static} +getInstance(ServletConfig, Properties): WikiEngine
        {static} +getInstance(ServletContext, Properties): WikiEngine
        +getManager(Class<T>): T
        +isConfigured(): boolean
        +initReferenceManager(): void
        +getWikiProperties(): Properties
        +getWorkDir(): String
        +getTemplateDir(): String
        +getTemplateManager(): TemplateManager
        +getStartTime(): Date
        +getBaseURL(): String
        +getGlobalRSSURL(): String
        +getInterWikiURL(String): String
        +getURL(String, String, String): String
        +getFrontPage(): String
        +getServletContext(): ServletContext
        +getAllInterWikiLinks(): Collection<String>
        +getAllInlinedImagePatterns(): Collection<String>
        +getSpecialPageReference(String): String
        +getApplicationName(): String
        +getFinalPageName(String): String
        +encodeName(String): String
        +decodeName(String): String
        +getContentEncoding(): Charset
        +getWorkflowManager(): WorkflowManager
        +shutdown(): void
        +getReferenceManager(): ReferenceManager
        +getRenderingManager(): RenderingManager
        +getPluginManager(): PluginManager
        +getVariableManager(): VariableManager
        +getPageManager(): PageManager
        +getCommandResolver(): CommandResolver
        +getAttachmentManager(): AttachmentManager
        +getAuthorizationManager(): AuthorizationManager
        +getAuthenticationManager(): AuthenticationManager
        +getFilterManager(): FilterManager
        +getSearchManager(): SearchManager
        +getProgressManager(): ProgressManager
        +getRootPath(): String
        +getURLConstructor(): URLConstructor
        +getRSSGenerator(): RSSGenerator
        +getPageRenamer(): PageRenamer
        +getUserManager(): UserManager
        +getTasksManager(): TasksManager
        +getGroupManager(): GroupManager
        +getAdminBeanManager(): AdminBeanManager
        +getAclManager(): AclManager
        +getDifferenceManager(): DifferenceManager
        +getEditorManager(): EditorManager
        +getInternationalizationManager(): InternationalizationManager
        +addWikiEventListener(WikiEventListener): void
        +removeWikiEventListener(WikiEventListener): void
        #fireEvent(int): void
        #firePageEvent(int, String): void
        +setAttribute(String, Object): void
        +getAttribute(String): T
        +removeAttribute(String): T
        +getCurrentWatchDog(): WatchDog
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
