@startuml

    class WikiSession [[WikiSession.html]] {
        #isInGroup(Group): boolean
        +isAsserted(): boolean
        +isAuthenticated(): boolean
        +isAnonymous(): boolean
        +getLoginPrincipal(): Principal
        +getUserPrincipal(): Principal
        +getLocale(): Locale
        +addMessage(String): void
        +addMessage(String, String): void
        +clearMessages(): void
        +clearMessages(String): void
        +getMessages(): String[]
        +getMessages(String): String[]
        +getPrincipals(): Principal[]
        +getRoles(): Principal[]
        +hasPrincipal(Principal): boolean
        +actionPerformed(WikiEvent): void
        +invalidate(): void
        #injectGroupPrincipals(): void
        #injectUserProfilePrincipals(): void
        +getStatus(): String
        +getSubject(): Subject
        {static} +removeWikiSession(Engine, HttpServletRequest): void
        {static} +getWikiSession(Engine, HttpServletRequest): Session
        {static} +guestSession(Engine): Session
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
