@startuml

    abstract class AbstractUserDatabase [[AbstractUserDatabase.html]] {
        {static} #log: Logger
        {static} #SHA_PREFIX: String
        {static} #SSHA_PREFIX: String
        +find(String): UserProfile
        +getPrincipals(String): Principal[]
        +newProfile(): UserProfile
        +validatePassword(String, String): boolean
        {static} #generateUid(UserDatabase): String
        #getHash(String): String
        #parseLong(String): long
        {abstract} +findByEmail(String): UserProfile
        {abstract} +findByFullName(String): UserProfile
        {abstract} +findByLoginName(String): UserProfile
        {abstract} +findByWikiName(String): UserProfile
        {abstract} +initialize(WikiEngine, Properties): void
        {abstract} +save(UserProfile): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
