@startuml

    class JDBCUserDatabase [[JDBCUserDatabase.html]] {
        {static} +DEFAULT_DB_ATTRIBUTES: String
        {static} +DEFAULT_DB_CREATED: String
        {static} +DEFAULT_DB_EMAIL: String
        {static} +DEFAULT_DB_FULL_NAME: String
        {static} +DEFAULT_DB_JNDI_NAME: String
        {static} +DEFAULT_DB_LOCK_EXPIRY: String
        {static} +DEFAULT_DB_MODIFIED: String
        {static} +DEFAULT_DB_ROLE: String
        {static} +DEFAULT_DB_ROLE_TABLE: String
        {static} +DEFAULT_DB_TABLE: String
        {static} +DEFAULT_DB_LOGIN_NAME: String
        {static} +DEFAULT_DB_PASSWORD: String
        {static} +DEFAULT_DB_UID: String
        {static} +DEFAULT_DB_WIKI_NAME: String
        {static} +PROP_DB_ATTRIBUTES: String
        {static} +PROP_DB_CREATED: String
        {static} +PROP_DB_EMAIL: String
        {static} +PROP_DB_FULL_NAME: String
        {static} +PROP_DB_DATASOURCE: String
        {static} +PROP_DB_LOCK_EXPIRY: String
        {static} +PROP_DB_LOGIN_NAME: String
        {static} +PROP_DB_MODIFIED: String
        {static} +PROP_DB_PASSWORD: String
        {static} +PROP_DB_UID: String
        {static} +PROP_DB_ROLE: String
        {static} +PROP_DB_ROLE_TABLE: String
        {static} +PROP_DB_TABLE: String
        {static} +PROP_DB_WIKI_NAME: String
        +deleteByLoginName(String): void
        +findByEmail(String): UserProfile
        +findByFullName(String): UserProfile
        +findByLoginName(String): UserProfile
        +findByUid(String): UserProfile
        +findByWikiName(String): UserProfile
        +getWikiNames(): Principal[]
        +initialize(WikiEngine, Properties): void
        +rename(String, String): void
        +save(UserProfile): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
