@startuml

    class MarkdownDocument [[MarkdownDocument.html]] {
        +MarkdownDocument(Page, Node)
        +getMarkdownNode(): Node
        {static} +options(Context, boolean, List<Pattern>): MutableDataSet
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
