@startuml

    namespace org.apache.wiki.parser.markdown {

        class MarkdownDocument [[MarkdownDocument.html]] {
            +MarkdownDocument(Page, Node)
            +getMarkdownNode(): Node
            {static} +options(Context, boolean, List<Pattern>): MutableDataSet
        }

        class MarkdownParser [[MarkdownParser.html]] {
            +MarkdownParser(Context, Reader)
            +parse(): WikiDocument
        }

        class org.apache.wiki.parser.WikiDocument
        org.apache.wiki.parser.WikiDocument <|-- MarkdownDocument

        abstract class org.apache.wiki.parser.MarkupParser {
            {abstract} +parse(): WikiDocument
        }
        org.apache.wiki.parser.MarkupParser <|-- MarkdownParser

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
