@startuml

    namespace org.apache.wiki.parser.markdown {

        class MarkdownParser [[MarkdownParser.html]] {
            +MarkdownParser(WikiContext, Reader)
            +parse(): WikiDocument
        }

        class MarkdownDocument [[MarkdownDocument.html]] {
            +MarkdownDocument(WikiPage, Node)
            +getMarkdownNode(): Node
            {static} +options(WikiContext): MutableDataSet
        }

        abstract class org.apache.wiki.parser.MarkupParser {
            {abstract} +parse(): WikiDocument
        }
        org.apache.wiki.parser.MarkupParser <|-- MarkdownParser

        class org.apache.wiki.parser.WikiDocument
        org.apache.wiki.parser.WikiDocument <|-- MarkdownDocument

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
