@startuml

    class DefaultFilterManager [[DefaultFilterManager.html]] {
        +DefaultFilterManager(Engine, Properties)
        +addPageFilter(PageFilter, int): void
        #initialize(Properties): void
        +doPreTranslateFiltering(WikiContext, String): String
        +doPostTranslateFiltering(WikiContext, String): String
        +doPreSaveFiltering(WikiContext, String): String
        +doPostSaveFiltering(WikiContext, String): void
        +getFilterList(): List<PageFilter>
        +destroy(): void
        +fireEvent(int, WikiContext): void
        +modules(): Collection<WikiModuleInfo>
        +getModuleInfo(String): DefaultFilterManager.PageFilterInfo
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
