@startuml

    namespace org.apache.wiki.filters {

        class CreoleFilter [[CreoleFilter.html]] {
            +initialize(Engine, Properties): void
            +preSave(WikiContext, String): String
            +preTranslate(WikiContext, String): String
        }

        interface FilterManager [[FilterManager.html]] {
            {static} +PROP_FILTERXML: String
            {static} +DEFAULT_XMLFILE: String
            {static} +SYSTEM_FILTER_PRIORITY: int
            {static} +USER_FILTER_PRIORITY: int
            {abstract} +addPageFilter(PageFilter, int): void
            {abstract} +doPreTranslateFiltering(WikiContext, String): String
            {abstract} +doPostTranslateFiltering(WikiContext, String): String
            {abstract} +doPreSaveFiltering(WikiContext, String): String
            {abstract} +doPostSaveFiltering(WikiContext, String): void
            {abstract} +getFilterList(): List<PageFilter>
            {abstract} +destroy(): void
        }

        class PageEventFilter [[PageEventFilter.html]] {
            +initialize(Properties): void
            +preTranslate(WikiContext, String): String
            +postTranslate(WikiContext, String): String
            +preSave(WikiContext, String): String
            +postSave(WikiContext, String): void
            +addWikiEventListener(WikiEventListener): void
            +removeWikiEventListener(WikiEventListener): void
            #fireEvent(int, WikiContext): void
        }

        class DefaultFilterManager [[DefaultFilterManager.html]] {
            +DefaultFilterManager(Engine, Properties)
            +addPageFilter(PageFilter, int): void
            #initialize(Properties): void
            +doPreTranslateFiltering(WikiContext, String): String
            +doPostTranslateFiltering(WikiContext, String): String
            +doPreSaveFiltering(WikiContext, String): String
            +doPostSaveFiltering(WikiContext, String): void
            +getFilterList(): List<PageFilter>
            +destroy(): void
            +fireEvent(int, WikiContext): void
            +modules(): Collection<WikiModuleInfo>
            +getModuleInfo(String): DefaultFilterManager.PageFilterInfo
        }

        class PingWeblogsComFilter [[PingWeblogsComFilter.html]] {
            {static} +PROP_PINGURL: String
            +initialize(Engine, Properties): void
            +postSave(WikiContext, String): void
        }

        class SpamFilter [[SpamFilter.html]] {
            {static} +PROP_WORDLIST: String
            {static} +PROP_IPLIST: String
            {static} +PROP_MAX_PAGENAME_LENGTH: String
            {static} +PROP_ERRORPAGE: String
            {static} +PROP_PAGECHANGES: String
            {static} +PROP_SIMILARCHANGES: String
            {static} +PROP_BANTIME: String
            {static} +PROP_BLACKLIST: String
            {static} +PROP_MAXURLS: String
            {static} +PROP_AKISMET_API_KEY: String
            {static} +PROP_IGNORE_AUTHENTICATED: String
            {static} +PROP_CAPTCHA: String
            {static} +PROP_FILTERSTRATEGY: String
            {static} +STRATEGY_EAGER: String
            {static} +STRATEGY_SCORE: String
            +initialize(Engine, Properties): void
            +preSave(WikiContext, String): String
            {static} +getBotFieldName(): String
            +isValidUserProfile(WikiContext, UserProfile): boolean
            {static} +getSpamHash(WikiPage, HttpServletRequest): String
            {static} +getHashFieldName(HttpServletRequest): String
            {static} +checkHash(WikiContext, PageContext): boolean
            {static} +insertInputFields(PageContext): String
        }

        class ProfanityFilter [[ProfanityFilter.html]] {
            +preTranslate(WikiContext, String): String
        }

        class org.apache.wiki.api.filters.BasicPageFilter
        org.apache.wiki.api.filters.BasicPageFilter <|-- CreoleFilter

        interface org.apache.wiki.modules.ModuleManager {
            {abstract} +checkCompatibility(WikiModuleInfo): boolean
            {abstract} +getModuleInfo(String): WikiModuleInfo
            {abstract} +modules(): Collection<WikiModuleInfo>
        }
        org.apache.wiki.modules.ModuleManager <|.. FilterManager

        org.apache.wiki.api.filters.BasicPageFilter <|-- PageEventFilter

        abstract class org.apache.wiki.modules.BaseModuleManager
        org.apache.wiki.modules.BaseModuleManager <|-- DefaultFilterManager

        FilterManager <|.. DefaultFilterManager

        org.apache.wiki.api.filters.BasicPageFilter <|-- PingWeblogsComFilter

        org.apache.wiki.api.filters.BasicPageFilter <|-- SpamFilter

        org.apache.wiki.api.filters.BasicPageFilter <|-- ProfanityFilter

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
