@startuml

    class SpamFilter [[SpamFilter.html]] {
        {static} +PROP_WORDLIST: String
        {static} +PROP_IPLIST: String
        {static} +PROP_MAX_PAGENAME_LENGTH: String
        {static} +PROP_ERRORPAGE: String
        {static} +PROP_PAGECHANGES: String
        {static} +PROP_SIMILARCHANGES: String
        {static} +PROP_BANTIME: String
        {static} +PROP_BLACKLIST: String
        {static} +PROP_MAXURLS: String
        {static} +PROP_AKISMET_API_KEY: String
        {static} +PROP_IGNORE_AUTHENTICATED: String
        {static} +PROP_CAPTCHA: String
        {static} +PROP_FILTERSTRATEGY: String
        {static} +STRATEGY_EAGER: String
        {static} +STRATEGY_SCORE: String
        +initialize(WikiEngine, Properties): void
        +preSave(WikiContext, String): String
        {static} +getBotFieldName(): String
        +isValidUserProfile(WikiContext, UserProfile): boolean
        {static} +getSpamHash(WikiPage, HttpServletRequest): String
        {static} +getHashFieldName(HttpServletRequest): String
        {static} +checkHash(WikiContext, PageContext): boolean
        {static} +insertInputFields(PageContext): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
