@startuml

    interface UserProfile [[UserProfile.html]] {
        {abstract} +getAttributes(): Map<String, Serializable>
        {abstract} +getCreated(): Date
        {abstract} +getEmail(): String
        {abstract} +getFullname(): String
        {abstract} +getLastModified(): Date
        {abstract} +getLockExpiry(): Date
        {abstract} +getLoginName(): String
        {abstract} +getPassword(): String
        {abstract} +getUid(): String
        {abstract} +getWikiName(): String
        {abstract} +isLocked(): boolean
        {abstract} +isNew(): boolean
        {abstract} +setCreated(Date): void
        {abstract} +setEmail(String): void
        {abstract} +setFullname(String): void
        {abstract} +setLastModified(Date): void
        {abstract} +setLockExpiry(Date): void
        {abstract} +setLoginName(String): void
        {abstract} +setPassword(String): void
        {abstract} +setUid(String): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
