@startuml

    class XMLUserDatabase [[XMLUserDatabase.html]] {
        {static} +PROP_USERDATABASE: String
        +deleteByLoginName(String): void
        +findByEmail(String): UserProfile
        +findByFullName(String): UserProfile
        +findByLoginName(String): UserProfile
        +findByUid(String): UserProfile
        +findByWikiName(String): UserProfile
        +getWikiNames(): Principal[]
        +initialize(Engine, Properties): void
        +rename(String, String): void
        +save(UserProfile): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
