@startuml

    class LocalLinkAttributeProviderState [[LocalLinkAttributeProviderState.html]] {
        +LocalLinkAttributeProviderState(Context, boolean, boolean, List<Pattern>)
        +setAttributes(MutableAttributes, JSPWikiLink): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
