@startuml

    namespace org.apache.wiki.markdown.extensions.jspwikilinks.attributeprovider {

        class ExternalLinkAttributeProviderState [[ExternalLinkAttributeProviderState.html]] {
            +ExternalLinkAttributeProviderState(Context, boolean, boolean, List<Pattern>)
            +setAttributes(MutableAttributes, JSPWikiLink): void
        }

        class JSPWikiLinkAttributeProvider [[JSPWikiLinkAttributeProvider.html]] {
            #wikiContext: Context
            #linkOperations: LinkParsingOperations
            +JSPWikiLinkAttributeProvider(Context, boolean, List<Pattern>)
            +setAttributes(Node, AttributablePart, MutableAttributes): void
        }

        interface NodeAttributeProviderState<T> [[NodeAttributeProviderState.html]] {
            {abstract} +setAttributes(MutableAttributes, T): void
        }

        class LocalFootnoteLinkAttributeProviderState [[LocalFootnoteLinkAttributeProviderState.html]] {
            +LocalFootnoteLinkAttributeProviderState(Context)
            +setAttributes(MutableAttributes, JSPWikiLink): void
        }

        class ImageLinkAttributeProviderState [[ImageLinkAttributeProviderState.html]] {
            +ImageLinkAttributeProviderState(Context, String, boolean)
            +setAttributes(MutableAttributes, JSPWikiLink): void
        }

        class WysiwygEditingAttributeProviderState [[WysiwygEditingAttributeProviderState.html]] {
            +WysiwygEditingAttributeProviderState(Context)
            +setAttributes(MutableAttributes, JSPWikiLink): void
        }

        class LocalLinkAttributeProviderState [[LocalLinkAttributeProviderState.html]] {
            +LocalLinkAttributeProviderState(Context, boolean, boolean, List<Pattern>)
            +setAttributes(MutableAttributes, JSPWikiLink): void
        }

        class LocalReadLinkAttributeProviderState [[LocalReadLinkAttributeProviderState.html]] {
            +LocalReadLinkAttributeProviderState(Context)
            +setAttributes(MutableAttributes, JSPWikiLink): void
        }

        class InterWikiLinkAttributeProviderState [[InterWikiLinkAttributeProviderState.html]] {
            +InterWikiLinkAttributeProviderState(Context, boolean, boolean, List<Pattern>)
            +setAttributes(MutableAttributes, JSPWikiLink): void
        }

        class LocalEditLinkAttributeProviderState [[LocalEditLinkAttributeProviderState.html]] {
            +LocalEditLinkAttributeProviderState(Context, String)
            +setAttributes(MutableAttributes, JSPWikiLink): void
        }

        class LocalFootnoteRefLinkAttributeProviderState [[LocalFootnoteRefLinkAttributeProviderState.html]] {
            +LocalFootnoteRefLinkAttributeProviderState(Context)
            +setAttributes(MutableAttributes, JSPWikiLink): void
        }

        class JSPWikiLinkAttributeProviderFactory [[JSPWikiLinkAttributeProviderFactory.html]] {
            +JSPWikiLinkAttributeProviderFactory(Context, boolean, List<Pattern>)
            +apply(LinkResolverContext): AttributeProvider
        }

        NodeAttributeProviderState <|.. ExternalLinkAttributeProviderState

        interface com.vladsch.flexmark.html.AttributeProvider {
            {abstract} +setAttributes(Node, AttributablePart, MutableAttributes): void
        }
        com.vladsch.flexmark.html.AttributeProvider <|.. JSPWikiLinkAttributeProvider

        NodeAttributeProviderState <|.. LocalFootnoteLinkAttributeProviderState

        NodeAttributeProviderState <|.. ImageLinkAttributeProviderState

        NodeAttributeProviderState <|.. WysiwygEditingAttributeProviderState

        NodeAttributeProviderState <|.. LocalLinkAttributeProviderState

        NodeAttributeProviderState <|.. LocalReadLinkAttributeProviderState

        NodeAttributeProviderState <|.. InterWikiLinkAttributeProviderState

        NodeAttributeProviderState <|.. LocalEditLinkAttributeProviderState

        NodeAttributeProviderState <|.. LocalFootnoteRefLinkAttributeProviderState

        abstract class com.vladsch.flexmark.html.IndependentAttributeProviderFactory
        com.vladsch.flexmark.html.IndependentAttributeProviderFactory <|-- JSPWikiLinkAttributeProviderFactory

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
