@startuml

    class UserManager.JSONUserModule [[UserManager.JSONUserModule.html]] {
        +JSONUserModule(UserManager)
        +getServletMapping(): String
        +service(HttpServletRequest, HttpServletResponse, String, List<String>): void
        +getUserInfo(String): UserProfile
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
