@startuml

    class TwoXFilter <<deprecated>> [[TwoXFilter.html]] {
        + --initialize-- (WikiEngine, Properties): void
        + --postTranslate-- (WikiContext, String): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
