@startuml

    class WikiPermission [[WikiPermission.html]] {
        {static} +CREATE_GROUPS_ACTION: String
        {static} +CREATE_PAGES_ACTION: String
        {static} +LOGIN_ACTION: String
        {static} +EDIT_PREFERENCES_ACTION: String
        {static} +EDIT_PROFILE_ACTION: String
        {static} +WILDCARD: String
        {static} #CREATE_GROUPS_MASK: int
        {static} #CREATE_PAGES_MASK: int
        {static} #EDIT_PREFERENCES_MASK: int
        {static} #EDIT_PROFILE_MASK: int
        {static} #LOGIN_MASK: int
        {static} +CREATE_GROUPS: WikiPermission
        {static} +CREATE_PAGES: WikiPermission
        {static} +LOGIN: WikiPermission
        {static} +EDIT_PREFERENCES: WikiPermission
        {static} +EDIT_PROFILE: WikiPermission
        +WikiPermission(String, String)
        +getActions(): String
        +getWiki(): String
        +implies(Permission): boolean
        +newPermissionCollection(): PermissionCollection
        {static} #impliedMask(int): int
        {static} #createMask(String): int
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
