@startuml

    interface AuthenticationManager [[AuthenticationManager.html]] {
        {static} +PROP_STOREIPADDRESS: String
        {static} +PROP_ALLOW_COOKIE_AUTH: String
        {static} +PROP_LOGIN_THROTTLING: String
        {static} +PREFIX_LOGIN_MODULE_OPTIONS: String
        {static} +PROP_ALLOW_COOKIE_ASSERTIONS: String
        {static} +PROP_LOGIN_MODULE: String
        {static} +isRolePrincipal(Principal): boolean
        {static} +isUserPrincipal(Principal): boolean
        +getLoginPrincipal(Set<Principal>): Principal
        +fireEvent(int, Principal, Object): void
        {abstract} +isContainerAuthenticated(): boolean
        {abstract} +login(HttpServletRequest): boolean
        {abstract} +login(Session, HttpServletRequest, String, String): boolean
        {abstract} +logout(HttpServletRequest): void
        {abstract} +allowsCookieAssertions(): boolean
        {abstract} +allowsCookieAuthentication(): boolean
        {abstract} +doJAASLogin(Class<?>, CallbackHandler, Map<String, String>): Set<Principal>
        {abstract} +addWikiEventListener(WikiEventListener): void
        {abstract} +removeWikiEventListener(WikiEventListener): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
