@startuml

    class DefaultUserManager [[DefaultUserManager.html]] {
        +initialize(Engine, Properties): void
        +getUserDatabase(): UserDatabase
        +getUserProfile(Session): UserProfile
        +setUserProfile(Context, UserProfile): void
        +startUserProfileCreationWorkflow(Context, UserProfile): void
        +parseProfile(Context): UserProfile
        +validateProfile(Context, UserProfile): void
        +listWikiNames(): Principal[]
        +addWikiEventListener(WikiEventListener): void
        +removeWikiEventListener(WikiEventListener): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
