@startuml

    interface UserManager [[UserManager.html]] {
        {static} +PROP_DATABASE: String
        {static} +JSON_USERS: String
        +fireEvent(int, Session, Object): void
        {abstract} +getUserDatabase(): UserDatabase
        {abstract} +getUserProfile(Session): UserProfile
        {abstract} +setUserProfile(Context, UserProfile): void
        {abstract} +startUserProfileCreationWorkflow(Context, UserProfile): void
        {abstract} +parseProfile(Context): UserProfile
        {abstract} +validateProfile(Context, UserProfile): void
        {abstract} +listWikiNames(): Principal[]
        {abstract} +addWikiEventListener(WikiEventListener): void
        {abstract} +removeWikiEventListener(WikiEventListener): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
