@startuml

    class WikiEventManager [[WikiEventManager.html]] {
        {static} +getInstance(): WikiEventManager
        {static} +addWikiEventListener(Object, WikiEventListener): boolean
        {static} +removeWikiEventListener(Object, WikiEventListener): boolean
        {static} +getWikiEventListeners(Object): Set<WikiEventListener>
        {static} +removeWikiEventListener(WikiEventListener): boolean
        {static} +isListening(Object): boolean
        {static} +fireEvent(Object, WikiEvent): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
