@startuml

    abstract class WikiRenderer [[WikiRenderer.html]] {
        {static} +LINKS_TRANSLATION: String
        {static} +LINKS_SOURCE: String
        #m_context: WikiContext
        #m_document: WikiDocument
        #WikiRenderer(WikiContext, WikiDocument)
        {abstract} +getString(): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
