@startuml

    class MetaWeblogHandler [[MetaWeblogHandler.html]] {
        +initialize(WikiContext): void
        +getCategories(String, String, String): Hashtable
        +getRecentPosts(String, String, String, int): Hashtable
        +newPost(String, String, String, Hashtable, boolean): String
        +newMediaObject(String, String, String, Hashtable): Hashtable
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
