@startuml

    class FormUtil [[FormUtil.html]] {
        {static} +getValues(Map<?, ?>, String): List<?>
        {static} +getNumberedValues(Map<?, ?>, String): List<?>
        {static} +requestToMap(HttpServletRequest, String): Map<String, String>
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
