@startuml

    class MailUtil [[MailUtil.html]] {
        {static} #log: Logger
        {static} #DEFAULT_MAIL_JNDI_NAME: String
        {static} #DEFAULT_MAIL_HOST: String
        {static} #DEFAULT_MAIL_PORT: String
        {static} #DEFAULT_MAIL_TIMEOUT: String
        {static} #DEFAULT_MAIL_CONN_TIMEOUT: String
        {static} #DEFAULT_SENDER: String
        {static} #PROP_MAIL_JNDI_NAME: String
        {static} #PROP_MAIL_HOST: String
        {static} #PROP_MAIL_PORT: String
        {static} #PROP_MAIL_ACCOUNT: String
        {static} #PROP_MAIL_PASSWORD: String
        {static} #PROP_MAIL_TIMEOUT: String
        {static} #PROP_MAIL_CONNECTION_TIMEOUT: String
        {static} #PROP_MAIL_TRANSPORT: String
        {static} #PROP_MAIL_SENDER: String
        {static} #PROP_MAIL_STARTTLS: String
        {static} +sendMessage(Properties, String, String, String): void
        {static} #getSenderEmailAddress(Session, Properties): String
        {static} #getStandaloneMailSession(Properties): Session
        {static} #getJNDIMailSession(String): Session
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
