@startuml

    class XmlUtil [[XmlUtil.html]] {
        {static} +parse(String, String): List<Element>
        {static} +parse(InputStream, String): List<Element>
        {static} +extractTextFromDocument(Document): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
