@startuml

    namespace org.apache.wiki.api.filters {

        class BasePageFilter [[BasePageFilter.html]] {
            #m_engine: Engine
            +initialize(Engine, Properties): void
        }

        interface PageFilter [[PageFilter.html]] {
            +preTranslate(Context, String): String
            +postTranslate(Context, String): String
            +preSave(Context, String): String
            +postSave(Context, String): void
            +destroy(Engine): void
            {abstract} +initialize(Engine, Properties): void
        }

        PageFilter <|.. BasePageFilter

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
