@startuml

    interface PageFilter [[PageFilter.html]] {
        +preTranslate(Context, String): String
        +postTranslate(Context, String): String
        +preSave(Context, String): String
        +postSave(Context, String): void
        +destroy(Engine): void
        {abstract} +initialize(Engine, Properties): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
