@startuml

    class Heading [[Heading.html]] {
        {static} +HEADING_SMALL: int
        {static} +HEADING_MEDIUM: int
        {static} +HEADING_LARGE: int
        +m_level: int
        +m_titleText: String
        +m_titleAnchor: String
        +m_titleSection: String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
