@startuml

    class LinkParser.Link [[LinkParser.Link.html]] {
        #Link(String)
        #Link(String, String)
        #setText(String): void
        +getText(): String
        #setReference(String): void
        +hasReference(): boolean
        +getReference(): String
        +isInterwikiLink(): boolean
        +getExternalWiki(): String
        +getExternalWikiPage(): String
        +attributeCount(): int
        +addAttribute(Attribute): void
        +getAttributes(): Iterator<Attribute>
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
