@startuml

    class WikiDocument [[WikiDocument.html]] {
        +WikiDocument(Page)
        +setPageData(String): void
        +getPageData(): String
        +getPage(): Page
        +setContext(Context): void
        +getContext(): Context
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
