@startuml

    class DefaultPageManager [[DefaultPageManager.html]] {
        #m_pageLocks: ConcurrentHashMap<String, PageLock>
        +DefaultPageManager(WikiEngine, Properties)
        +getProvider(): WikiPageProvider
        +getAllPages(): Collection<WikiPage>
        +getPageText(String, int): String
        +getEngine(): WikiEngine
        +putPageText(WikiPage, String): void
        +lockPage(WikiPage, String): PageLock
        +unlockPage(PageLock): void
        +getCurrentLock(WikiPage): PageLock
        +getActiveLocks(): List<PageLock>
        +getPageInfo(String, int): WikiPage
        +getVersionHistory(String): List<WikiPage>
        +getProviderDescription(): String
        +getTotalPageCount(): int
        +pageExists(String): boolean
        +pageExists(String, int): boolean
        +deleteVersion(WikiPage): void
        +deletePage(WikiPage): void
        #fireEvent(int, String): void
        +modules(): Collection<WikiModuleInfo>
        +getModuleInfo(String): WikiModuleInfo
        +actionPerformed(WikiEvent): void
        #changeAcl(WikiPage, Principal[], Principal): boolean
        +getPageSorter(): PageSorter
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
