@startuml

    class PageSorter [[PageSorter.html]] {
        {static} #PROP_PAGE_NAME_COMPARATOR: String
        +PageSorter()
        +PageSorter(Comparator<String>)
        +compare(String, String): int
        +initialize(Properties): void
        +sort(List<String>): void
        +sort(String[]): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
