@startuml

    namespace org.apache.wiki.management {

        abstract class SimpleMBean [[SimpleMBean.html]] {
            #m_beanInfo: MBeanInfo
            #getDescription(): String
            +getAttribute(String): Object
            +getAttributes(String[]): AttributeList
            +getMBeanInfo(): MBeanInfo
            +invoke(String, Object[], String[]): Object
            +setAttribute(Attribute): void
            +setAttributes(AttributeList): AttributeList
            {abstract} +getAttributeNames(): String[]
            {abstract} +getMethodNames(): String[]
        }

        interface javax.management.DynamicMBean {
            {abstract} +getAttribute(String): Object
            {abstract} +setAttribute(Attribute): void
            {abstract} +getAttributes(String[]): AttributeList
            {abstract} +setAttributes(AttributeList): AttributeList
            {abstract} +invoke(String, Object[], String[]): Object
            {abstract} +getMBeanInfo(): MBeanInfo
        }
        javax.management.DynamicMBean <|.. SimpleMBean

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
