@startuml

    class CoreBean [[CoreBean.html]] {
        +CoreBean(Engine)
        +getPages(): int
        +getPagesDescription(): String
        +getVersion(): String
        +getVersionDescription(): String
        +getTitle(): String
        +getType(): int
        +getId(): String
        +getAttributeNames(): String[]
        +getMethodNames(): String[]
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
