@startuml

    abstract class ModuleBean [[ModuleBean.html]] {
        +ModuleBean(Engine)
        +getAttributeNames(): String[]
        +getMethodNames(): String[]
        +doGet(WikiContext): String
        #title(): Element
        #containerForModuleDetail(Element): Element
        #validModuleVersion(WikiModuleInfo): String
        {abstract} #modules(): Collection<WikiModuleInfo>
        {abstract} #heading(): Element
        {abstract} #rowBody(WikiModuleInfo): Element
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
