@startuml

    namespace org.apache.wiki.ui.admin.beans {

        class SearchManagerBean [[SearchManagerBean.html]] {
            +SearchManagerBean(Engine)
            +getAttributeNames(): String[]
            +getMethodNames(): String[]
            +getTitle(): String
            +reload(): void
            +getType(): int
            +doGet(Context): String
            +doPost(Context): String
        }

        class CoreBean [[CoreBean.html]] {
            +CoreBean(Engine)
            +getPages(): int
            +getPagesDescription(): String
            +getVersion(): String
            +getVersionDescription(): String
            +getTitle(): String
            +getType(): int
            +getId(): String
            +getAttributeNames(): String[]
            +getMethodNames(): String[]
        }

        class PlainEditorAdminBean [[PlainEditorAdminBean.html]] {
            +doGet(Context): String
            +doPost(Context): String
            +getTitle(): String
            +getType(): int
            +isEnabled(): boolean
            +getId(): String
            +getChecked(): boolean
            +getAttributeNames(): String[]
            +getMethodNames(): String[]
            +initialize(Engine): void
        }

        class PluginBean [[PluginBean.html]] {
            +PluginBean(Engine)
            +getTitle(): String
            +getType(): int
            #modules(): Collection<WikiModuleInfo>
            #heading(): Element
            #rowBody(WikiModuleInfo): Element
        }

        abstract class ModuleBean [[ModuleBean.html]] {
            +ModuleBean(Engine)
            +getAttributeNames(): String[]
            +getMethodNames(): String[]
            +doGet(Context): String
            #title(): Element
            #containerForModuleDetail(Element): Element
            #validModuleVersion(WikiModuleInfo): String
            {abstract} #modules(): Collection<WikiModuleInfo>
            {abstract} #heading(): Element
            {abstract} #rowBody(WikiModuleInfo): Element
        }

        class UserBean [[UserBean.html]] {
            +UserBean(Engine)
            +getAttributeNames(): String[]
            +getMethodNames(): String[]
            +doPost(Context): String
            +getTitle(): String
            +getType(): int
        }

        class FilterBean [[FilterBean.html]] {
            +FilterBean(Engine)
            +getTitle(): String
            +getType(): int
            #modules(): Collection<WikiModuleInfo>
            #heading(): Element
            #rowBody(WikiModuleInfo): Element
        }

        abstract class org.apache.wiki.ui.admin.SimpleAdminBean
        org.apache.wiki.ui.admin.SimpleAdminBean <|-- SearchManagerBean

        org.apache.wiki.ui.admin.SimpleAdminBean <|-- CoreBean

        abstract class org.apache.wiki.management.SimpleMBean {
            {abstract} +getAttributeNames(): String[]
            {abstract} +getMethodNames(): String[]
        }
        org.apache.wiki.management.SimpleMBean <|-- PlainEditorAdminBean

        interface org.apache.wiki.ui.admin.AdminBean {
            {abstract} +initialize(Engine): void
            {abstract} +getTitle(): String
            {abstract} +getType(): int
        }
        org.apache.wiki.ui.admin.AdminBean <|.. PlainEditorAdminBean

        ModuleBean <|-- PluginBean

        org.apache.wiki.ui.admin.SimpleAdminBean <|-- ModuleBean

        org.apache.wiki.ui.admin.SimpleAdminBean <|-- UserBean

        ModuleBean <|-- FilterBean

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
