@startuml

    class PlainEditorAdminBean [[PlainEditorAdminBean.html]] {
        +doGet(WikiContext): String
        +doPost(WikiContext): String
        +getTitle(): String
        +getType(): int
        +isEnabled(): boolean
        +getId(): String
        +getChecked(): boolean
        +getAttributeNames(): String[]
        +getMethodNames(): String[]
        +initialize(Engine): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
