@startuml

    class DefaultURLConstructor [[DefaultURLConstructor.html]] {
        #m_engine: WikiEngine
        #m_pathPrefix: String
        +initialize(WikiEngine, Properties): void
        #doReplacement(String, String): String
        {static} +getURLPattern(String, String): String
        +makeURL(String, String, String): String
        +parsePage(String, HttpServletRequest, Charset): String
        {static} +parsePageFromURL(HttpServletRequest, Charset): String
        +getForwardPage(HttpServletRequest): String
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
