@startuml

    namespace org.apache.wiki.url {

        class ShortURLConstructor [[ShortURLConstructor.html]] {
            {static} +PROP_PREFIX: String
            #m_urlPrefix: String
            +initialize(WikiEngine, Properties): void
            +makeURL(String, String, boolean, String): String
            +parsePage(String, HttpServletRequest, Charset): String
            +getForwardPage(HttpServletRequest): String
        }

        class DefaultURLConstructor [[DefaultURLConstructor.html]] {
            #m_engine: WikiEngine
            #m_pathPrefix: String
            +initialize(WikiEngine, Properties): void
            #doReplacement(String, String, boolean): String
            {static} +getURLPattern(String, String): String
            +makeURL(String, String, boolean, String): String
            +parsePage(String, HttpServletRequest, Charset): String
            {static} +parsePageFromURL(HttpServletRequest, Charset): String
            +getForwardPage(HttpServletRequest): String
        }

        class ShortViewURLConstructor [[ShortViewURLConstructor.html]] {
            +initialize(WikiEngine, Properties): void
            +makeURL(String, String, boolean, String): String
            +getForwardPage(HttpServletRequest): String
        }

        interface URLConstructor [[URLConstructor.html]] {
            {abstract} +initialize(WikiEngine, Properties): void
            {abstract} +makeURL(String, String, boolean, String): String
            {abstract} +parsePage(String, HttpServletRequest, Charset): String
            {abstract} +getForwardPage(HttpServletRequest): String
        }

        DefaultURLConstructor <|-- ShortURLConstructor

        URLConstructor <|.. DefaultURLConstructor

        ShortURLConstructor <|-- ShortViewURLConstructor

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
