@startuml

    namespace org.apache.wiki.rpc.atom {

        class AtomAPIServlet [[AtomAPIServlet.html]] {
            +init(ServletConfig): void
            +doPost(HttpServletRequest, HttpServletResponse): void
            +doGet(HttpServletRequest, HttpServletResponse): void
            +doDelete(HttpServletRequest, HttpServletResponse): void
            +doPut(HttpServletRequest, HttpServletResponse): void
        }

        abstract class javax.servlet.http.HttpServlet
        javax.servlet.http.HttpServlet <|-- AtomAPIServlet

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
