@startuml

    class JSPWikiLinkAttributeProvider [[JSPWikiLinkAttributeProvider.html]] {
        #wikiContext: WikiContext
        #linkOperations: LinkParsingOperations
        +JSPWikiLinkAttributeProvider(WikiContext)
        +setAttributes(Node, AttributablePart, Attributes): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
