@startuml

    class DefaultSearchManager [[DefaultSearchManager.html]] {
        +DefaultSearchManager(Engine, Properties)
        +initialize(Engine, Properties): void
        +getSearchEngine(): SearchProvider
        +actionPerformed(WikiEvent): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
