@startuml

    class DefaultSearchManager.JSONSearch [[DefaultSearchManager.JSONSearch.html]] {
        {static} +AJAX_ACTION_SUGGESTIONS: String
        {static} +AJAX_ACTION_PAGES: String
        {static} +DEFAULT_MAX_RESULTS: int
        +maxResults: int
        +getServletMapping(): String
        +service(HttpServletRequest, HttpServletResponse, String, List<String>): void
        +getSuggestions(String, int): List<String>
        +findPages(String, int, Context): List<Map<String, Object>>
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
