@startuml

    interface SearchManager [[SearchManager.html]] {
        {static} +DEFAULT_SEARCHPROVIDER: String
        {static} +PROP_SEARCHPROVIDER: String
        {static} +JSON_SEARCH: String
        +findPages(String, WikiContext): Collection<SearchResult>
        +pageRemoved(WikiPage): void
        +reindexPage(WikiPage): void
        {abstract} +getSearchEngine(): SearchProvider
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
