@startuml

    class SearchMatcher.SearchResultImpl [[SearchMatcher.SearchResultImpl.html]] {
        +SearchResultImpl(String, int)
        +getPage(): WikiPage
        +getScore(): int
        +getContexts(): String[]
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
