@startuml

    namespace org.apache.wiki.pages.haddock {

        class LoginPage [[LoginPage.html]] {
            +performLogin(): ReadWikiPage
            +performLogin(String, String): ReadWikiPage
        }

        interface HaddockPage [[HaddockPage.html]] {
            +wikiTitle(): String
            +wikiPageContent(): String
        }

        class ReadWikiPage [[ReadWikiPage.html]] {
            +authenticatedText(): String
            +clickOnLogin(): LoginPage
            +clickOnShowReaderView(): ReadWikiPage
            +hoverLoginArea(): ReadWikiPage
            +hoverMoreArea(): ReadWikiPage
            +logout(): ReadWikiPage
            +navigateTo(String): ReadWikiPage
            +sidebar(): SelenideElement
        }

        HaddockPage <|.. LoginPage

        interface org.apache.wiki.pages.Page {
            {abstract} +wikiTitle(): String
            {abstract} +wikiPageContent(): String
        }
        org.apache.wiki.pages.Page <|.. HaddockPage

        HaddockPage <|.. ReadWikiPage

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
