@startuml

    class DefaultRenderingManager [[DefaultRenderingManager.html]] {
        +initialize(Engine, Properties): void
        +beautifyTitle(String): String
        +beautifyTitleNoBreak(String): String
        +getParser(Context, String): MarkupParser
        +getRenderedDocument(Context, String): WikiDocument
        +getHTML(Context, WikiDocument): String
        +getHTML(Context, Page): String
        +getHTML(String, int): String
        +textToHTML(Context, String): String
        +textToHTML(Context, String, StringTransmutator, StringTransmutator, StringTransmutator, boolean, boolean): String
        +getRenderer(Context, WikiDocument): WikiRenderer
        +getWysiwygRenderer(Context, WikiDocument): WikiRenderer
        +actionPerformed(WikiEvent): void
    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
