@startuml

    namespace org.apache.wiki.api.exceptions {

        class ProviderException [[ProviderException.html]] {
            +ProviderException(String)
        }

        class NoSuchVariableException [[NoSuchVariableException.html]] {
            +NoSuchVariableException(String)
        }

        class NoRequiredPropertyException [[NoRequiredPropertyException.html]] {
            +NoRequiredPropertyException(String, String)
        }

        class FilterException [[FilterException.html]] {
            +FilterException(String)
        }

        class RedirectException [[RedirectException.html]] {
            +RedirectException(String, String)
            +getRedirect(): String
        }

        class WikiException [[WikiException.html]] {
            +WikiException(String)
            +WikiException(String, Throwable)
        }

        class WikiI18nException [[WikiI18nException.html]] {
            #args: Object[]
            +WikiI18nException(String, Object[])
            +getArgs(): Object[]
        }

        class PluginException [[PluginException.html]] {
            +PluginException(String)
            +PluginException(String, Throwable)
            +getRootThrowable(): Throwable
        }

        WikiException <|-- ProviderException

        WikiException <|-- NoSuchVariableException

        WikiException <|-- NoRequiredPropertyException

        WikiException <|-- FilterException

        FilterException <|-- RedirectException

        class java.lang.Exception
        java.lang.Exception <|-- WikiException

        WikiException <|-- WikiI18nException

        WikiException <|-- PluginException

    }


    center footer UMLDoclet 1.1.4, PlantUML 1.2019.05
@enduml
